--合唱圣歌：大小庙产出等于其固定产出信仰的文化值，大小庙分别为圣地周围所有单元格+1文化值。
INSERT INTO RequirementSets (RequirementSetId,RequirementSetType)
	VALUES	('REQUIRE_PLOT_ADJACENT_TO_OWNER','REQUIREMENTSET_TEST_ALL'),
			('REQUIREMENTS_FOLLOWER_SHRINE','REQUIREMENTSET_TEST_ALL'),
			('REQUIREMENTS_FOLLOWER_TEMPLE','REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId)
	VALUES	('REQUIRE_PLOT_ADJACENT_TO_OWNER','ADJACENT_TO_OWNER'),
			('REQUIREMENTS_FOLLOWER_SHRINE','REQUIRES_DISTRICT_IS_HOLY_SITE'),
			('REQUIREMENTS_FOLLOWER_SHRINE','REQUIRES_CITY_FOLLOWS_RELIGION'),
			('REQUIREMENTS_FOLLOWER_SHRINE','REQUIRES_CITY_HAS_SHRINE'),
			('REQUIREMENTS_FOLLOWER_TEMPLE','REQUIRES_DISTRICT_IS_HOLY_SITE'),
			('REQUIREMENTS_FOLLOWER_TEMPLE','REQUIRES_CITY_FOLLOWS_RELIGION'),
			('REQUIREMENTS_FOLLOWER_TEMPLE','REQUIRES_CITY_HAS_TEMPLE');

INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_CHORAL_MUSIC','CHORAL_MUSIC_SHRINE_PLOT'),
			('BELIEF_CHORAL_MUSIC','CHORAL_MUSIC_TEMPLE_PLOT');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('CHORAL_MUSIC_SHRINE_PLOT','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER','REQUIREMENTS_FOLLOWER_SHRINE'),
			('CHORAL_MUSIC_SHRINE_PLOT_MODIFIER','MODIFIER_PLAYER_ADJUST_PLOT_YIELD','REQUIRE_PLOT_ADJACENT_TO_OWNER'),
			('CHORAL_MUSIC_TEMPLE_PLOT','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER','REQUIREMENTS_FOLLOWER_TEMPLE'),
			('CHORAL_MUSIC_TEMPLE_PLOT_MODIFIER','MODIFIER_PLAYER_ADJUST_PLOT_YIELD','REQUIRE_PLOT_ADJACENT_TO_OWNER');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('CHORAL_MUSIC_SHRINE_PLOT','ModifierId','CHORAL_MUSIC_SHRINE_PLOT_MODIFIER'),
			('CHORAL_MUSIC_SHRINE_PLOT_MODIFIER','YieldType','YIELD_CULTURE'),
			('CHORAL_MUSIC_SHRINE_PLOT_MODIFIER','Amount',1),
			('CHORAL_MUSIC_TEMPLE_PLOT','ModifierId','CHORAL_MUSIC_TEMPLE_PLOT_MODIFIER'),
			('CHORAL_MUSIC_TEMPLE_PLOT_MODIFIER','YieldType','YIELD_CULTURE'),
			('CHORAL_MUSIC_TEMPLE_PLOT_MODIFIER','Amount',1);

--神灵启示：奇观建成后返还奇观所需生产力一半的信仰值，所有奇观+4信仰值
--DIVINE_INSPIRATION_WONDER_FAITH



--哺育世界：大小庙+2住房，且分别为六环内所有市中心+3粮
--FEED_THE_WORLD_SHRINE_FOOD3
--FEED_THE_WORLD_TEMPLE_FOOD3
--FEED_THE_WORLD_SHRINE_HOUSING
--FEED_THE_WORLD_TEMPLE_HOUSING
INSERT INTO Requirements (RequirementId,RequirementType)
	VALUES	('ADJACENT_TO_OWNER_6','REQUIREMENT_PLOT_ADJACENT_TO_OWNER');
INSERT INTO RequirementArguments (RequirementId,Name,Value)
	VALUES	('ADJACENT_TO_OWNER_6','MinDistance',0),
			('ADJACENT_TO_OWNER_6','MaxDistance',6);
INSERT INTO RequirementSets (RequirementSetId,RequirementSetType)
	VALUES	('REQUIRE_PLOT_ADJACENT_TO_OWNER_6','REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId)
	VALUES	('REQUIRE_PLOT_ADJACENT_TO_OWNER_6','ADJACENT_TO_OWNER_6'),
			('REQUIRE_PLOT_ADJACENT_TO_OWNER_6','REQUIRES_DISTRICT_IS_CITY_CENTER');

UPDATE BeliefModifiers SET ModifierId = 'FEED_THE_WORLD_SHRINE_REGIONAL' WHERE ModifierId = 'FEED_THE_WORLD_SHRINE_FOOD3';
UPDATE BeliefModifiers SET ModifierId = 'FEED_THE_WORLD_TEMPLE_REGIONAL' WHERE ModifierId = 'FEED_THE_WORLD_TEMPLE_FOOD3';

INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('FEED_THE_WORLD_SHRINE_REGIONAL','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER','REQUIREMENTS_FOLLOWER_SHRINE'),
			('FEED_THE_WORLD_SHRINE_REGIONAL_MODIFIER','MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE','REQUIRE_PLOT_ADJACENT_TO_OWNER_6'),
			('FEED_THE_WORLD_TEMPLE_REGIONAL','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER','REQUIREMENTS_FOLLOWER_TEMPLE'),
			('FEED_THE_WORLD_TEMPLE_REGIONAL_MODIFIER','MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE','REQUIRE_PLOT_ADJACENT_TO_OWNER_6');

INSERT INTO ModifierArguments(ModifierId,Name,Value)
	VALUES	('FEED_THE_WORLD_SHRINE_REGIONAL','ModifierId','FEED_THE_WORLD_SHRINE_REGIONAL_MODIFIER'),
			('FEED_THE_WORLD_SHRINE_REGIONAL_MODIFIER','Amount',3),
			('FEED_THE_WORLD_SHRINE_REGIONAL_MODIFIER','YieldType','YIELD_FOOD'),
			('FEED_THE_WORLD_TEMPLE_REGIONAL','ModifierId','FEED_THE_WORLD_TEMPLE_REGIONAL_MODIFIER'),
			('FEED_THE_WORLD_TEMPLE_REGIONAL_MODIFIER','Amount',3),
			('FEED_THE_WORLD_TEMPLE_REGIONAL_MODIFIER','YieldType','YIELD_FOOD');

--耶稣会教育：可使用信仰值购买学院和剧院建筑，城市产出信仰值的15%转化为科技和文化值。
--JESUIT_EDUCATION_CULTURE_BUILDINGS
--JESUIT_EDUCATION_SCIENCE_BUILDINGS
INSERT INTO Types 
	(Type,																		Kind)
VALUES
	('MODIFIER_H_BELIEF_SINGLE_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH',			'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,																CollectionType,					EffectType)
VALUES
	('MODIFIER_H_BELIEF_SINGLE_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH',			'COLLECTION_OWNER',				'EFFECT_ADJUST_CITY_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_JESUIT_EDUCATION','JESUIT_EDUCATION_FAITH_TO_CULTURE'),
			('BELIEF_JESUIT_EDUCATION','JESUIT_EDUCATION_FAITH_TO_SCIENCE');
INSERT INTO Modifiers (ModifierId,															ModifierType,																		SubjectRequirementSetId)
	VALUES	('JESUIT_EDUCATION_FAITH_TO_CULTURE',											'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',												'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
			('JESUIT_EDUCATION_FAITH_TO_CULTURE_MODIFIER',									'MODIFIER_H_BELIEF_SINGLE_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH',					NULL),
			('JESUIT_EDUCATION_FAITH_TO_SCIENCE',											'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',												'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
			('JESUIT_EDUCATION_FAITH_TO_SCIENCE_MODIFIER',									'MODIFIER_H_BELIEF_SINGLE_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH',					NULL);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('JESUIT_EDUCATION_FAITH_TO_CULTURE','ModifierId','JESUIT_EDUCATION_FAITH_TO_CULTURE_MODIFIER'),
			('JESUIT_EDUCATION_FAITH_TO_CULTURE_MODIFIER','YieldType','YIELD_CULTURE'),
			('JESUIT_EDUCATION_FAITH_TO_CULTURE_MODIFIER','Amount',15),
			('JESUIT_EDUCATION_FAITH_TO_SCIENCE','ModifierId','JESUIT_EDUCATION_FAITH_TO_SCIENCE_MODIFIER'),
			('JESUIT_EDUCATION_FAITH_TO_SCIENCE_MODIFIER','YieldType','YIELD_SCIENCE'),
			('JESUIT_EDUCATION_FAITH_TO_SCIENCE_MODIFIER','Amount',15);

--圣物箱：不变
--RELIQUARIES_RELIC_FAITH
--RELIQUARIES_RELIC_TOURISM

--武僧：允许训练武僧，圣地建成后触发文化炸弹，可使用信仰值购买平民单位
--ALLOW_WARRIOR_MONKS
--WARRIOR_MONKS_CULTURE_BOMB_TRIGGER_HOLY_SITE
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_WARRIOR_MONKS','WARRIOR_MONKS_PURCHASE_CIVILIAN');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('WARRIOR_MONKS_PURCHASE_CIVILIAN','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
			('WARRIOR_MONKS_PURCHASE_CIVILIAN_MODIFIER','MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',NULL);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('WARRIOR_MONKS_PURCHASE_CIVILIAN','ModifierId','WARRIOR_MONKS_PURCHASE_CIVILIAN_MODIFIER'),
			('WARRIOR_MONKS_PURCHASE_CIVILIAN_MODIFIER','Tag','CLASS_LANDCIVILIAN');			


--职业道德：
--WORK ETHIC holy sites provide +3 production, increased to +5 production if the district has at least +4 adjacency bonus 

UPDATE BeliefModifiers SET ModifierID = 'JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY' WHERE BeliefType = 'BELIEF_WORK_ETHIC' AND ModifierID = 'WORK_ETHIC_ADJACENCY_PRODUCTION_2' ;

INSERT INTO BeliefModifiers
		(BeliefType,           ModifierID)
VALUES	('BELIEF_WORK_ETHIC', 'JAVYZ_WORK_ETHIC_PRODUCTION');


INSERT OR REPLACE INTO DynamicModifiers
		(ModifierType,                                  CollectionType,               EffectType)
VALUES	('MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 'COLLECTION_CITY_DISTRICTS', 'EFFECT_ADJUST_DISTRICT_YIELD_CHANGE');

INSERT INTO Types
		(Type,                                          Kind)
VALUES	('MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 'KIND_MODIFIER');

INSERT INTO Modifiers
		(ModifierId,                              ModifierType,                                 SubjectRequirementSetId)
VALUES	('JAVYZ_WORK_ETHIC_PRODUCTION',          'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',         'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_MODIFIER', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 'JAVYZ_WORK_ETHIC_REQUIREMENTS');
		
INSERT INTO ModifierArguments
		(ModifierId,                              Name,         Value)
VALUES	('JAVYZ_WORK_ETHIC_PRODUCTION',          'ModifierId', 'JAVYZ_WORK_ETHIC_PRODUCTION_MODIFIER'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_MODIFIER', 'Amount',     3);

INSERT INTO Modifiers
		(ModifierId,                                            ModifierType,                                  SubjectRequirementSetId)
VALUES	('JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY',          'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',         'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY_MODIFIER', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 'JAVYZ_WORK_ETHIC_HIGHADJACENCY_REQUIREMENTS');

INSERT INTO ModifierArguments
		(ModifierId,                                            Name,          Value)
VALUES	('JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY',          'ModifierId',  'JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY_MODIFIER'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY_MODIFIER', 'YieldType',   'YIELD_PRODUCTION'),
		('JAVYZ_WORK_ETHIC_PRODUCTION_HIGHADJACENCY_MODIFIER', 'Amount',      2);

INSERT INTO RequirementSets
		(RequirementSetId,                               RequirementSetType)
VALUES	('JAVYZ_WORK_ETHIC_HIGHADJACENCY_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
		('JAVYZ_WORK_ETHIC_REQUIREMENTS',               'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,								 RequirementId)
VALUES	('JAVYZ_WORK_ETHIC_HIGHADJACENCY_REQUIREMENTS', 'REQUIRES_HOLY_SITE_HAS_HIGH_ADJACENCY'),
		('JAVYZ_WORK_ETHIC_HIGHADJACENCY_REQUIREMENTS', 'REQUIRES_DISTRICT_IS_HOLY_SITE'),
		('JAVYZ_WORK_ETHIC_HIGHADJACENCY_REQUIREMENTS', 'REQUIRES_CITY_FOLLOWS_RELIGION'),
		('JAVYZ_WORK_ETHIC_REQUIREMENTS',               'REQUIRES_DISTRICT_IS_HOLY_SITE'),
		('JAVYZ_WORK_ETHIC_REQUIREMENTS',               'REQUIRES_CITY_FOLLOWS_RELIGION');

--禅修：拥有两个专业化区域的城市+2宜居，若城市为快乐，信仰值产出的宜居度加成提升至25%，若为欣喜若狂，则提升至50%。
--ZEN_MEDITATION_AMENITY
INSERT INTO Types 
	(Type,																		Kind)
VALUES
	('MODIFIER_H_SINGLE_CITY_ADJUST_HAPPINESS_YIELD',							'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,																CollectionType,					EffectType)
VALUES
	('MODIFIER_H_SINGLE_CITY_ADJUST_HAPPINESS_YIELD',							'COLLECTION_OWNER',				'EFFECT_ADJUST_CITY_HAPPINESS_YIELD');

INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_ZEN_MEDITATION','ZEN_MEDITATION_FAITH_ADJUST_HAPPY'),
			('BELIEF_ZEN_MEDITATION','ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('ZEN_MEDITATION_FAITH_ADJUST_HAPPY','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
			('ZEN_MEDITATION_FAITH_ADJUST_HAPPY_MODIFIER','MODIFIER_H_SINGLE_CITY_ADJUST_HAPPINESS_YIELD',NULL),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC_MODIFIER','MODIFIER_H_SINGLE_CITY_ADJUST_HAPPINESS_YIELD',NULL);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('ZEN_MEDITATION_FAITH_ADJUST_HAPPY','ModifierId','ZEN_MEDITATION_FAITH_ADJUST_HAPPY_MODIFIER'),
			('ZEN_MEDITATION_FAITH_ADJUST_HAPPY_MODIFIER','HappinessType','HAPPINESS_HAPPY'),
			('ZEN_MEDITATION_FAITH_ADJUST_HAPPY_MODIFIER','YieldType','YIELD_FAITH'),
			('ZEN_MEDITATION_FAITH_ADJUST_HAPPY_MODIFIER','Amount',15),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC','ModifierId','ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC_MODIFIER'),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC_MODIFIER','HappinessType','HAPPINESS_ECSTATIC'),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC_MODIFIER','YieldType','YIELD_FAITH'),
			('ZEN_MEDITATION_FAITH_ADJUST_ECSTATIC_MODIFIER','Amount',30);

UPDATE ModifierArguments SET Value = 2 WHERE ModifierId = 'ZEN_MEDITATION_AMENITY_MODIFIER' AND Name = 'Amount';

UPDATE Beliefs SET Description = 'LOC_BELIEF_CHORAL_MUSIC_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_CHORAL_MUSIC';
UPDATE Beliefs SET Description = 'LOC_BELIEF_FEED_THE_WORLD_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_FEED_THE_WORLD';
UPDATE Beliefs SET Description = 'LOC_BELIEF_JESUIT_EDUCATION_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_JESUIT_EDUCATION';
UPDATE Beliefs SET Description = 'LOC_BELIEF_WARRIOR_MONKS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_WARRIOR_MONKS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_ZEN_MEDITATION_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_ZEN_MEDITATION';