INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_UNIT_GREAT_MONUMENT','ICON_ATLAS_UNITS',10);

INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_UNIT_GREAT_MONUMENT_PORTRAIT','ICON_ATLAS_UNIT_PORTRAITS',10);

INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_ETHNICITY_ASIAN_UNIT_GREAT_MONUMENT_PORTRAIT','ICON_ATLAS_ASIAN_UNIT_PORTRAITS',10);

INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_ETHNICITY_MEDIT_UNIT_GREAT_MONUMENT_PORTRAIT','ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS',10);

INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_ETHNICITY_SOUTHAM_UNIT_GREAT_MONUMENT_PORTRAIT','ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS',10);

INSERT OR REPLACE INTO IconDefinitions (Name,Atlas,'Index')	VALUES
('ICON_ETHNICITY_AFRICAN_UNIT_GREAT_MONUMENT_PORTRAIT','ICON_ATLAS_AFRICAN_UNIT_PORTRAITS',10);