INSERT INTO Types (Type,Kind)
	VALUES	('GREAT_PERSON_CLASS_MONUMENT','KIND_GREAT_PERSON_CLASS'),
			('GREAT_PERSON_INDIVIDUAL_MONUMENT','KIND_GREAT_PERSON_INDIVIDUAL'),
			('UNIT_GREAT_MONUMENT','KIND_UNIT');
INSERT INTO TypeTags (Type,Tag)
	VALUES	('UNIT_GREAT_MONUMENT','CLASS_LANDCIVILIAN');

--城市守护女神：没有特色区域的城市建造区域时+100%生产力
UPDATE ModifierArguments SET Value = 100 WHERE ModifierId = 'CITY_PATRON_GODDESS_DISTRICT_PRODUCTION_MODIFIER';

--大地女神：魅力为美丽的单元格提供的信仰+1,魅力为惊艳的单元格提供的信仰+2
--EARTH_GODDESS_APPEAL_FAITH
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES  ('BELIEF_EARTH_GODDESS','EARTH_GODDESS_APPEAL_FAITH_CHARMING');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES  ('EARTH_GODDESS_APPEAL_FAITH_CHARMING','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
		    ('EARTH_GODDESS_APPEAL_FAITH_MODIFIER_CHARMING','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_CHARMING_APPEAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('EARTH_GODDESS_APPEAL_FAITH_CHARMING','ModifierId','EARTH_GODDESS_APPEAL_FAITH_MODIFIER_CHARMING'),
			('EARTH_GODDESS_APPEAL_FAITH_MODIFIER_CHARMING','YieldType','YIELD_FAITH'),
			('EARTH_GODDESS_APPEAL_FAITH_MODIFIER_CHARMING','Amount',1);

--神圣之光：圣地,学院,剧院地基+1伟人点
--DIVINE_SPARK_HOLY_SITE
--DIVINE_SPARK_SCIENTIST
--DIVINE_SPARK_WRITER
UPDATE Modifiers SET SubjectRequirementSetId = 'DISTRICT_IS_CAMPUS' WHERE ModifierId = 'DIVINE_SPARK_SCIENTIST_MODIFIER';
UPDATE Modifiers SET SubjectRequirementSetId = 'DISTRICT_IS_THEATER' WHERE ModifierId = 'DIVINE_SPARK_WRITER_MODIFIER';
UPDATE Modifiers SET ModifierType = 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS' WHERE ModifierId = 'DIVINE_SPARK_SCIENTIST_MODIFIER' OR ModifierId = 'DIVINE_SPARK_WRITER_MODIFIER';


--火之女神：所有火山土和地热裂缝+1琴1鸽
--GODDESS_OF_FIRE_FEATURES_FAITH
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_GODDESS_OF_FIRE','GODDESS_OF_FIRE_FEATURES_CULTURE');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('GODDESS_OF_FIRE_FEATURES_CULTURE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('GODDESS_OF_FIRE_FEATURES_CULTURE_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_GODDES_FIRE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('GODDESS_OF_FIRE_FEATURES_CULTURE','ModifierId','GODDESS_OF_FIRE_FEATURES_CULTURE_MODIFIER'),
			('GODDESS_OF_FIRE_FEATURES_CULTURE_MODIFIER','YieldType','YIELD_CULTURE'),
			('GODDESS_OF_FIRE_FEATURES_CULTURE_MODIFIER','Amount',1);
UPDATE ModifierArguments SET Value = 1 WHERE ModifierId = 'GODDESS_OF_FIRE_FEATURES_FAITH_MODIFIER' AND Name = 'Amount';

--工匠之神：不变

--愈合之神：转生君主崇拜,效果为送一个总督点
INSERT INTO BeliefModifiers (BeliefType,ModifierId)
	VALUES	('BELIEF_GOD_OF_HEALING','GOD_KING_GOVERNOR');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId,RunOnce,Permanent)
	VALUES	('GOD_KING_GOVERNOR','MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER','PLAYER_HAS_PANTHEON_REQUIREMENTS',0,0),
			('GOD_KING_GOVERNOR_MODIFIER','MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',NULL,1,1);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('GOD_KING_GOVERNOR','ModifierId','GOD_KING_GOVERNOR_MODIFIER'),
			('GOD_KING_GOVERNOR_MODIFIER','Delta',1);


--锻造之神：生产远古古典军事单位+25%生产力,每训练一个军事单位获得20%所需生产力的文化
--GOD_OF_THE_FORGE_UNIT_ANCIENT_CLASSICAL_PRODUCTION
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_GOD_OF_THE_FORGE','GOD_OF_THE_FORGE_UNIT_CULTURE');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('GOD_OF_THE_FORGE_UNIT_CULTURE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('GOD_OF_THE_FORGE_UNIT_CULTURE_MODIFIER','MODIFIER_PLAYER_CITIES_GRANT_YIELD_PER_UNIT_COST',NULL);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('GOD_OF_THE_FORGE_UNIT_CULTURE','ModifierId','GOD_OF_THE_FORGE_UNIT_CULTURE_MODIFIER'),
			('GOD_OF_THE_FORGE_UNIT_CULTURE_MODIFIER','YieldType','YIELD_CULTURE'),
			('GOD_OF_THE_FORGE_UNIT_CULTURE_MODIFIER','UnitProductionPercent',20);
			
--天空之神：不变

--海洋之神：所有渔船+1锤1瓶
--GOD_OF_THE_SEA_FISHINGBOATS_PRODUCTION
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_GOD_OF_THE_SEA','GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_FISHINGBOATS_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE','ModifierId','GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE_MODIFIER'),
			('GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE_MODIFIER','YieldType','YIELD_SCIENCE'),
			('GOD_OF_THE_SEA_FISHINGBOATS_SCIENCE_MODIFIER','Amount',1);

--战争之神：改名水之女神,效果为沿海的圣地+2信仰，圣地从相邻水域单元格获得标准相邻加成
DELETE FROM BeliefModifiers WHERE BeliefType = 'BELIEF_GOD_OF_WAR';
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_GOD_OF_WAR','GODDESS_OF_WATER_BASE'),
			('BELIEF_GOD_OF_WAR','GODDESS_OF_WATER_ADJ');

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId)
	VALUES  ('GODDESS_OF_WATER_REQUIREMENTS','REQUIRES_PLOT_IS_ADJACENT_TO_COAST'),
			('GODDESS_OF_WATER_REQUIREMENTS','REQUIRES_DISTRICT_IS_HOLY_SITE');
INSERT INTO RequirementSets (RequirementSetId,RequirementSetType)
	VALUES  ('GODDESS_OF_WATER_REQUIREMENTS','REQUIREMENTSET_TEST_ALL');


INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('GODDESS_OF_WATER_BASE','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('GODDESS_OF_WATER_BASE_MODIFIER','MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE','GODDESS_OF_WATER_REQUIREMENTS'),
			('GODDESS_OF_WATER_ADJ','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('GODDESS_OF_WATER_BASE','ModifierId','GODDESS_OF_WATER_BASE_MODIFIER'),
			('GODDESS_OF_WATER_BASE_MODIFIER','YieldType','YIELD_FAITH'),
			('GODDESS_OF_WATER_BASE_MODIFIER','Amount',2),
			('GODDESS_OF_WATER_ADJ','DistrictType','DISTRICT_HOLY_SITE'),
			('GODDESS_OF_WATER_ADJ','TerrainType','TERRAIN_COAST'),
			('GODDESS_OF_WATER_ADJ','YieldType','YIELD_FAITH'),
			('GODDESS_OF_WATER_ADJ','Amount',1),
			('GODDESS_OF_WATER_ADJ','Description','LOC_DISTRICT_COAST_FAITH');


--节庆女神：不变

--狩猎女神：不变

--启蒙会：清理蛮族哨站时获得一个部落村庄奖励,清寨子单位回满血
--INITIATION_RITES_FAITH_DISPERSAL
--INITIATION_RITES_HEALING_DISPERSAL
UPDATE BeliefModifiers SET ModifierId = 'INITIATION_RITES_GOODY_HUT' WHERE ModifierId = 'INITIATION_RITES_FAITH_DISPERSAL';
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('INITIATION_RITES_GOODY_HUT','MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER','PLAYER_HAS_PANTHEON_REQUIREMENTS'),
			('INITIATION_RITES_GOODY_HUT_MODIFIER','MODIFIER_PLAYER_ADJUST_IMPROVEMENT_GOODY_HUT',NULL);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('INITIATION_RITES_GOODY_HUT','ModifierId','INITIATION_RITES_GOODY_HUT_MODIFIER'),
			('INITIATION_RITES_GOODY_HUT_MODIFIER','ImprovementType','IMPROVEMENT_BARBARIAN_CAMP'),
			('INITIATION_RITES_GOODY_HUT_MODIFIER','GoodyHutImprovementType','IMPROVEMENT_GOODY_HUT');

--烂地夫人：不变

--宗教偶像：改良奢侈和加成资源的矿山+1粮1鸽
--RELIGIOUS_IDOLS_BONUS_MINE_FAITH
--RELIGIOUS_IDOLS_LUXURY_MINE_FAITH
INSERT INTO BeliefModifiers (BeliefType,ModifierID)
	VALUES	('BELIEF_RELIGIOUS_IDOLS','RELIGIOUS_IDOLS_BONUS_MINE_FOOD'),
			('BELIEF_RELIGIOUS_IDOLS','RELIGIOUS_IDOLS_LUXURY_MINE_FOOD');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId)
	VALUES	('RELIGIOUS_IDOLS_BONUS_MINE_FOOD','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('RELIGIOUS_IDOLS_BONUS_MINE_FOOD_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_BONUS_MINE_REQUIREMENTS'),
			('RELIGIOUS_IDOLS_LUXURY_MINE_FOOD','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
			('RELIGIOUS_IDOLS_LUXURY_MINE_FOOD_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_LUXURY_MINE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('RELIGIOUS_IDOLS_BONUS_MINE_FOOD','ModifierId','RELIGIOUS_IDOLS_BONUS_MINE_FOOD_MODIFIER'),
			('RELIGIOUS_IDOLS_BONUS_MINE_FOOD_MODIFIER','YieldType','YIELD_FOOD'),
			('RELIGIOUS_IDOLS_BONUS_MINE_FOOD_MODIFIER','Amount',1),
			('RELIGIOUS_IDOLS_LUXURY_MINE_FOOD','ModifierId','RELIGIOUS_IDOLS_LUXURY_MINE_FOOD_MODIFIER'),
			('RELIGIOUS_IDOLS_LUXURY_MINE_FOOD_MODIFIER','YieldType','YIELD_FOOD'),
			('RELIGIOUS_IDOLS_LUXURY_MINE_FOOD_MODIFIER','Amount',1);
UPDATE ModifierArguments SET Value = 1 WHERE ModifierId = 'RELIGIOUS_IDOLS_BONUS_MINE_FAITH_MODIFIER' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 1 WHERE ModifierId = 'RELIGIOUS_IDOLS_LUXURY_MINE_FAITH_MODIFIER' AND Name = 'Amount';

--宗教移民：不变

--主神纪念碑：首都立刻获得一名特殊大工程师,他拥有一次使用次数,可以立刻为远古奇观提供110生产力
UPDATE BeliefModifiers SET ModifierId = 'MONUMENT_TO_THE_GODS_GREAT_PERSON' WHERE BeliefType = 'BELIEF_MONUMENT_TO_THE_GODS' AND ModifierId = 'MONUMENT_TO_THE_GODS_ANCIENTCLASSICALWONDER';
INSERT INTO UnitAiInfos (UnitType,AiType)
	VALUES	('UNIT_GREAT_MONUMENT','UNITTYPE_CIVILIAN');
INSERT INTO Units (UnitType,Name,BaseSightRange,BaseMoves,Domain,FormationClass,Cost,Description,CanCapture,CanRetreatWhenCaptured,CanTrain)
	VALUES	('UNIT_GREAT_MONUMENT','LOC_UNIT_GREAT_MONUMENT_NAME',2,4,'DOMAIN_LAND','FORMATION_CLASS_CIVILIAN',1,'LOC_UNIT_GREAT_MONUMENT_DESCRIPTION',0,1,0);
INSERT INTO Units_XP2 (UnitType,CanEarnExperience,CanFormMilitaryFormation)
	VALUES	('UNIT_GREAT_MONUMENT',0,0);

INSERT INTO GreatPersonClasses (GreatPersonClassType,Name,UnitType,DistrictType,PseudoYieldType,IconString,ActionIcon,AvailableInTimeline,GenerateDuplicateIndividuals)
	VALUES	('GREAT_PERSON_CLASS_MONUMENT','LOC_GREAT_PERSON_CLASS_MONUMENT_NAME','UNIT_GREAT_MONUMENT','DISTRICT_ENCAMPMENT','PSEUDOYIELD_GPP_ENGINEER','[ICON_GreatEngineer]','ICON_UNIT_GREAT_MONUMENT',0,1);

INSERT INTO GreatPersonIndividuals (GreatPersonIndividualType,Name,GreatPersonClassType,EraType,ActionCharges,ActionRequiresIncompleteWonder,Gender)
	VALUES	('GREAT_PERSON_INDIVIDUAL_MONUMENT','LOC_GREAT_PERSON_INDIVIDUAL_MONUMENT_NAME','GREAT_PERSON_CLASS_MONUMENT','ERA_ANCIENT',1,1,'M');
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType,ModifierId,AttachmentTargetType)
	VALUES	('GREAT_PERSON_INDIVIDUAL_MONUMENT','GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_ANCIENT','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_WONDER_IN_TILE');	
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType,ModifierId,AttachmentTargetType)
	VALUES	('GREAT_PERSON_INDIVIDUAL_MONUMENT','GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_OTHER','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_WONDER_IN_TILE');	

INSERT INTO Requirements (RequirementId,RequirementType,Inverse)
	VALUES	('REQUIRE_THIS_WONDER_IS_ANCIENT','REQUIREMENT_PLOT_WONDER_IS_ERA',0),
			('REQUIRE_THIS_WONDER_IS_ANCIENT_INVERSE','REQUIREMENT_PLOT_WONDER_IS_ERA',1);
INSERT INTO RequirementArguments (RequirementId,Name,Value)
	VALUES	('REQUIRE_THIS_WONDER_IS_ANCIENT','EarliestEra','ERA_ANCIENT'),
			('REQUIRE_THIS_WONDER_IS_ANCIENT','LatestEra','ERA_ANCIENT'),
			('REQUIRE_THIS_WONDER_IS_ANCIENT_INVERSE','EarliestEra','ERA_ANCIENT'),
			('REQUIRE_THIS_WONDER_IS_ANCIENT_INVERSE','LatestEra','ERA_ANCIENT');
INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId)
	VALUES	('THIS_WONDER_IS_ANCIENT','REQUIRE_THIS_WONDER_IS_ANCIENT'),
			('THIS_WONDER_IS_ANCIENT_INVERSE','REQUIRE_THIS_WONDER_IS_ANCIENT_INVERSE');
INSERT INTO RequirementSets (RequirementSetId,RequirementSetType)
	VALUES	('THIS_WONDER_IS_ANCIENT','REQUIREMENTSET_TEST_ALL'),
			('THIS_WONDER_IS_ANCIENT_INVERSE','REQUIREMENTSET_TEST_ALL');						

INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId,RunOnce,Permanent)
	VALUES	('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_ANCIENT','MODIFIER_SINGLE_CITY_GRANT_PRODUCTION_IN_CITY','THIS_WONDER_IS_ANCIENT',1,1),
			('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_OTHER','MODIFIER_SINGLE_CITY_GRANT_PRODUCTION_IN_CITY','THIS_WONDER_IS_ANCIENT_INVERSE',1,1);
INSERT INTO ModifierArguments (ModifierId,Name,Type,Value)
	VALUES	('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_ANCIENT','Amount','ScaleByGameSpeed',110),
			('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_ANCIENT','KeepOverflow','ARGTYPE_IDENTITY',0),
			('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_OTHER','Amount','ScaleByGameSpeed',10),
			('GREAT_PERSON_INDIVIDUAL_MONUMENT_PRODUCTION_OTHER','KeepOverflow','ARGTYPE_IDENTITY',0);	
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId,RunOnce,Permanent)
	VALUES	('MONUMENT_TO_THE_GODS_GREAT_PERSON','MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER','PLAYER_HAS_PANTHEON_REQUIREMENTS',0,0),
			('MONUMENT_TO_THE_GODS_GREAT_PERSON_MODIFIER','MODIFIER_PLAYER_ADJUST_GREAT_PERSON_GUARANTEE','PLAYER_HAS_AT_LEAST_ONE_CITY_REQUIREMENTS',1,1);
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES	('MONUMENT_TO_THE_GODS_GREAT_PERSON','ModifierId','MONUMENT_TO_THE_GODS_GREAT_PERSON_MODIFIER'),
			('MONUMENT_TO_THE_GODS_GREAT_PERSON_MODIFIER','GreatPersonClassType','GREAT_PERSON_CLASS_MONUMENT');

--河神：所有沿河专业化区域+1相邻加成,沿河圣地+2住房+2宜居
INSERT INTO BeliefModifiers (BeliefType,ModifierId)
	VALUES	('BELIEF_RIVER_GODDESS','RIVER_GODDESS_CAMPUS_ADJ'),
			('BELIEF_RIVER_GODDESS','RIVER_GODDESS_COMMERCIAL_ADJ'),
			('BELIEF_RIVER_GODDESS','RIVER_GODDESS_HOLY_SITE_ADJ'),
			('BELIEF_RIVER_GODDESS','RIVER_GODDESS_INDUSTRIAL_ADJ'),
			('BELIEF_RIVER_GODDESS','RIVER_GODDESS_THEATER_ADJ');

INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId,SubjectStackLimit)
	VALUES  ('RIVER_GODDESS_CAMPUS_ADJ','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS',NULL),
			('RIVER_GODDESS_COMMERCIAL_ADJ','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS',NULL),
			('RIVER_GODDESS_HOLY_SITE_ADJ','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS',NULL),
			('RIVER_GODDESS_INDUSTRIAL_ADJ','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS',NULL),
			('RIVER_GODDESS_THEATER_ADJ','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS',NULL),
			('RIVER_GODDESS_CAMPUS_ADJ_MODIFIER','MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',NULL,1),
			('RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER','MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',NULL,1),
			('RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER','MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',NULL,1),
			('RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER','MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',NULL,1),
			('RIVER_GODDESS_THEATER_ADJ_MODIFIER','MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',NULL,1);

INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES  ('RIVER_GODDESS_CAMPUS_ADJ','ModifierId','RIVER_GODDESS_CAMPUS_ADJ_MODIFIER'),
			('RIVER_GODDESS_COMMERCIAL_ADJ','ModifierId','RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER'),
			('RIVER_GODDESS_HOLY_SITE_ADJ','ModifierId','RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER'),
			('RIVER_GODDESS_INDUSTRIAL_ADJ','ModifierId','RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER'),
			('RIVER_GODDESS_THEATER_ADJ','ModifierId','RIVER_GODDESS_THEATER_ADJ_MODIFIER'),
			('RIVER_GODDESS_CAMPUS_ADJ_MODIFIER','Amount',1),
			('RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER','Amount',1),
			('RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER','Amount',1),
			('RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER','Amount',1),
			('RIVER_GODDESS_THEATER_ADJ_MODIFIER','Amount',1),
			('RIVER_GODDESS_CAMPUS_ADJ_MODIFIER','Description','LOC_RIVER_GODDESS_CAMPUS_ADJ_H_DESCRIPTION'),
			('RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER','Description','LOC_RIVER_GODDESS_COMMERCIAL_ADJ_H_DESCRIPTION'),
			('RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER','Description','LOC_RIVER_GODDESS_HOLY_SITE_ADJ_H_DESCRIPTION'),
			('RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER','Description','LOC_RIVER_GODDESS_INDUSTRIAL_ADJ_H_DESCRIPTION'),
			('RIVER_GODDESS_THEATER_ADJ_MODIFIER','Description','LOC_RIVER_GODDESS_THEATER_ADJ_H_DESCRIPTION'),
			('RIVER_GODDESS_CAMPUS_ADJ_MODIFIER','DistrictType','DISTRICT_CAMPUS'),
			('RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER','DistrictType','DISTRICT_COMMERCIAL'),
			('RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER','DistrictType','DISTRICT_HOLY_SITE'),
			('RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER','DistrictType','DISTRICT_INDUSTRIAL'),
			('RIVER_GODDESS_THEATER_ADJ_MODIFIER','DistrictType','DISTRICT_THEATER'),
			('RIVER_GODDESS_CAMPUS_ADJ_MODIFIER','YieldType','YIELD_SCIENCE'),
			('RIVER_GODDESS_COMMERCIAL_ADJ_MODIFIER','YieldType','YIELD_GOLD'),
			('RIVER_GODDESS_HOLY_SITE_ADJ_MODIFIER','YieldType','YIELD_FAITH'),
			('RIVER_GODDESS_INDUSTRIAL_ADJ_MODIFIER','YieldType','YIELD_PRODUCTION'),
			('RIVER_GODDESS_THEATER_ADJ_MODIFIER','YieldType','YIELD_CULTURE');

--新万神：国境内所有特色改良设施的每种基础产出+1,若为金币则+2。
DELETE FROM BeliefModifiers WHERE BeliefType = 'BELIEF_STONE_CIRCLES';

INSERT INTO BeliefModifiers (BeliefType,ModifierId) VALUES ('BELIEF_STONE_CIRCLES','GENSHIN_FOOD_UI'),
                                                           ('BELIEF_STONE_CIRCLES','GENSHIN_PRODUCTION_UI'),
                                                           ('BELIEF_STONE_CIRCLES','GENSHIN_CULTURE_UI'),
                                                           ('BELIEF_STONE_CIRCLES','GENSHIN_SCIENCE_UI'),
                                                           ('BELIEF_STONE_CIRCLES','GENSHIN_FAITH_UI'),
                                                           ('BELIEF_STONE_CIRCLES','GENSHIN_GOLD_UI');

CREATE TABLE Improvement_HPatheon (
    ImprovementType TEXT    PRIMARY KEY
                            REFERENCES Improvements (ImprovementType) 
                            NOT NULL
                            DEFAULT NULL,
    IsFoodUI        BOOLEAN CHECK (IsFoodUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0),
    IsProductionUI  BOOLEAN CHECK (IsProductionUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0),
    IsCultureUI     BOOLEAN CHECK (IsCultureUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0),
    IsScienceUI     BOOLEAN CHECK (IsScienceUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0),
    IsFaithUI       BOOLEAN CHECK (IsFaithUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0),
    IsGoldUI        BOOLEAN CHECK (IsGoldUI IN (0, 1) ) 
                            NOT NULL
                            DEFAULT (0) 
);

INSERT INTO Improvement_HPatheon (ImprovementType) SELECT ImprovementType FROM Improvements WHERE TraitType IS NOT NULL;

UPDATE Improvement_HPatheon SET IsFoodUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_FOOD' AND YieldChange <> 0);

UPDATE Improvement_HPatheon SET IsProductionUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_PRODUCTION' AND YieldChange <> 0);

UPDATE Improvement_HPatheon SET IsCultureUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_CULTURE' AND YieldChange <> 0);

UPDATE Improvement_HPatheon SET IsScienceUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_SCIENCE' AND YieldChange <> 0);

UPDATE Improvement_HPatheon SET IsFaithUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_FAITH' AND YieldChange <> 0);

UPDATE Improvement_HPatheon SET IsGoldUI = 1 WHERE EXISTS (SELECT YieldType,YieldChange FROM Improvement_YieldChanges WHERE Improvement_HPatheon.ImprovementType = Improvement_YieldChanges.ImprovementType AND YieldType = 'YIELD_GOLD' AND YieldChange <> 0);

INSERT INTO Requirements (RequirementId, RequirementType) SELECT 'REQUIRES_PLOT_HAS_' || ImprovementType, 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES' ImprovementType FROM Improvement_HPatheon;

INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) SELECT 'REQUIRES_PLOT_HAS_' || ImprovementType, 'ImprovementType', ImprovementType FROM Improvement_HPatheon;

INSERT INTO RequirementSets (RequirementSetId,RequirementSetType) VALUES ('PLOT_HAS_FOOD_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY'),
                                                                         ('PLOT_HAS_PRODUCTION_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY'),
                                                                         ('PLOT_HAS_CULTURE_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY'),
                                                                         ('PLOT_HAS_SCIENCE_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY'),
                                                                         ('PLOT_HAS_FAITH_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY'),
                                                                         ('PLOT_HAS_GOLD_UI_REQUIREMENTS','REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_FOOD_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsFoodUI = 1;

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_PRODUCTION_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsProductionUI = 1;

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_CULTURE_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsCultureUI = 1;

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_SCIENCE_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsScienceUI = 1;

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_FAITH_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsFaithUI = 1;

INSERT INTO RequirementSetRequirements (RequirementSetId,RequirementId) SELECT 'PLOT_HAS_GOLD_UI_REQUIREMENTS', 'REQUIRES_PLOT_HAS_' || ImprovementType FROM Improvement_HPatheon  WHERE IsGoldUI = 1;

INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId) VALUES ('GENSHIN_FOOD_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_FOOD_UI_REQUIREMENTS'),
                                                                               ('GENSHIN_PRODUCTION_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_PRODUCTION_UI_REQUIREMENTS'),
                                                                               ('GENSHIN_CULTURE_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_CULTURE_UI_REQUIREMENTS'),
                                                                               ('GENSHIN_SCIENCE_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_SCIENCE_UI_REQUIREMENTS'),
                                                                               ('GENSHIN_FAITH_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_FAITH_UI_REQUIREMENTS'),
                                                                               ('GENSHIN_GOLD_UI_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_GOLD_UI_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES ('GENSHIN_FOOD_UI_MODIFIER','YieldType','YIELD_FOOD'),('GENSHIN_FOOD_UI_MODIFIER','Amount',1),
                                                             ('GENSHIN_PRODUCTION_UI_MODIFIER','YieldType','YIELD_PRODUCTION'),('GENSHIN_PRODUCTION_UI_MODIFIER','Amount',1),
                                                             ('GENSHIN_CULTURE_UI_MODIFIER','YieldType','YIELD_CULTURE'),('GENSHIN_CULTURE_UI_MODIFIER','Amount',1),
                                                             ('GENSHIN_SCIENCE_UI_MODIFIER','YieldType','YIELD_SCIENCE'),('GENSHIN_SCIENCE_UI_MODIFIER','Amount',1),
                                                             ('GENSHIN_FAITH_UI_MODIFIER','YieldType','YIELD_FAITH'),('GENSHIN_FAITH_UI_MODIFIER','Amount',1),
                                                             ('GENSHIN_GOLD_UI_MODIFIER','YieldType','YIELD_GOLD'),('GENSHIN_GOLD_UI_MODIFIER','Amount',2);

INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId) VALUES ('GENSHIN_FOOD_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
                                                                               ('GENSHIN_PRODUCTION_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
                                                                               ('GENSHIN_CULTURE_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
                                                                               ('GENSHIN_SCIENCE_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
                                                                               ('GENSHIN_FAITH_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
                                                                               ('GENSHIN_GOLD_UI','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES ('GENSHIN_FOOD_UI','ModifierId','GENSHIN_FOOD_UI_MODIFIER'),
                                                             ('GENSHIN_PRODUCTION_UI','ModifierId','GENSHIN_PRODUCTION_UI_MODIFIER'),
                                                             ('GENSHIN_CULTURE_UI','ModifierId','GENSHIN_CULTURE_UI_MODIFIER'),
                                                             ('GENSHIN_SCIENCE_UI','ModifierId','GENSHIN_SCIENCE_UI_MODIFIER'),
                                                             ('GENSHIN_FAITH_UI','ModifierId','GENSHIN_FAITH_UI_MODIFIER'),
                                                             ('GENSHIN_GOLD_UI','ModifierId','GENSHIN_GOLD_UI_MODIFIER');


--极光之舞：雪地加金币

INSERT OR IGNORE INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId) VALUES
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
VALUES
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT', 'DistrictType', 'DISTRICT_HOLY_SITE'),
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT', 'TerrainType', 'TERRAIN_SNOW'),
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT', 'YieldType', 'YIELD_GOLD'),
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT', 'Amount', '1'),
('DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT', 'Description', 'LOC_DISTRICT_SNOW_FAITH_TT'),

('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT', 'DistrictType', 'DISTRICT_HOLY_SITE'),
('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT', 'TerrainType', 'TERRAIN_SNOW_HILLS'),
('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT', 'YieldType', 'YIELD_GOLD'),
('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT', 'Amount', '1'),
('DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT', 'Description', 'LOC_DISTRICT_SNOW_HILLS_FAITH_TT');

INSERT OR IGNORE INTO BeliefModifiers(BeliefType,ModifierId) VALUES
('BELIEF_DANCE_OF_THE_AURORA','DANCE_OF_THE_AURORA_FAITHSNOWADJACENCY_TT'),
('BELIEF_DANCE_OF_THE_AURORA','DANCE_OF_THE_AURORA_FAITHSNOWHILLSADJACENCY_TT');

--神圣道路：不变

--沙漠民俗：不变

UPDATE Beliefs SET Description = 'LOC_BELIEF_EARTH_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_EARTH_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GODDESS_OF_FIRE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GODDESS_OF_FIRE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_RELIGIOUS_IDOLS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_RELIGIOUS_IDOLS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DIVINE_SPARK_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_DIVINE_SPARK';
UPDATE Beliefs SET Description = 'LOC_BELIEF_RIVER_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_RIVER_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_MONUMENT_TO_THE_GODS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_MONUMENT_TO_THE_GODS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_CITY_PATRON_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_CITY_PATRON_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_THE_SEA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_THE_SEA';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_THE_FORGE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_THE_FORGE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_HEALING_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_HEALING'; 
UPDATE Beliefs SET Description = 'LOC_BELIEF_INITIATION_RITES_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_INITIATION_RITES';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GENSHIN_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_STONE_CIRCLES';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GODDESS_OF_WATER_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_WAR';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DANCE_OF_THE_AURORA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_DANCE_OF_THE_AURORA';