UPDATE Beliefs SET Description = 'LOC_BELIEF_EARTH_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_EARTH_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GODDESS_OF_FIRE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GODDESS_OF_FIRE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_RELIGIOUS_IDOLS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_RELIGIOUS_IDOLS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DIVINE_SPARK_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_DIVINE_SPARK';
UPDATE Beliefs SET Description = 'LOC_BELIEF_RIVER_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_RIVER_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_MONUMENT_TO_THE_GODS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_MONUMENT_TO_THE_GODS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_CITY_PATRON_GODDESS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_CITY_PATRON_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_THE_SEA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_THE_SEA';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_THE_FORGE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GOD_OF_THE_FORGE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GOD_OF_HEALING_H_DESCRIPTION' WHERE BeliefType = 'GOD_OF_HEALING';	
UPDATE Beliefs SET Description = 'LOC_BELIEF_INITIATION_RITES_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_INITIATION_RITES';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DANCE_OF_THE_AURORA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_DANCE_OF_THE_AURORA';

UPDATE Beliefs SET Description = 'LOC_BELIEF_CHORAL_MUSIC_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_CHORAL_MUSIC';
UPDATE Beliefs SET Description = 'LOC_BELIEF_FEED_THE_WORLD_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_FEED_THE_WORLD';
UPDATE Beliefs SET Description = 'LOC_BELIEF_JESUIT_EDUCATION_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_JESUIT_EDUCATION';
UPDATE Beliefs SET Description = 'LOC_BELIEF_WARRIOR_MONKS_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_WARRIOR_MONKS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_ZEN_MEDITATION_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_ZEN_MEDITATION';

UPDATE Beliefs SET Description = 'LOC_BELIEF_CATHEDRAL_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_CATHEDRAL';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GURDWARA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_GURDWARA';
UPDATE Beliefs SET Description = 'LOC_BELIEF_MEETING_HOUSE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_MEETING_HOUSE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_MOSQUE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_MOSQUE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_PAGODA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_PAGODA';
UPDATE Beliefs SET Description = 'LOC_BELIEF_SYNAGOGUE_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_SYNAGOGUE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_WAT_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_WAT';
UPDATE Beliefs SET Description = 'LOC_BELIEF_STUPA_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_STUPA';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DAR_E_MEHR_H_DESCRIPTION' WHERE BeliefType = 'BELIEF_DAR_E_MEHR';

UPDATE Buildings SET Description = 'LOC_BUILDING_PAGODA_H_DESCRIPTION' WHERE BuildingType = 'BELIEF_PAGODA';
UPDATE Buildings SET Description = 'LOC_BUILDING_DAR_E_MEHR_H_DESCRIPTION' WHERE BuildingType = 'BELIEF_DAR_E_MEHR';
