--------------------------------------------------------------------------------------------------------------------------
-- LocalisedText
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, 								Language,	Text)
VALUES
-- English US ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"en_US",	"Enhanced Mod Manager v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"en_US",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"en_US",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"en_US",	"Sort By: Author"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"en_US", 	"Sort By: Dependency"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"en_US", 	"Sort By: Update Time"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"en_US", 	"Sort By: Compatibility"),
		("LOC_FF16_CUSTOM_FILTER",  		"en_US", 	"Custom Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"en_US", 	"Off"),
		("LOC_FF16_BY_AUTHOR",				"en_US", 	"By: "),
		("LOC_FF16_ENABLED_MODS",  			"en_US", 	"ENABLED MODS"),
		("LOC_FF16_DISABLED_MODS",  		"en_US", 	"DISABLED MODS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"en_US", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"en_US", 	"Mods"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"en_US", 	"Gameplay"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"en_US", 	"Cosmetic"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"en_US", 	"Filter official DLC by Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"en_US", 	"Filter community made mods."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"en_US", 	"Filter mods that affect save games."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "en_US", 	"Filter mods that do not affect save games."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","en_US", 	"Search for content based on title, teaser or mod author."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"en_US", 	"Enable all mods currently listed below."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"en_US", 	"Disable all mods currently listed below."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"en_US", 	"Enable all currently listed mods?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"en_US", 	"Disable all currently listed mods?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"en_US", 	"Multi Selection Mode"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"en_US", 	"More than one mod has been selected."),	
		("LOC_FF16_MULTISELECT_DESC", 		"en_US", 	"Number of mods currently selected: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"en_US", 	"Selected Mods Depend On"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"en_US", 	"Your current mod selection has missing dependencies. Add the missing mods to your selection or deselect the dependant mods."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "en_US", 	"Ignoring Compatibility Warning"),
		("LOC_FF16_OPEN_WORKSHOP",			"en_US",	"Open this mod's Steam Workshop page."),
		("LOC_FF16_OPEN_CHANGELOG",			"en_US",	"Open this mod's changelog."),
		("LOC_FF16_MODS_SUBSCRIBED",		"en_US",	"Workshop Subscribed?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"en_US",	"Last Updated: No Subscription Found"),
		("LOC_FF16_MODID",					"en_US",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"en_US",	"Locally Installed"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"en_US",	"Non-Workshop Mod"),
		("LOC_FF16_MODID_EXPORT",			"en_US",	"Export Mod ID's"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"en_US",	"Exports a list of ID's from the current mod selection to:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"en_US",	"Color Names"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"en_US",	"Enables/Disables the color tags in mod names set by the author."),
		("LOC_FF16_AUTO_LASTUSEDMODS",      "en_US",    "Auto: Last Used Mods"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "en_US", "An automatically generated mod group based on last used mods."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"en_US", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"en_US", 	"Tip: Right click a mod to instantly enable/disable it."),
		("LOC_FF16_MODSCREEN_TIP_2",		"en_US", 	"Tip: You can also sort by Author or Mod Dependency."),
		("LOC_FF16_MODSCREEN_TIP_3",		"en_US", 	"Tip: Uncheck the 'Gameplay' filter to only show mods you can apply to your existing save games!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"en_US", 	"Tip: Click on a mod to bring up its details panel. Click again to hide it."),
		("LOC_FF16_MODSCREEN_TIP_5",		"en_US", 	"Tip: Mod conflicts? Try disabling similar mods one by one to find out which one is causing the issue."),
		("LOC_FF16_MODSCREEN_TIP_6",		"en_US", 	"Tip: If Gandhi asks for any of your Uranium, say no."),
		("LOC_FF16_MODSCREEN_TIP_7",		"en_US", 	"Tip: Mods that affect save games are automatically loaded or de-loaded when you load an existing save."),
		("LOC_FF16_MODSCREEN_TIP_8",		"en_US", 	"Tip: Like a certain mod set up? Click the plus icon in the top right corner to save your current mod group."),
		("LOC_FF16_MODSCREEN_TIP_9",		"en_US", 	"Tip: Enjoying a new mod? Do the author a favour and rate it on the workshop!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"en_US", 	"Happy Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"en_US", 	"Tip: Hold Shift while selecting mods to enable or disable multiple mods at once!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"en_US", 	"Tip: You can define your own custom mod filters! Check out CustomFilters.xml for more information."),
		("LOC_FF16_MODSCREEN_TIP_13",		"en_US", 	"Tip: The most recently used mods are saved in the 'Auto: Last Mods Used' mod group automatically."),
		
-- German  ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"de_DE",	"Enhanced Mod Manager v1.9.1 von FinalFreak16 - Deutsche Übersetzung von Pudding"),
		("LOC_FF16_MOD_TITLE_1", 	 		"de_DE",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"de_DE",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"de_DE",	"Sortieren nach: Autor"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"de_DE", 	"Sortieren nach: Abhängigkeit"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"de_DE", 	"Sortieren nach: Zuletzt Aktualisiert"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"de_DE", 	"Sortieren nach: Kompatibilität"),
		("LOC_FF16_CUSTOM_FILTER",  		"de_DE", 	"Angepasster Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"de_DE", 	"Aus"),
		("LOC_FF16_BY_AUTHOR",				"de_DE", 	"Von: "),
		("LOC_FF16_ENABLED_MODS",  			"de_DE", 	"AKTIVIERTE MODS"),
		("LOC_FF16_DISABLED_MODS",  		"de_DE", 	"DEAKTIVIERTE MODS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"de_DE", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"de_DE", 	"Mods"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"de_DE", 	"Spielverlauf"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"de_DE", 	"Kosmetisch"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"de_DE", 	"Zeige Offizielle DLCs von Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"de_DE", 	"Zeige Benutzererstellte Mods anzeigen."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"de_DE", 	"Zeige Spielstand-beeinflussende Mods."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "de_DE", 	"Zeige Mods, welche Spielstände nicht beeinflussen."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","de_DE", 	"Suche nach Inhalten basierend auf Titel, Beschreibung oder Mod Author."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"de_DE", 	"Aktiviere alle aktuell aufgelisteten Mods."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"de_DE", 	"Deaktiviere alle aktuell aufgelisteten Mods."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"de_DE", 	"Alle aktuell aufgelistete Mods aktivieren?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"de_DE", 	"Alle aktuell aufgelistete Mods deaktivieren?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"de_DE", 	"Mehrfach-Auswahlmodus"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"de_DE", 	"Mehr als eine Mod wurde ausgewählt."),	
		("LOC_FF16_MULTISELECT_DESC", 		"de_DE", 	"Anzahl aktuell ausgewählter Mods: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"de_DE", 	"Ausgewählte Mod ist abhängig von"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"de_DE", 	"Fehlende Abhängigkeiten in deiner Modauswahl. Füge die Abhängigkeiten deiner Auswahl hinzu oder deaktiviere die abhängige Mod."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "de_DE", 	"Ignoriere Kompatibilitätswarnungen"),
		("LOC_FF16_OPEN_WORKSHOP",			"de_DE",	"Öffne die Steam Workshop Seite dieser Mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"de_DE",	"Öffne den Änderungshinweis dieser Mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"de_DE",	"Im Workshop abonniert?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"de_DE",	"Letztes Update: Kein Abonnement gefunden"),
		("LOC_FF16_MODID",					"de_DE",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"de_DE",	"Lokal installiert"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"de_DE",	"Manuell installierte Mod"),
		("LOC_FF16_MODID_EXPORT",			"de_DE",	"Exportiere Mod IDs"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"de_DE",	"Exportiert eine Liste von IDs der aktuellen Modauswahl nach:[NEWLINE]~\Dokumente\My Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"de_DE",	"Bunte Namen"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"de_DE",	"Aktiviert/deaktiviert die Farbmarkierungen in Mod-Namen, die vom Autor festgelegt wurden."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"de_DE", 	"Auto: Zuletzt verwendete Mods"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "de_DE", "Eine automatisch generierte Mod-Gruppe basierend auf zuletzt verwendeten Mods."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"de_DE", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"de_DE", 	"Tipp: Ein Rechtsklick auf eine Mod de-/aktiviert diese sofort."),
		("LOC_FF16_MODSCREEN_TIP_2",		"de_DE", 	"Tipp: Du kannst auch nach Author oder Abhängigkeiten sortieren."),
		("LOC_FF16_MODSCREEN_TIP_3",		"de_DE", 	"Tipp: Deaktiviere den 'Gameplay' Filter um ausschließlich Mods anzuzeigen,[NEWLINE]welche du deinen existierenden Spielständen hinzufügen kannst!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"de_DE", 	"Tipp: Klicke auf eine Mod um ein Detailfenster über diese zu öffnen. Ein erneuter Klick blendet diesen wieder aus."),
		("LOC_FF16_MODSCREEN_TIP_5",		"de_DE", 	"Tipp: In Konflikt stehende Mods? Versuche Mods mit ähnlicher Auswirkung nacheinander zu deaktivieren,[NEWLINE]um herauszufinden welche Probleme bereitet."),
		("LOC_FF16_MODSCREEN_TIP_6",		"de_DE", 	"Tipp: Sollte Gandhi nach deinem Uran fragen, lehne ab."),
		("LOC_FF16_MODSCREEN_TIP_7",		"de_DE", 	"Tipp: Mods welche deinen Spielstand beeinflussen werden automatisch ge-[NEWLINE]und entladen wenn du einen entsprechenden bereits existierenden Spielstand lädst."),
		("LOC_FF16_MODSCREEN_TIP_8",		"de_DE", 	"Tipp: Gefällt dir eine Mod? Klicke auf das Plus-Icon oben rechts um es deiner aktuellen Modgruppe hinzuzufügen.."),
		("LOC_FF16_MODSCREEN_TIP_9",		"de_DE", 	"Tipp: Macht dir eine neue Mod Spaß? Mach dem Author eine Freude und favorisiere und bewerte die Mod im Workshop!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"de_DE", 	"Fröhliches Modden!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"de_DE", 	"Tipp: Halte die Umschalttaste während du Mods auswählst, um mehrere Mods gleichzeitig zu de-/aktivieren!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"de_DE", 	"Tipp: Du kannst deine eigenen Filter definieren! Siehe CustomFilters.xml für weitere Details."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"de_DE", 	"Tipp: Die zuletzt verwendeten Mods werden automatisch in der Gruppe 'Auto: Zuletzt verwendete Mods' gespeichert."),
		
-- French  ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"fr_FR",	"Enhanced Mod Manager v1.9.1 par FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"fr_FR",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"fr_FR",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"fr_FR",	"Trier par: Auteur"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"fr_FR", 	"Trier par: Dépendance"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"fr_FR", 	"Trier par: Dernière mise à jour"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"fr_FR", 	"Trier par: Compatibilité"),
		("LOC_FF16_CUSTOM_FILTER",  		"fr_FR", 	"Angepasster Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"fr_FR", 	"Aus"),
		("LOC_FF16_BY_AUTHOR",				"fr_FR", 	"Von: "),
		("LOC_FF16_ENABLED_MODS",  			"fr_FR", 	"ACTIVÉ MODS"),
		("LOC_FF16_DISABLED_MODS",  		"fr_FR", 	"DÉSACTIVÉS MODS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"fr_FR", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"fr_FR", 	"Mods"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"fr_FR", 	"Jouabilité"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"fr_FR", 	"Cosmétique"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"fr_FR", 	"Filtrer les DLC officiels de Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"fr_FR", 	"Filtrer les mods créés par la communauté."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"fr_FR", 	"Filtrer les mods qui affectent les sauvegardes."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "fr_FR", 	"Filtrer les mods qui n'affectent pas les sauvegardes."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","fr_FR", 	"Rechercher du contenu en fonction du titre, du teaser ou de l'auteur du mod."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"fr_FR", 	"Activer tous les mods actuellement répertoriés ci-dessous."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"fr_FR", 	"Désactiver tous les mods actuellement répertoriés ci-dessous."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"fr_FR", 	"Activer tous les mods répertoriés actuellement?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"fr_FR", 	"Désactiver tous les mods répertoriés actuellement?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"fr_FR", 	"Mode de sélection multiple"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"fr_FR", 	"Plus d'un mod a été sélectionné."),	
		("LOC_FF16_MULTISELECT_DESC", 		"fr_FR", 	"Nombre de mods actuellement sélectionnés: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"fr_FR", 	"Les mods sélectionnés dépendent de"),
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"fr_FR", 	"Votre sélection de mods actuelle comporte des dépendances manquantes. Ajoutez les mods manquants à votre sélection ou désélectionnez les mods dépendants."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "fr_FR", 	"Ignorer l'avertissement de compatibilité"),
		("LOC_FF16_OPEN_WORKSHOP",			"fr_FR",	"Ouvrir la page du Workshop Steam de ce mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"fr_FR",	"Ouvrir le journal des modifications de ce mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"fr_FR",	"Inscrit sur le Workshop ?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"fr_FR",	"Dernière mise à jour : aucune inscription trouvée"),
		("LOC_FF16_MODID",					"fr_FR",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"fr_FR",	"Installation locale"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"fr_FR",	"Mod non-Workshop"),
		("LOC_FF16_MODID_EXPORT",			"fr_FR",	"Exporter les ID"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"fr_FR",	"Exporte une liste d'ID à partir de la sélection de mods actuelle vers:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"fr_FR",	"Noms en couleur"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"fr_FR",	"Active/désactive les tags de couleur dans les noms de mod définis par l'auteur."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"fr_FR", 	"Auto: Mods Utilisés Récemment"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "fr_FR", "Un groupe de mods généré automatiquement en fonction des mods utilisés récemment."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"fr_FR", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1", 		"fr_FR", 	"Astuce: Cliquez avec le bouton droit sur un mod pour l'activer/désactiver instantanément."),
		("LOC_FF16_MODSCREEN_TIP_2", 		"fr_FR", 	"Astuce: Vous pouvez également trier par auteur ou dépendance de mod."),
		("LOC_FF16_MODSCREEN_TIP_3", 		"fr_FR", 	"Astuce: Décochez 'Gameplay' pour afficher uniquement les mods applicables aux parties sauvegardées existantes!"),
		("LOC_FF16_MODSCREEN_TIP_4", 		"fr_FR",	"Astuce: Cliquez sur un mod pour afficher son panneau de détails. Cliquez à nouveau pour le masquer."),
		("LOC_FF16_MODSCREEN_TIP_5", 		"fr_FR", 	"Astuce: Des conflits de mods? Essayez de désactiver les mods similaires un par un pour découvrir lequel pose problème."),
		("LOC_FF16_MODSCREEN_TIP_6", 		"fr_FR", 	"Astuce: Si Gandhi vous demande de lui donner de l'uranium, dites non."),
		("LOC_FF16_MODSCREEN_TIP_7", 		"fr_FR", 	"Astuce: Les mods affectant les sauvegardes se chargent automatiquement."),
		("LOC_FF16_MODSCREEN_TIP_8", 		"fr_FR",	"Astuce: Enregistrez votre groupe de mods en cliquant sur l'icône plus en haut à droite."),
		("LOC_FF16_MODSCREEN_TIP_9", 		"fr_FR", 	"Astuce: Vous appréciez un nouveau mod? Faites une faveur à l'auteur et notez-le sur l'atelier!"),
		("LOC_FF16_MODSCREEN_TIP_10", 		"fr_FR", 	"Bon modding!"),
		("LOC_FF16_MODSCREEN_TIP_11", 		"fr_FR", 	"Astuce: Maintenez Shift enfoncé lors de la sélection de mods pour en activer ou désactiver plusieurs à la fois!"),
		("LOC_FF16_MODSCREEN_TIP_12", 		"fr_FR", 	"Astuce: Vous pouvez définir vos propres filtres de mod personnalisés ! Consultez CustomFilters.xml pour plus d'informations."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"fr_FR", 	"Astuce: Les mods les plus récemment utilisés sont enregistrés automatiquement dans le groupe de mods[NEWLINE]'Auto: Mods Utilisés Récemment'."),
	
-- Spanish ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"es_ES",	"Enhanced Mod Manager v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"es_ES",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"es_ES",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"es_ES",	"Ordenar por: Autor"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"es_ES", 	"Ordenar por: Dependencia"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"es_ES", 	"Ordenar por: Hora de actualización"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"es_ES", 	"Ordenar por: Compatibilidad"),
		("LOC_FF16_CUSTOM_FILTER",  		"es_ES", 	"Filtro personalizado:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"es_ES", 	"Apagado"),
		("LOC_FF16_BY_AUTHOR",				"es_ES", 	"Por: "),
		("LOC_FF16_ENABLED_MODS",  			"es_ES", 	"ACTIVADO MODS"),
		("LOC_FF16_DISABLED_MODS",  		"es_ES", 	"DESACTIVADO MODS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"es_ES", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"es_ES", 	"Mods"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"es_ES", 	"Jugabilidad"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"es_ES", 	"Cosmética"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"es_ES", 	"Filtrar DLC oficiales de Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"es_ES", 	"Filtrar mods creados por la comunidad."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"es_ES", 	"Filtrar mods que afectan partidas guardadas."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "es_ES", 	"Filtrar mods que no afectan partidas guardadas."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","es_ES", 	"Buscar contenido por título, descripción o autor del mod."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"es_ES", 	"Habilitar todos los mods listados."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"es_ES", 	"Deshabilitar todos los mods listados."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"es_ES", 	"¿Habilitar todos los mods listados?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"es_ES", 	"¿Deshabilitar todos los mods listados?"),
		("LOC_FF16_MULTISELECT_TITLE", 		"es_ES", 	"Modo de selección múltiple"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"es_ES", 	"Más de un mod ha sido seleccionado."),	
		("LOC_FF16_MULTISELECT_DESC", 		"es_ES", 	"Número de mods actualmente seleccionados: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"es_ES", 	"Mods seleccionados dependen de"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"es_ES", 	"Su selección actual de mods tiene dependencias faltantes. Agregue los mods faltantes a su selección o deseleccione los mods dependientes."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "es_ES", 	"Ignorando Advertencia de Compatibilidad"),
		("LOC_FF16_OPEN_WORKSHOP",			"es_ES",	"Abrir la página del taller de Steam de este mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"es_ES",	"Abrir el registro de cambios de este mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"es_ES",	"¿Suscripción en el taller?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"es_ES",	"Última actualización: No se encontró suscripción"),
		("LOC_FF16_MODID",					"es_ES",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"es_ES",	"Instalado localmente"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"es_ES",	"Mod no suscrito"),
		("LOC_FF16_MODID_EXPORT",			"es_ES",	"Exportar ID"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"es_ES",	"Exporta una lista de ID de la selección actual de mods a:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"es_ES",	"Colorear nombres"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"es_ES",	"Habilita/Deshabilita las etiquetas de color en los nombres de los mods establecidas por el autor."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"es_ES", 	"Auto: Últimos Mods Usados"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "es_ES", "Un grupo de mods generado automáticamente en función de los mods utilizados recientemente."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",      "es_ES",    "13"),
		("LOC_FF16_MODSCREEN_TIP_1",        "es_ES",    "Consejo: Haz clic derecho en un mod para activarlo/desactivarlo instantáneamente."),
		("LOC_FF16_MODSCREEN_TIP_2",        "es_ES",    "Consejo: También puedes ordenar por autor o dependencia de mod."),
		("LOC_FF16_MODSCREEN_TIP_3",        "es_ES",    "Consejo: Desmarca el filtro 'Jugabilidad' para mostrar solo los mods que puedes aplicar a tus partidas guardadas existentes."),
		("LOC_FF16_MODSCREEN_TIP_4",        "es_ES",    "Consejo: Haz clic en un mod para abrir su panel de detalles. Haz clic de nuevo para ocultarlo."),
		("LOC_FF16_MODSCREEN_TIP_5",        "es_ES",    "Consejo: ¿Conflictos de mods? Prueba a desactivar mods similares uno por uno para descubrir cuál está causando el problema."),
		("LOC_FF16_MODSCREEN_TIP_6",        "es_ES",    "Consejo: Si Gandhi te pide uranio, di que no."),
		("LOC_FF16_MODSCREEN_TIP_7",        "es_ES",    "Consejo: Los mods que afectan a las partidas guardadas se cargan o descargan automáticamente[NEWLINE]al cargar una partida guardada existente."),
		("LOC_FF16_MODSCREEN_TIP_8",        "es_ES",    "Consejo: ¿Te gusta una configuración de mod en particular?[NEWLINE]Haz clic en el icono de más en la esquina superior derecha para guardar tu grupo de mods actual."),
		("LOC_FF16_MODSCREEN_TIP_9",        "es_ES",    "Consejo: ¿Disfrutas de un nuevo mod? ¡Haz un favor al autor y califícalo en el taller!"),
		("LOC_FF16_MODSCREEN_TIP_10",       "es_ES",    "¡Feliz modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",       "es_ES",    "Consejo: Mantén presionada la tecla Mayús mientras seleccionas mods para activar o desactivar varios mods a la vez."),
		("LOC_FF16_MODSCREEN_TIP_12",       "es_ES",    "Consejo: ¡Puedes definir tus propios filtros de mod personalizados! Consulta CustomFilters.xml para obtener más información."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"es_ES", 	"Consejo: Los mods utilizados más recientemente se guardan automáticamente en el grupo de mods 'Auto: Últimos Mods Usados'."),
	
-- Polish ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"pl_PL",	"Enhanced Mod Manager v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"pl_PL",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"pl_PL",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"pl_PL",	"Sortuj według: Autor"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"pl_PL", 	"Sortuj według: Zależność"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"pl_PL", 	"Sortuj według: Czas aktualizacji"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"pl_PL", 	"Sortuj według: Kompatybilność"),
		("LOC_FF16_CUSTOM_FILTER",  		"pl_PL", 	"Filtr niestandardowy:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"pl_PL", 	"Poza"),
		("LOC_FF16_BY_AUTHOR",				"pl_PL", 	"Przez: "),
		("LOC_FF16_ENABLED_MODS",  			"pl_PL", 	"WŁĄCZONE MOD"),
		("LOC_FF16_DISABLED_MODS",  		"pl_PL", 	"WYŁĄCZONE MOD"),
		("LOC_FF16_OFFICIAL_FILTER",  		"pl_PL", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"pl_PL", 	"Mod"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"pl_PL", 	"Rozgrywka"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"pl_PL", 	"Kosmetyczne"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"pl_PL", 	"Filtruj oficjalne DLC firmy Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"pl_PL", 	"Filtruj mod stworzone przez społeczność."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"pl_PL", 	"Filtruj mod wpływające na zapisane gry."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "pl_PL", 	"Filtruj mod, które nie wpływają na zapisane gry."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","pl_PL", 	"Wyszukaj treść na podstawie tytułu, wstępu lub autora mod."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"pl_PL", 	"Włącz wszystkie obecnie wymienione mod."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"pl_PL", 	"Wyłącz wszystkie obecnie wymienione mod."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"pl_PL", 	"Włączyć wszystkie obecnie wymienione mod?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"pl_PL", 	"Zamknąć wszystkie obecnie wymienione mod?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"pl_PL", 	"Tryb wielokrotnego wyboru"),
		("LOC_FF16_MULTISELECT_TEASER", 	"pl_PL", 	"Zostało wybranych więcej niż jeden mod."),	
		("LOC_FF16_MULTISELECT_DESC", 		"pl_PL", 	"Liczba aktualnie wybranych mod: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"pl_PL", 	"Wymagane są wybrane mod"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"pl_PL", 	"Wybrane mod wymagają innych modów. Dodaj brakujące mod do swojego wyboru lub odznacz wymagające mod."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "pl_PL", 	"Ignorowanie ostrzeżenia o zgodności"),
		("LOC_FF16_OPEN_WORKSHOP",			"pl_PL",	"Otwórz stronę warsztatu Steam dla tego mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"pl_PL",	"Otwórz dziennik zmian tego mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"pl_PL",	"Subskrybowano w warsztacie?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"pl_PL",	"Ostatnio aktualizowane: nie znaleziono subskrypcji"),
		("LOC_FF16_MODID",					"pl_PL",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"pl_PL",	"Zainstalowany lokalnie"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"pl_PL",	"Mod spoza warsztatu"),
		("LOC_FF16_MODID_EXPORT",			"pl_PL",	"Eksportuj ID modów"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"pl_PL",	"Eksportuje listę ID modów z aktualnego wyboru do:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"pl_PL",	"Kolorowe nazwy"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"pl_PL",	"Włącza/Wyłącza tagi kolorów w nazwach modów dodane przez autora."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"pl_PL", 	"Auto: Ostatnio Używane Mody"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "pl_PL", "Automatycznie wygenerowana grupa modyfikacji na podstawie ostatnio używanych modów."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"pl_PL", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"pl_PL", 	"Porada: Kliknij prawym przyciskiem myszy na modyfikację, aby ją natychmiast włączyć/wyłączyć."),
		("LOC_FF16_MODSCREEN_TIP_2",		"pl_PL", 	"Porada: Możesz również sortować według autora lub zależności modów."),
		("LOC_FF16_MODSCREEN_TIP_3",		"pl_PL", 	"Porada: Odznacz filtr 'Rozgrywka', aby wyświetlać tylko mod, które można zastosować do istniejących zapisów gier!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"pl_PL", 	"Porada: Kliknij na modyfikację, aby otworzyć jej panel szczegółów. Kliknij ponownie, aby go ukryć."),
		("LOC_FF16_MODSCREEN_TIP_5",		"pl_PL", 	"Porada: Konflikty modów? Spróbuj wyłączyć podobne mod jeden po drugim, aby dowiedzieć się, który powoduje problem."),
		("LOC_FF16_MODSCREEN_TIP_6",		"pl_PL", 	"Porada: Jeśli Gandhi prosi cię o twoje Uran, powiedz nie."),
		("LOC_FF16_MODSCREEN_TIP_7",		"pl_PL", 	"Porada: Mody, które wpływają na zapisy gier, są automatycznie ładowane lub wyłączane podczas ładowania istniejącego zapisu."),
		("LOC_FF16_MODSCREEN_TIP_8",		"pl_PL", 	"Porada: Lubisz określony zestaw modów? Kliknij ikonę plusa w prawym górnym rogu, aby zapisać swój obecny zestaw modów."),
		("LOC_FF16_MODSCREEN_TIP_9",		"pl_PL", 	"Porada: Podoba ci się nowa modyfikacja? Zrób autorowi przysługę i oceniaj ją na warsztacie!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"pl_PL", 	"Udanych modyfikacji!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"pl_PL", 	"Porada: Przytrzymaj klawisz Shift podczas wybierania modów, aby włączyć lub wyłączyć wiele modów naraz!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"pl_PL", 	"Porada: Możesz definiować własne niestandardowe filtry modów! Sprawdź plik CustomFilters.xml, aby uzyskać więcej informacji."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"pl_PL", 	"Porada: Ostatnio używane mody są automatycznie zapisywane w grupie modów „Auto: Ostatnio używane mody”."),
 
-- Chinese (Simplified) --------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"zh_Hans_CN",	"加强版MOD管理器 v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"zh_Hans_CN",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"zh_Hans_CN",	"管理器"),
		("LOC_FF16_SORTBY_AUTHOR",  		"zh_Hans_CN",	"按作者分类"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"zh_Hans_CN", 	"按关联分类"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"zh_Hans_CN", 	"Sort By: Update Time"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"zh_Hans_CN", 	"Sort By: Compatibility"),
		("LOC_FF16_CUSTOM_FILTER",  		"zh_Hans_CN", 	"Custom Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"zh_Hans_CN", 	"Off"),
		("LOC_FF16_BY_AUTHOR",				"zh_Hans_CN", 	"作者："),
		("LOC_FF16_ENABLED_MODS",  			"zh_Hans_CN", 	"已启用的MOD"),
		("LOC_FF16_DISABLED_MODS",  		"zh_Hans_CN", 	"已禁用的MOD"),
		("LOC_FF16_OFFICIAL_FILTER",  		"zh_Hans_CN", 	"官方包"),
		("LOC_FF16_COMMUNITY_FILTER",  		"zh_Hans_CN", 	"社区包"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"zh_Hans_CN", 	"影响存档"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"zh_Hans_CN", 	"不影响存档"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"zh_Hans_CN", 	"显示官方制作的DLC。"),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"zh_Hans_CN", 	"显示社区制作的MOD。"),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"zh_Hans_CN", 	"显示影响游戏存档的MOD。"),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "zh_Hans_CN", 	"显示不影响游戏存档的MOD。"),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","zh_Hans_CN", 	"依照标题、描述或者作者来搜索MOD。"),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"zh_Hans_CN", 	"启用列表中的所有MOD。"),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"zh_Hans_CN", 	"禁用列表中的所有MOD。"),
		("LOC_FF16_ENABLEALL_QUESTION", 	"zh_Hans_CN", 	"启用列表中的所有MOD？"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"zh_Hans_CN", 	"禁用列表中的所有MOD？"),
		("LOC_FF16_MULTISELECT_TITLE", 		"zh_Hans_CN", 	"多选模式"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"zh_Hans_CN", 	"已经选择了一个以上的MOD。"),	
		("LOC_FF16_MULTISELECT_DESC", 		"zh_Hans_CN", 	"目前已选中的MOD数量："),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"zh_Hans_CN", 	"选中的MOD依赖于："),	
		("LOC_FF16_MULTISELECT_TOOLTIP",	"zh_Hans_CN", 	"您当前选择的MOD缺少依赖项。将缺少的MOD添加到您的选择中，或者取消选择需要依赖的MOD。"),
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "zh_Hans_CN", 	"忽略兼容性警告"),
		("LOC_FF16_OPEN_WORKSHOP",			"zh_Hans_CN",	"打开这个MOD的Steam Workshop页面。"),
		("LOC_FF16_OPEN_CHANGELOG",			"zh_Hans_CN",	"打开这个MOD的变更日志。"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"zh_Hans_CN",	"最后更新: 没有找到订阅"),
		("LOC_FF16_MODID",					"zh_Hans_CN",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"zh_Hans_CN",	"本地安装"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"zh_Hans_CN",	"不是Steam Workshop的MOD"),
		("LOC_FF16_MODID_EXPORT",			"zh_Hans_CN",	"导出MOD ID"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"zh_Hans_CN",	"当前MODS中的ID列表将被导出至:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"zh_Hans_CN",	"多彩的名字"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"zh_Hans_CN",	"启用/禁用作者设置的MOD名称中的颜色标签"),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"zh_Hans_CN", 	"自动：上次使用的MOD组"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "zh_Hans_CN", "基于最近使用的MOD自动生成的MOD组。"),
		
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"zh_Hans_CN", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"zh_Hans_CN", 	"小贴士：右键一个MOD可以直接启用或者禁用它。"),
		("LOC_FF16_MODSCREEN_TIP_2",		"zh_Hans_CN", 	"小贴士：你可以按照作者或根据关联的顺序来排列。"),
		("LOC_FF16_MODSCREEN_TIP_3",		"zh_Hans_CN", 	"小贴士：不勾选“影响存档”选项，列表中就会只显示你可以用于你现有的存档的MOD！"),
		("LOC_FF16_MODSCREEN_TIP_4",		"zh_Hans_CN", 	"小贴士：点击一个MOD可以打开它的详情面板，再次点击则可以隐藏面板。"),
		("LOC_FF16_MODSCREEN_TIP_5",		"zh_Hans_CN", 	"小贴士：MOD冲突？尝试逐个禁用类似的MOD，以查明是哪个MOD导致的冲突。"),
		("LOC_FF16_MODSCREEN_TIP_6",		"zh_Hans_CN", 	"小贴士：如果甘地向你要铀，千万别给！"),
		("LOC_FF16_MODSCREEN_TIP_7",		"zh_Hans_CN", 	"小贴士：当你读取存档的时候，影响游戏存档的MOD会根据之前的使用情况自动加载或卸载。"),
		("LOC_FF16_MODSCREEN_TIP_8",		"zh_Hans_CN", 	"小贴士：喜欢当前的MOD组合吗？单击右上角的加号图标可以将当前的MOD存为一个组。"),
		("LOC_FF16_MODSCREEN_TIP_9",		"zh_Hans_CN", 	"小贴士：喜欢一个MOD？别吝啬，去创意工坊给作者点个赞吧！"),
		("LOC_FF16_MODSCREEN_TIP_10",		"zh_Hans_CN", 	"愉快的Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"zh_Hans_CN", 	"小贴士：在选择MOD的时候，按住Shift可以同时选中多个哦。"),
		("LOC_FF16_MODSCREEN_TIP_12",		"zh_Hans_CN", 	"小贴士：你可以定义自己的自定义MOD过滤器! 阅读CustomFilters.xml了解更多信息。"),
		("LOC_FF16_MODSCREEN_TIP_13", 		"zh_Hans_CN", 	"小贴士：最近使用的MOD会自动保存在“自动：上次使用的MOD”组中。"),
 
-- Italian IT ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"it_IT",	"Enhanced Mod Manager v1.9.1 di FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"it_IT",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"it_IT",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"it_IT",	"Ordina per: Autore"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"it_IT", 	"Ordina per: Dipendenza"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"it_IT", 	"Ordina per: Ultimo aggiornamento"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"it_IT", 	"Ordina per: Compatibilità"),
		("LOC_FF16_CUSTOM_FILTER",  		"it_IT", 	"Filtro Personalizzato:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"it_IT", 	"Spento"),
		("LOC_FF16_BY_AUTHOR",				"it_IT", 	"Di: "),
		("LOC_FF16_ENABLED_MODS",  			"it_IT", 	"MOD ATTIVE"),
		("LOC_FF16_DISABLED_MODS",  		"it_IT", 	"MOD DISATTIVE"),
		("LOC_FF16_OFFICIAL_FILTER",  		"it_IT", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"it_IT", 	"Mod"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"it_IT", 	"Gameplay"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"it_IT", 	"Cosmetiche"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"it_IT", 	"Filtra per DLC ufficiali di Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"it_IT", 	"Filtra per mod della community."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"it_IT", 	"Filtra per mod che influenzano i savlataggi."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "it_IT", 	"Filtra per mod che non influenzano i salvataggi."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","it_IT", 	"Cerca per contenuto in base a titolo, teaser o autore."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"it_IT", 	"Abilita tutte le mod elencate qui sotto."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"it_IT", 	"Disabilita tutte le mod elencate qui sotto."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"it_IT", 	"Abilitare tutte le mod elencate?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"it_IT", 	"Disabilitare tutte le mod elencate?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"it_IT", 	"Modalità Multiselezione"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"it_IT", 	"È stata selezionata più di una mod."),	
		("LOC_FF16_MULTISELECT_DESC", 		"it_IT", 	"Numero di mod selezionate: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"it_IT", 	"Le mod selezionate dipendono da"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"it_IT", 	"Alcune mod che hai selezionato dipendono da altre NON selezionate. Aggiungi le mod mancanti o deseleziona quelle con dipendenze da altre mod."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "it_IT", 	"Ignorando avviso di compatibilià"),
		("LOC_FF16_OPEN_WORKSHOP",			"it_IT",	"Apri la pagina del Workshop Steam di questa mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"it_IT",	"Apri il changelog di questa mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"it_IT",	"Sottoscritta dal Workshop?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"it_IT",	"Ultimo aggiornamento: Nessuna sottoscrizione trovata"),
		("LOC_FF16_MODID",					"it_IT",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"it_IT",	"Installata localmente"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"it_IT",	"Mod esterna al Workshop"),
		("LOC_FF16_MODID_EXPORT",			"it_IT",	"Esportazione Mod ID"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"it_IT",	"Esporta una lista di ID dalla selezione del mod corrente a:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"it_IT",	"Nomi colorati"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"it_IT",	"Abilita/disabilita i tag di colore nei nomi dei mod impostati dall'autore."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"it_IT", 	"Auto: Ultimi Mods Utilizzati"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "it_IT", "Un gruppo di mod generato automaticamente in base agli ultimi mod utilizzati."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"it_IT", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"it_IT", 	"Suggerimento: Fai tasto destro su una mod per attivarla/disattivarla rapidamente."),
		("LOC_FF16_MODSCREEN_TIP_2",		"it_IT", 	"Suggerimento: Puoi anche ordinare le mod per autore o dipendenza da altre mod."),
		("LOC_FF16_MODSCREEN_TIP_3",		"it_IT", 	"Suggerimento: Deseleziona il filtro 'Gameplay' per mostrare le mod che puoi applicare ai tuoi salvataggi esistenti!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"it_IT", 	"Suggerimento: Clicca su una mod per aprire il pannello dettagli. Clicca ancora per nasconderlo."),
		("LOC_FF16_MODSCREEN_TIP_5",		"it_IT", 	"Suggerimento: Conflitti tra mod? Prova a disattivare mod simili una per una per trovare quale causa il problema."),
		("LOC_FF16_MODSCREEN_TIP_6",		"it_IT", 	"Suggerimento: Se Gandhi chiede anche solo un po' del tuo Uranio, digli di NO."),
		("LOC_FF16_MODSCREEN_TIP_7",		"it_IT", 	"Suggerimento: Le mod che influenzano i salvataggi sono automaticamente caricate o scaricate quando ne carichi uno esistente."),
		("LOC_FF16_MODSCREEN_TIP_8",		"it_IT", 	"Suggerimento: Ti piace un certo setup di mod? Clicca il pulsante + in alto a destra per salvare il tuo gruppo di mod attive."),
		("LOC_FF16_MODSCREEN_TIP_9",		"it_IT", 	"Suggerimento: Ti piace una nuova mod? Fai un favore all'autore e dai una valutazione sul Workshop!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"it_IT", 	"Buon Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"it_IT", 	"Suggerimento: Mantieni Shift e seleleziona più mod per attivare o disattivarle tutte insieme!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"it_IT", 	"Suggerimento: Puoi definire i tuoi filtri personalizzati! Controla il file CustomFilters.xml per più informazioni."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"it_IT", 	"Suggerimento: I mod utilizzati di recente vengono salvati automaticamente nel gruppo di mod 'Auto: Ultimi Mods Utilizzati'."),

-- Portuguese BR ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"pt_BR",	"Enhanced Mod Manager v1.9.1 por FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"pt_BR",	"GERECIADOR"),
		("LOC_FF16_MOD_TITLE_2",  			"pt_BR",	"DE MODS"),
		("LOC_FF16_SORTBY_AUTHOR",  		"pt_BR",	"Ordenar por: Autor"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"pt_BR", 	"Ordenar por: Dependência"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"pt_BR", 	"Ordenar por: Ultima atualização"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"pt_BR", 	"Ordenar por: Compatibilidade"),
		("LOC_FF16_CUSTOM_FILTER",  		"pt_BR", 	"Filtro Personalizado:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"pt_BR", 	"Desligado"),
		("LOC_FF16_BY_AUTHOR",				"pt_BR", 	"Por: "),
		("LOC_FF16_ENABLED_MODS",  			"pt_BR", 	"MODS ATIVADOS"),
		("LOC_FF16_DISABLED_MODS",  		"pt_BR", 	"MODS DESATIVADOS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"pt_BR", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"pt_BR", 	"Mod"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"pt_BR", 	"Gameplay"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"pt_BR", 	"Cosmético"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"pt_BR", 	"Filtra por DLC oficial de Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"pt_BR", 	"Filtra por Mods da comunidade."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"pt_BR", 	"Filtra por Mods que influenciam jogos salvos."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "pt_BR", 	"Filtra por Mods que não influenciam jogos salvos."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","pt_BR", 	"Busca por conteúdo no título, teaser ou autor."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"pt_BR", 	"Ativa todos os Mods listados abaixo."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"pt_BR", 	"Desativa todos os Mods listados abaixo."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"pt_BR", 	"Ativar todos os Mods listados?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"pt_BR", 	"Desativar todos os Mods listados?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"pt_BR", 	"Modo Multi-Seleção"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"pt_BR", 	"Mais de um Mod foi selecionado."),	
		("LOC_FF16_MULTISELECT_DESC", 		"pt_BR", 	"Número de Mods selecionados: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"pt_BR", 	"Mods Selecionados Dependem De"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"pt_BR", 	"Alguns Mods selecionados tem dependências faltando. Adicione os Mods faltando ou desmarque os Mods dependentes."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "pt_BR", 	"Ignorar Avisos de Compatibilidade"),
		("LOC_FF16_OPEN_WORKSHOP",			"pt_BR",	"Abrir a página Workshop Steam do Mod."),
		("LOC_FF16_OPEN_CHANGELOG",			"pt_BR",	"Abrir as mudanças recentes do Mod."),
		("LOC_FF16_MODS_SUBSCRIBED",		"pt_BR",	"Workshop Escrita?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"pt_BR",	"Ultima Atualização: Nenhum Escrito encontrado"),
		("LOC_FF16_MODID",					"pt_BR",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"pt_BR",	"Instalado localmente"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"pt_BR",	"Mod Não-Workshop"),
		("LOC_FF16_MODID_EXPORT",			"pt_BR",	"Exportar IDs"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"pt_BR",	"Exporta uma lista de IDs dos Mods selecionados para:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"pt_BR",	"Nomes coloridos"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"pt_BR",	"Activa/Desactiva as etiquetas de cor nos nomes dos mods definidos pelo autor."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"pt_BR", 	"Auto: Últimos Mods Usados"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "pt_BR", "Um grupo de mods gerado automaticamente com base nos mods usados recentemente."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"pt_BR", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"pt_BR", 	"Dica: Clique com o botão direito em um Mods para ativar/desativar ele imediatamente."),
		("LOC_FF16_MODSCREEN_TIP_2",		"pt_BR", 	"Dica: Você também pode filtrar por Autor e Dependência de Mods."),
		("LOC_FF16_MODSCREEN_TIP_3",		"pt_BR", 	"Dica: Desmarque o filtro 'Gameplay' para mostrar os Mods que você pode aplicar nos seus saves atuais!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"pt_BR", 	"Dica: Clique em um Mod para abrir seu painel de detalhes. Clique de novo para escondê-lo."),
		("LOC_FF16_MODSCREEN_TIP_5",		"pt_BR", 	"Dica: Tem conflito de Mods? Tente desativar Mods similares um por um para checar qual estar causando problemas."),
		("LOC_FF16_MODSCREEN_TIP_6",		"pt_BR", 	"Dica: Se Gandhi pedir por qualquer Urânio, diga não."),
		("LOC_FF16_MODSCREEN_TIP_7",		"pt_BR", 	"Dica: Mods que afetam partidas salvas são automaticamente ativados ou desativados ao carregar um jogo."),
		("LOC_FF16_MODSCREEN_TIP_8",		"pt_BR", 	"Dica: Gosta de uma certa configuração? Clique no símbolo de + para salvar seu grupo de Mods atuais."),
		("LOC_FF16_MODSCREEN_TIP_9",		"pt_BR", 	"Dica: Gostou de um Mod? Faça um autor um favor e der um Gostei e Favorito!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"pt_BR", 	"Tenha um bom tempo Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"pt_BR", 	"Dica: Mantenha o Shift pressionado para ativar e desativar múltiplos Mods ao mesmo tempo!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"pt_BR", 	"Dica: Você pode definir os próprios filtros de Mods! Cheque o arquivo CustomFilters.xml para mais informações."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"pt_BR", 	"Dica: Os mods mais usados recentemente são salvos automaticamente no grupo de mods 'Auto: Últimos Mods Usados'."),

-- Japanese JP ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"ja_JP",	"Enhanced Mod Manager v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"ja_JP",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"ja_JP",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"ja_JP",	"並べ替え: 作者"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"ja_JP", 	"並べ替え: 依存"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"ja_JP", 	"並べ替え: 更新"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"ja_JP", 	"並べ替え: 互換"),
		("LOC_FF16_CUSTOM_FILTER",  		"ja_JP", 	"カスタムフィルター:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"ja_JP", 	"なし"),
		("LOC_FF16_BY_AUTHOR",				"ja_JP", 	"作者: "),
		("LOC_FF16_ENABLED_MODS",  			"ja_JP", 	"有効"),
		("LOC_FF16_DISABLED_MODS",  		"ja_JP", 	"無効"),
		("LOC_FF16_OFFICIAL_FILTER",  		"ja_JP", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"ja_JP", 	"MOD"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"ja_JP", 	"ゲームプレイ"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"ja_JP", 	"装飾"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"ja_JP", 	"Firaxisの公式DLCでフィルターをかける"),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"ja_JP", 	"コミュニティ製のMODでフィルターをかける"),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"ja_JP", 	"セーブデータに影響を与えるMODでフィルターをかける"),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "ja_JP", 	"セーブデータに影響を与えないMODでフィルターをかける"),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","ja_JP", 	"タイトル、概要、MOD製作者からコンテンツを探す"),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"ja_JP", 	"以下のMODをすべて有効にする"),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"ja_JP", 	"以下のMODをすべて無効にする"),
		("LOC_FF16_ENABLEALL_QUESTION", 	"ja_JP", 	"以下のMODをすべて有効にしますか？"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"ja_JP", 	"以下のMODをすべて無効にしますか？"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"ja_JP", 	"複数選択モード"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"ja_JP", 	"複数のMODを選択中"),	
		("LOC_FF16_MULTISELECT_DESC", 		"ja_JP", 	"現在選択しているMODの数: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"ja_JP", 	"必要な前提MOD"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"ja_JP", 	"必要な前提MODを有効にしなければならない"),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "ja_JP", 	"互換性の警告を無視"),
		("LOC_FF16_OPEN_WORKSHOP",			"ja_JP",	"ワークショップのページを開く"),
		("LOC_FF16_OPEN_CHANGELOG",			"ja_JP",	"変更履歴のページを開く"),
		("LOC_FF16_MODS_SUBSCRIBED",		"ja_JP",	"ワークショップから追加？"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"ja_JP",	"更新日: 情報なし"),
		("LOC_FF16_MODID",					"ja_JP",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"ja_JP",	"局所的にインストールした"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"ja_JP",	"ワークショップのMODじゃない"),
		("LOC_FF16_MODID_EXPORT",			"ja_JP",	"MODのIDを輸出選択"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"ja_JP",	"選択したMODのIDをこの場所にエクスポートします:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"ja_JP",	"カラーネーム"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"ja_JP",	"作者が設定したMOD名のカラータグの有効・無効を設定します"),	
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"ja_JP", 	"自動: 最近使用したMOD"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "ja_JP", "最近使用したModに基づいて自動生成されたModグループ。"),	
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"ja_JP", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"ja_JP", 	"ヒント: MODを右クリックすると、有効・無効を切り替えられます。"),
		("LOC_FF16_MODSCREEN_TIP_2",		"ja_JP", 	"ヒント: MODの作者や依存関係で並べ替えることも可能です。"),
		("LOC_FF16_MODSCREEN_TIP_3",		"ja_JP", 	"ヒント: 「ゲームプレイ」のフィルターを外すと、既存のセーブデータに適用可能なMODだけが表示されます。"),
		("LOC_FF16_MODSCREEN_TIP_4",		"ja_JP", 	"ヒント: MODをクリックすると、詳細パネルが開きます。もう一度クリックすると、詳細パネルが閉じます。"),
		("LOC_FF16_MODSCREEN_TIP_5",		"ja_JP", 	"ヒント: MODが競合したら、類似のMODを一つずつ無効化して原因を突き止めましょう。"),
		("LOC_FF16_MODSCREEN_TIP_6",		"ja_JP", 	"ヒント: ガンジーからウランを求められたら断りましょう。"),
		("LOC_FF16_MODSCREEN_TIP_7",		"ja_JP", 	"ヒント: セーブデータに影響を与えるMODは、既存のセーブデータをロードすると自動的に読み込まれます。"),
		("LOC_FF16_MODSCREEN_TIP_8",		"ja_JP", 	"ヒント: 特定の組み合わせが気に入ったら、画面右上の+アイコンをクリックして現在のグループを保存しましょう。"),
		("LOC_FF16_MODSCREEN_TIP_9",		"ja_JP", 	"ヒント: 気に入ったMODはワークショップで高評価を付けましょう！"),
		("LOC_FF16_MODSCREEN_TIP_10",		"ja_JP", 	"Happy Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"ja_JP", 	"ヒント: Shiftキーを押したままクリックすると、複数MODの有効・無効を一緒に切り替えられます。"),
		("LOC_FF16_MODSCREEN_TIP_12",		"ja_JP", 	"ヒント: MODのフィルターは自分でカスタムできます。詳細は CustomFilters.xml をチェックしてください。"),
		("LOC_FF16_MODSCREEN_TIP_13", 		"ja_JP", 	"ヒント: 最近使用したMODは、自動的に「自動: 最近使用したMOD」MODグループに保存されます。"),

-- Korean KR ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE", 				"ko_KR", 	"Enhanced Mod Manager v1.9.1 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 			"ko_KR", 	"콘텐츠"),
		("LOC_FF16_MOD_TITLE_2", 			"ko_KR", 	"관리자"),
		("LOC_FF16_SORTBY_AUTHOR", 			"ko_KR", 	"정렬 기준: 제작자"),
		("LOC_FF16_SORTBY_DEPENDENCY", 		"ko_KR", 	"정렬 기준: 독립성"),
		("LOC_FF16_SORTBY_LASTUPDATED", 	"ko_KR", 	"정렬 기준: 업데이트 시간"),
		("LOC_FF16_SORTBY_COMPATIBILITY", 	"ko_KR", 	"정렬 기준: 호환성"),
		("LOC_FF16_CUSTOM_FILTER", 			"ko_KR", 	"커스텀 필터:"),
		("LOC_FF16_CUSTOM_FILTER_OFF", 		"ko_KR", 	"끄기"),
		("LOC_FF16_BY_AUTHOR", 				"ko_KR", 	"제작자: "),
		("LOC_FF16_ENABLED_MODS", 			"ko_KR", 	"활성화 된 콘텐츠"),
		("LOC_FF16_DISABLED_MODS", 			"ko_KR",	"비활성화 콘텐츠"),
		("LOC_FF16_OFFICIAL_FILTER", 		"ko_KR", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER", 		"ko_KR", 	"콘텐츠"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"ko_KR", 	"변경 불가능"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"ko_KR", 	"변경 가능"),
		("LOC_FF16_OFFICIAL_TOOLTIP", 		"ko_KR", 	"Firaxis의 공식 DLC"),
		("LOC_FF16_COMMUNITY_TOOLTIP", 		"ko_KR", 	"커뮤니티 콘텐츠"),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"ko_KR", 	"저장된 게임에 영향을 미칩니다."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "ko_KR", 	"저장된 게임에 영향을 주지 않습니다."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","ko_KR", 	"제목이나 제작자로 검색할 수 있습니다."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"ko_KR", 	"아래의 모든 콘텐츠를 활성화 합니다."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"ko_KR", 	"아래의 모든 콘텐츠를 비활성화 합니다."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"ko_KR", 	"모든 콘텐츠를 활성화 하시겠습니까?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"ko_KR", 	"모든 콘텐츠를 비활성화 하시겠습니까?"),
		("LOC_FF16_MULTISELECT_TITLE", 		"ko_KR", 	"다중 선택"),
		("LOC_FF16_MULTISELECT_TEASER", 	"ko_KR", 	"여러 콘텐츠가 선택되었습니다."),
		("LOC_FF16_MULTISELECT_DESC", 		"ko_KR", 	"현재 선택된 콘텐츠 수: "),
		("LOC_FF16_MULTISELECT_DEPEND", 	"ko_KR", 	"선택한 모드는 이 모드가 필요합니다."),
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"ko_KR", 	"지금 선택한 모드 중에 연관된 다른 모드가 필요한 모드가 있습니다. 해당 모드도 선택에 추가하거나 그 모드를 제외하십시오."),
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "ko_KR", 	"호환성 경고 무시"),
		("LOC_FF16_OPEN_WORKSHOP", 			"ko_KR", 	"이 모드의 스팀 창작마당 페이지에 접속합니다."),
		("LOC_FF16_OPEN_CHANGELOG", 		"ko_KR", 	"이 모드의 카탈로그에 접속합니다."),
		("LOC_FF16_MODS_SUBSCRIBED", 		"ko_KR", 	"창작마당 구독:"),
		("LOC_FF16_LAST_UPDATED_OFFLINE", 	"ko_KR", 	"최근 업데이트: 발견된 구독 항목이 없음"),
		("LOC_FF16_LOCALINSTALL",			"ko_KR",	"로컬 설치됨"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"ko_KR",	"비 워크숍 콘텐츠"),
		("LOC_FF16_MODID_EXPORT",			"ko_KR",	"콘텐츠 ID 내보내기"),
		("LOC_FF16_MODID_EXPORT_TOOLTIP",	"ko_KR",	"현재 콘텐츠 선택 항목에서 ID 목록을 내보냅니다:[NEWLINE]~\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Logs\Lua.log"),
		("LOC_FF16_TOGGLE_COLOR",			"ko_KR",	"색상 이름"),
		("LOC_FF16_TOGGLE_COLOR_TOOLTIP",	"ko_KR",	"작성자가 설정한 콘텐츠 이름에 색상 태그를 활성화/비활성화합니다."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"ko_KR", 	"자동: 최근 사용한 모드"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "ko_KR", "최근 사용한 모드를 기반으로 자동으로 생성된 모드 그룹입니다."),
		("LOC_FF16_AUTO_LASTUSEDMODS", 		"ko_KR", 	"자동: 최근 사용한 콘텐츠"),
		("LOC_FF16_AUTO_LASTUSEDMODS_TOOLTIP", "ko_KR", "최근 사용한 콘텐츠를 기반으로 자동으로 생성된 콘텐츠 그룹입니다."),
		--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"ko_KR", 	"13"),
		("LOC_FF16_MODSCREEN_TIP_1",		"ko_KR", 	"팁: 콘텐츠를 오른쪽 클릭하여 즉시 활성화/비활성화할 수 있습니다."),
		("LOC_FF16_MODSCREEN_TIP_2",		"ko_KR", 	"팁: 작성자 또는 콘텐츠 종속성으로 정렬할 수도 있습니다."),
		("LOC_FF16_MODSCREEN_TIP_3",		"ko_KR", 	"팁: '게임 플레이' 필터를 해제하여 기존 저장 게임에 적용할 수 있는 콘텐츠만 표시할 수 있습니다!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"ko_KR", 	"팁: 콘텐츠를 클릭하면 해당 콘텐츠의 세부 정보 패널이 표시됩니다. 다시 클릭하면 숨겨집니다."),
		("LOC_FF16_MODSCREEN_TIP_5",		"ko_KR", 	"팁: 콘텐츠 충돌이 발생하면 비슷한 콘텐츠를 하나씩 비활성화하여 어떤 콘텐츠가 문제를 일으키는지 확인해 보세요."),
		("LOC_FF16_MODSCREEN_TIP_6",		"ko_KR", 	"팁: 만약 간디(Gandhi)가 당신의 우라늄을 요구하면 거부하세요."),
		("LOC_FF16_MODSCREEN_TIP_7",		"ko_KR", 	"팁: 저장 게임에 영향을 미치는 콘텐츠는 기존 저장을 로드할 때 자동으로 로드되거나 로드 해제됩니다."),
		("LOC_FF16_MODSCREEN_TIP_8",		"ko_KR", 	"팁: 특정 콘텐츠 구성을 좋아하십니까? 현재 콘텐츠 그룹을 저장하려면 오른쪽 상단에 있는 추가 아이콘을 클릭하세요."),
		("LOC_FF16_MODSCREEN_TIP_9",		"ko_KR", 	"팁: 새로운 콘텐츠를 즐기고 계십니까? 작성자에게 친절한 일을 하여 워크샵에서 콘텐츠에 평점을 매겨주세요!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"ko_KR", 	"콘텐츠 적용 즐기세요!"),
		("LOC_FF16_MODSCREEN_TIP_11", 		"ko_KR", 	"팁: 여러 콘텐츠를 동시에 활성화 또는 비활성화하려면 Shift 키를 누른 상태로 콘텐츠를 선택하세요!"),
		("LOC_FF16_MODSCREEN_TIP_12", 		"ko_KR", 	"팁: 사용자 정의 콘텐츠 필터를 정의할 수 있습니다! 자세한 내용은 CustomFilters.xml을 확인하세요."),
		("LOC_FF16_MODSCREEN_TIP_13", 		"ko_KR", 	"팁: 가장 최근에 사용한 콘텐츠는 자동으로 '자동: 최근 사용한 콘텐츠' 콘텐츠 그룹에 저장됩니다.");