-- Building
-- Author: Flactine
-- DateCreated: 2/9/2020 7:33:39 PM
--------------------------------------------------------------

--仅首都加住房宜居

INSERT INTO Types
			(Type,	Kind)
VALUES		('MODIFIER_MENTAL_AI_POLICY_HOUSING',			'KIND_MODIFIER'),
		('MODIFIER_MENTAL_AI_POLICY_AMENITY',			'KIND_MODIFIER');


INSERT INTO DynamicModifiers
			(ModifierType,												CollectionType,						EffectType)
VALUES		('MODIFIER_MENTAL_AI_POLICY_HOUSING',			'COLLECTION_OWNER',			'EFFECT_ADJUST_POLICY_HOUSING'),
		('MODIFIER_MENTAL_AI_POLICY_AMENITY',			'COLLECTION_OWNER',			'EFFECT_ADJUST_POLICY_AMENITY');


--=====
--BuildingModifiers
--=====
INSERT INTO BuildingModifiers
(BuildingType,								ModifierId)
VALUES
('BUILDING_PALACE',		'MENTAL_AI_COPYUNITS_CLASS_WAR_CART'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_MELEE'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_RANGED'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_HEAVY_CAVALRY'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_LIGHT_CAVALRY'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_ANTI_CAVALRY'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_RANGED_CAVALRY'),
('BUILDING_PALACE',		'MENTAL_AI_LAND_GIANT_DEATH_ROBOT'),

('BUILDING_PALACE',		'MENTAL_AI_NAVAL_MELEE'),
('BUILDING_PALACE',		'MENTAL_AI_NAVAL_RANGED'),
('BUILDING_PALACE',		'MENTAL_AI_NAVAL_CARRIER'),

('BUILDING_PALACE',		'MENTAL_AI_HOUSE'),
('BUILDING_PALACE',		'MENTAL_AI_AMENITY'),


('BUILDING_PALACE',		'MENTAL_AI_GAIN_HORSES'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_IRON'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_NITER'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_COAL'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_OIL'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_URANIUM'),
('BUILDING_PALACE',		'MENTAL_AI_GAIN_ALUMINUM');

--=====
--Modifiers
--=====
INSERT INTO Modifiers
(ModifierId,				ModifierType,												SubjectRequirementSetId)
VALUES	
('MENTAL_AI_COPYUNITS_CLASS_WAR_CART',			'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',	'PLAYER_IS_AI'),
('MENTAL_AI_LAND_MELEE',				'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_RANGED',				'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_HEAVY_CAVALRY',		'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_LIGHT_CAVALRY',		'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_ANTI_CAVALRY',			'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_RANGED_CAVALRY',		'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_LAND_GIANT_DEATH_ROBOT',	'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),

('MENTAL_AI_NAVAL_MELEE',				'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_NAVAL_RANGED',				'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),
('MENTAL_AI_NAVAL_CARRIER',				'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_UNIT_COPY_TAG',		'PLAYER_IS_AI'),

('MENTAL_AI_HOUSE',					'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',					'PLAYER_IS_AI'),
('MENTAL_AI_AMENITY',					'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_AMENITY',					'PLAYER_IS_AI'),


('MENTAL_AI_GAIN_HORSES',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_HORSES_REQUIREMENTS'),
('MENTAL_AI_GAIN_IRON',				'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_IRON_REQUIREMENTS'),
('MENTAL_AI_GAIN_NITER',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_NITER_REQUIREMENTS'),
('MENTAL_AI_GAIN_COAL',				'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_COAL_REQUIREMENTS'),
('MENTAL_AI_GAIN_OIL',				'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_OIL_REQUIREMENTS'),
('MENTAL_AI_GAIN_ALUMINUM',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_ALUMINUM_REQUIREMENTS'),
('MENTAL_AI_GAIN_URANIUM',			'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',		'MENTAL_AI_GAIN_URANIUM_REQUIREMENTS');
--=====
--ModifierArguments
--=====
INSERT INTO ModifierArguments
(ModifierId,					Name,				Value)
VALUES						


('MENTAL_AI_COPYUNITS_CLASS_WAR_CART',			'Tag',	'CLASS_WAR_CART'),
('MENTAL_AI_COPYUNITS_CLASS_WAR_CART',			'Amount',	1),
('MENTAL_AI_LAND_MELEE',		'Tag',				'CLASS_MELEE'),
('MENTAL_AI_LAND_MELEE',		'Amount',			1),
('MENTAL_AI_LAND_RANGED',		'Tag',				'CLASS_RANGED'),
('MENTAL_AI_LAND_RANGED',		'Amount',			1),
('MENTAL_AI_LAND_HEAVY_CAVALRY',		'Tag',				'CLASS_HEAVY_CAVALRY'),
('MENTAL_AI_LAND_HEAVY_CAVALRY',		'Amount',			1),
('MENTAL_AI_LAND_LIGHT_CAVALRY',		'Tag',				'CLASS_LIGHT_CAVALRY'),
('MENTAL_AI_LAND_LIGHT_CAVALRY',		'Amount',			1),
('MENTAL_AI_LAND_ANTI_CAVALRY',			'Tag',				'CLASS_ANTI_CAVALRY'),
('MENTAL_AI_LAND_ANTI_CAVALRY',			'Amount',			1),
('MENTAL_AI_LAND_RANGED_CAVALRY',		'Tag',				'CLASS_RANGED_CAVALRY'),
('MENTAL_AI_LAND_RANGED_CAVALRY',		'Amount',			1),
('MENTAL_AI_LAND_GIANT_DEATH_ROBOT',	'Tag',				'CLASS_GIANT_DEATH_ROBOT'),
('MENTAL_AI_LAND_GIANT_DEATH_ROBOT',	'Amount',			1),


('MENTAL_AI_NAVAL_MELEE',				'Tag',				'CLASS_NAVAL_MELEE'),
('MENTAL_AI_NAVAL_MELEE',				'Amount',			1),
('MENTAL_AI_NAVAL_RANGED',				'Tag',				'CLASS_NAVAL_RANGED'),
('MENTAL_AI_NAVAL_RANGED',				'Amount',			1),
('MENTAL_AI_NAVAL_CARRIER',				'Tag',				'CLASS_NAVAL_CARRIER'),
('MENTAL_AI_NAVAL_CARRIER',				'Amount',			1),

('MENTAL_AI_HOUSE',				'Amount',			6),
('MENTAL_AI_AMENITY',				'Amount',			4),




('MENTAL_AI_GAIN_HORSES',			'ResourceType',					'RESOURCE_HORSES'),
('MENTAL_AI_GAIN_HORSES',			'Amount',						20),
('MENTAL_AI_GAIN_IRON',				'ResourceType',					'RESOURCE_IRON'),
('MENTAL_AI_GAIN_IRON',				'Amount',						20),
('MENTAL_AI_GAIN_NITER',			'ResourceType',					'RESOURCE_NITER'),
('MENTAL_AI_GAIN_NITER',			'Amount',						20),
('MENTAL_AI_GAIN_COAL',				'ResourceType',					'RESOURCE_COAL'),
('MENTAL_AI_GAIN_COAL',				'Amount',						30),
('MENTAL_AI_GAIN_OIL',				'ResourceType',					'RESOURCE_OIL'),
('MENTAL_AI_GAIN_OIL',				'Amount',						30),
('MENTAL_AI_GAIN_ALUMINUM',			'ResourceType',					'RESOURCE_ALUMINUM'),
('MENTAL_AI_GAIN_ALUMINUM',			'Amount',						20),
('MENTAL_AI_GAIN_URANIUM',			'ResourceType',					'RESOURCE_URANIUM'),
('MENTAL_AI_GAIN_URANIUM',			'Amount',						10);



--送资源前置

INSERT INTO Requirements

	(RequirementId,												RequirementType)
VALUES
	('REQUIRES_PLAYER_HAS_HORSEBACK_RIDING',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_IRON_WORKING',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_MILITARY_ENGINEERING',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_INDUSTRIALIZATION',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_REFINING',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_RADIO',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
	('REQUIRES_PLAYER_HAS_COMBINED_ARMS',						'REQUIREMENT_PLAYER_HAS_TECHNOLOGY');





INSERT INTO RequirementArguments
	(RequirementId,												Name,										Value)
VALUES
	('REQUIRES_PLAYER_HAS_HORSEBACK_RIDING',						'TechnologyType',						'TECH_ANIMAL_HUSBANDRY'),
	('REQUIRES_PLAYER_HAS_IRON_WORKING',						'TechnologyType',						'TECH_BRONZE_WORKING'),
	('REQUIRES_PLAYER_HAS_MILITARY_ENGINEERING',					'TechnologyType',						'TECH_MILITARY_ENGINEERING'),
	('REQUIRES_PLAYER_HAS_INDUSTRIALIZATION',						'TechnologyType',						'TECH_INDUSTRIALIZATION'),
	('REQUIRES_PLAYER_HAS_REFINING',						'TechnologyType',						'TECH_REFINING'),
	('REQUIRES_PLAYER_HAS_RADIO',						'TechnologyType',						'TECH_RADIO'),
	('REQUIRES_PLAYER_HAS_COMBINED_ARMS',						'TechnologyType',						'TECH_COMBINED_ARMS');



INSERT INTO RequirementSets
	(RequirementSetId,											RequirementSetType)
VALUES
	('MENTAL_AI_GAIN_HORSES_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_IRON_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_NITER_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_COAL_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_OIL_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_ALUMINUM_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('MENTAL_AI_GAIN_URANIUM_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL');


INSERT INTO RequirementSetRequirements
	(RequirementSetId,											RequirementId)
VALUES
	('MENTAL_AI_GAIN_HORSES_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_HORSES_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_HORSEBACK_RIDING'),
	('MENTAL_AI_GAIN_HORSES_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_IRON_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_IRON_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_IRON_WORKING'),
	('MENTAL_AI_GAIN_IRON_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_NITER_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_NITER_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_MILITARY_ENGINEERING'),
	('MENTAL_AI_GAIN_NITER_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_COAL_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_COAL_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_INDUSTRIALIZATION'),
	('MENTAL_AI_GAIN_COAL_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_OIL_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_OIL_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_REFINING'),
	('MENTAL_AI_GAIN_OIL_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_ALUMINUM_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_ALUMINUM_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_RADIO'),
	('MENTAL_AI_GAIN_ALUMINUM_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI'),
	('MENTAL_AI_GAIN_URANIUM_REQUIREMENTS',					'REQUIRES_MAJOR_CIV_OPPONENT'),
	('MENTAL_AI_GAIN_URANIUM_REQUIREMENTS',					'REQUIRES_PLAYER_HAS_COMBINED_ARMS'),
	('MENTAL_AI_GAIN_URANIUM_REQUIREMENTS',					'REQUIRES_PLAYER_IS_AI');






-- MA_Diplomacy
-- Author: Flactine
-- DateCreated: 6/14/2021 3:45:13 PM
--------------------------------------------------------------
--=====
--LeaderTraits
--=====
INSERT INTO LeaderTraits	
(LeaderType,			TraitType)
VALUES
('LEADER_DEFAULT',		'TRAIT_LEADER_AGGRESSIVE_MILITARY');
--=====
--TraitModifiers
--=====
INSERT INTO TraitModifiers	
(TraitType,						ModifierId)
VALUES
('TRAIT_LEADER_MAJOR_CIV',		'MENTAL_AI_LOVE_AI'),
('TRAIT_LEADER_MAJOR_CIV',		'MENTAL_AI_HATE_HUMAN');
--=====
--Modifiers
--=====
INSERT INTO Modifiers	
(ModifierId,					ModifierType,									SubjectRequirementSetId)
VALUES
('MENTAL_AI_LOVE_AI',			'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',	'PLAYER_IS_AI'),
('MENTAL_AI_HATE_HUMAN',		'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',	'PLAYER_IS_HUMAN');
--=====
--ModifierArguments
--=====
INSERT INTO ModifierArguments	
(ModifierId,					Name,								Value)
VALUES
('MENTAL_AI_LOVE_AI',			'InitialValue',						0),
('MENTAL_AI_LOVE_AI',			'StatementKey',						'LOC_MENTAL_AI_HATE_HUMAN_SMD'),
('MENTAL_AI_LOVE_AI',			'SimpleModifierDescription',		'LOC_MENTAL_AI_HATE_HUMAN_SMD'),
('MENTAL_AI_HATE_HUMAN',		'InitialValue',						-10),
('MENTAL_AI_HATE_HUMAN',		'StatementKey',						'LOC_MENTAL_AI_HATE_HUMAN_SMD'),
('MENTAL_AI_HATE_HUMAN',		'SimpleModifierDescription',		'LOC_MENTAL_AI_HATE_HUMAN_SMD');
--=====
--ModifierStrings
--=====
INSERT INTO ModifierStrings				
(ModifierId,				Context,		Text)
VALUES
('MENTAL_AI_LOVE_AI',		'Sample',		'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL'),
('MENTAL_AI_HATE_HUMAN',	'Sample',		'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL');






