

INSERT INTO LocalizedText ( Language, Tag, Text ) 
 VALUES ('en_US', 'LOC_CN_BUTTON_TOOLTIP', '自定义通知'),
		('en_US', 'LOC_CN_TITLE', '自定义通知'),
		('en_US', 'LOC_CN_CITY_POP_CHECKBOX', '城市人口增长通知'),
		('en_US', 'LOC_CN_CITY_BORDER_CHECKBOX', '城市边界扩展通知'),
		('en_US', 'LOC_CN_TRADE_DEAL_CHECKBOX', '交易到期通知'),
		('en_US', 'LOC_CN_RELIGION_CHECKBOX', '宗教传播通知'),
		('en_US', 'LOC_CN_CITY_POP_TITLE', '城市人口增长'),
		('en_US', 'LOC_CN_CITY_POP_MESSAGE', ' {1_CN_City_Name}  的人口已经增加'),
		('en_US', 'LOC_CN_CITY_POP_MESSAGE_1', '部落村民已选择  {1_CN_City_Name} 作为他们的新家'),
		('en_US', 'LOC_CN_RELIGION_TITLE', '宗教传播'),
		('en_US', 'LOC_CN_RELIGION_MESSAGE', '现在 {1_CN_Religion_Name}  是 {2_CN_City_Name} 中的主流宗教'),
		('en_US', 'LOC_CN_RELIGION_MESSAGE_1', '现在 {1_CN_Religion_Name} 不再是  {2_CN_City_Name} 中的主流宗教'),
		('en_US', 'LOC_CN_CITY_BORDER_TITLE', '城市边界扩展'),
		('en_US', 'LOC_CN_CITY_BORDER_MESSAGE', '{1_CN_City_Name} 的边界拓展了'),
		('en_US', 'LOC_CN_TRADE_DEAL_TITLE', '交易到期'),
		('en_US', 'LOC_CN_TRADE_DEAL_MESSAGE', '您与 {1_CN_Player_Name} 的交易已过期'),


		('zh_Hans_CN', 'LOC_CN_BUTTON_TOOLTIP', '自定义通知'),
		('zh_Hans_CN', 'LOC_CN_TITLE', '自定义通知'),
		('zh_Hans_CN', 'LOC_CN_CITY_POP_CHECKBOX', '城市人口增长通知'),
		('zh_Hans_CN', 'LOC_CN_CITY_BORDER_CHECKBOX', '城市边界扩展通知'),
		('zh_Hans_CN', 'LOC_CN_TRADE_DEAL_CHECKBOX', '交易到期通知'),
		('zh_Hans_CN', 'LOC_CN_RELIGION_CHECKBOX', '宗教传播通知'),
		('zh_Hans_CN', 'LOC_CN_CITY_POP_TITLE', '城市人口增长'),
		('zh_Hans_CN', 'LOC_CN_CITY_POP_MESSAGE', ' {1_CN_City_Name}  的人口已经增加'),
		('zh_Hans_CN', 'LOC_CN_CITY_POP_MESSAGE_1', '部落村民已选择  {1_CN_City_Name} 作为他们的新家'),
		('zh_Hans_CN', 'LOC_CN_RELIGION_TITLE', '宗教传播'),
		('zh_Hans_CN', 'LOC_CN_RELIGION_MESSAGE', '现在 {1_CN_Religion_Name}  是 {2_CN_City_Name} 中的主流宗教'),
		('zh_Hans_CN', 'LOC_CN_RELIGION_MESSAGE_1', '现在 {1_CN_Religion_Name} 不再是  {2_CN_City_Name} 中的主流宗教'),
		('zh_Hans_CN', 'LOC_CN_CITY_BORDER_TITLE', '城市边界扩展'),
		('zh_Hans_CN', 'LOC_CN_CITY_BORDER_MESSAGE', '{1_CN_City_Name} 的边界拓展了'),
		('zh_Hans_CN', 'LOC_CN_TRADE_DEAL_TITLE', '交易到期'),
		('zh_Hans_CN', 'LOC_CN_TRADE_DEAL_MESSAGE', '您与 {1_CN_Player_Name} 的交易已过期'),


		('ru_RU', 'LOC_CN_BUTTON_TOOLTIP', 'Особые  уведомления'),
		('ru_RU', 'LOC_CN_TITLE', 'Особые  уведомления'),
		('ru_RU', 'LOC_CN_CITY_POP_CHECKBOX', 'Уведомление  о  росте  населения'),
		('ru_RU', 'LOC_CN_CITY_BORDER_CHECKBOX', 'Уведомление  о  расширении  границ  города'),
		('ru_RU', 'LOC_CN_TRADE_DEAL_CHECKBOX', 'Уведомление  об  истечении  действия  торгового  соглашения'),
		('ru_RU', 'LOC_CN_RELIGION_CHECKBOX', 'Уведомление  о  распространении  религии'),
		('ru_RU', 'LOC_CN_CITY_POP_TITLE', 'Прирост  населения'),
		('ru_RU', 'LOC_CN_CITY_POP_MESSAGE', 'Прирост  населения  в  {1_CN_City_Name}'),
		('ru_RU', 'LOC_CN_CITY_POP_MESSAGE_1', 'Туземцы  из  деревни  переселились  в  {1_CN_City_Name}'),
		('ru_RU', 'LOC_CN_RELIGION_TITLE', 'Распространение  религии'),
		('ru_RU', 'LOC_CN_RELIGION_MESSAGE', '{1_CN_Religion_Name}  теперь - основная  религия  в  {2_CN_City_Name}'),
		('ru_RU', 'LOC_CN_RELIGION_MESSAGE_1', '{1_CN_Religion_Name}  больше  не  является  основной  религией  в  {2_CN_City_Name}'),
		('ru_RU', 'LOC_CN_CITY_BORDER_TITLE', 'Расширение  границ  города'),
		('ru_RU', 'LOC_CN_CITY_BORDER_MESSAGE', '{1_CN_City_Name}  расширяет  свои  границы'),
		('ru_RU', 'LOC_CN_TRADE_DEAL_TITLE', 'Истечение  действия  торгового  соглашения'),
		('ru_RU', 'LOC_CN_TRADE_DEAL_MESSAGE', 'Истёк  срок  действия  вашего  торгового  соглашения  с  {1_CN_Player_Name}'),


		('es_ES', 'LOC_CN_TITLE', 'Notificaciones personalizadas'),
		('es_ES', 'LOC_CN_BUTTON_TOOLTIP', 'Notificaciones personalizadas'),
		('es_ES', 'LOC_CN_CITY_POP_CHECKBOX', 'Notificación de crecimiento de la población de la ciudad'),
		('es_ES', 'LOC_CN_CITY_BORDER_CHECKBOX', 'Notificación de la expansión de la frontera de la ciudad'),
		('es_ES', 'LOC_CN_TRADE_DEAL_CHECKBOX', 'Notificación de caducidad de acuerdo comercial'),
		('es_ES', 'LOC_CN_RELIGION_CHECKBOX', 'Notificación de propagación de religión'),
		('es_ES', 'LOC_CN_CITY_POP_TITLE', 'Crecimiento de la población de la ciudad'),
		('es_ES', 'LOC_CN_CITY_POP_MESSAGE', 'La población de {1_CN_City_Name}  ha aumentado'),
		('es_ES', 'LOC_CN_CITY_POP_MESSAGE_1', 'Los aldeanos tribales han elegido {1_CN_City_Name}  como su nuevo hogar'),
		('es_ES', 'LOC_CN_RELIGION_TITLE', 'Propagación de la religión'),
		('es_ES', 'LOC_CN_RELIGION_MESSAGE', '{1_CN_Religion_Name}  ahora es la religión dominante en  {2_CN_City_Name}'),
		('es_ES', 'LOC_CN_RELIGION_MESSAGE_1', '{1_CN_Religion_Name}  ya no es la religión dominante en  {2_CN_City_Name}'),
		('es_ES', 'LOC_CN_CITY_BORDER_TITLE', 'Expansión de la frontera de la ciudad'),
		('es_ES', 'LOC_CN_CITY_BORDER_MESSAGE', 'La ciudad de {1_CN_City_Name}  expande sus fronteras'),
		('es_ES', 'LOC_CN_TRADE_DEAL_TITLE', 'Vencimiento de oferta comercial'),
		('es_ES', 'LOC_CN_TRADE_DEAL_MESSAGE', 'Su acuerdo comercial con  {1_CN_Player_Name}  ha expirado.'),


		('it_IT', 'LOC_CN_BUTTON_TOOLTIP', 'Notifiche Personalizzate'),
		('it_IT', 'LOC_CN_TITLE', 'Notifiche Personalizzate'),
		('it_IT', 'LOC_CN_CITY_POP_CHECKBOX', 'Notifiche di crescita della popolazione'),
		('it_IT', 'LOC_CN_CITY_BORDER_CHECKBOX', 'Notifiche di espansione dei confini'),
		('it_IT', 'LOC_CN_TRADE_DEAL_CHECKBOX', 'Notifiche di scadenza degli accordi'),
		('it_IT', 'LOC_CN_RELIGION_CHECKBOX', 'Notifiche di diffusione religiosa'),
		('it_IT', 'LOC_CN_CITY_POP_TITLE', 'La popolazione in città è aumentata'),
		('it_IT', 'LOC_CN_CITY_POP_MESSAGE', 'Gli abitanti di {1_CN_City_Name} festeggiano la crescita della loro città!'),
		('it_IT', 'LOC_CN_CITY_POP_MESSAGE_1', 'Gli abitanti di un villaggio tribale hanno scelto {1_CN_City_Name} come loro nuova casa'),
		('it_IT', 'LOC_CN_RELIGION_TITLE', 'Una città si è convertita'),
		('it_IT', 'LOC_CN_RELIGION_MESSAGE', '''{1_CN_Religion_Name}''  è il nome del nuovo culto dominante tra i cittadini di {2_CN_City_Name}'),
		('it_IT', 'LOC_CN_RELIGION_MESSAGE_1', 'I cittadini di {2_CN_City_Name} hanno perso la fede! ''{1_CN_Religion_Name}'' non è più la religione dominante'),
		('it_IT', 'LOC_CN_CITY_BORDER_TITLE', 'La città ha esteso i confini'),
		('it_IT', 'LOC_CN_CITY_BORDER_MESSAGE', 'Nei pressi di {1_CN_City_Name} i confini del tuo impero si sono appena espansi'),
		('it_IT', 'LOC_CN_TRADE_DEAL_TITLE', 'L''accordo commerciale è terminato'),
		('it_IT', 'LOC_CN_TRADE_DEAL_MESSAGE', 'Lo scambio commerciale avvenuto con {1_CN_Player_Name} è appena scaduto');