INSERT INTO MajorStartingUnits(Unit, Era, District, Quantity) VALUES
    ('UNIT_SLINGER', 'ERA_ANCIENT', 'DISTRICT_CITY_CENTER', 1),
	('UNIT_SCOUT', 'ERA_ANCIENT', 'DISTRICT_CITY_CENTER', 1),
    ('UNIT_BUILDER', 'ERA_ANCIENT', 'DISTRICT_CITY_CENTER', 1);