-- AWAW_NORESTART_Config
-- Author: Awase
-- DateCreated: 1/28/2026 3:50:08 PM
--------------------------------------------------------------

INSERT OR REPLACE INTO Parameters (ParameterId, Name, Description, Domain, ConfigurationGroup, ConfigurationId, GroupId, SortIndex, Array)
VALUES ('AWAW_StartHeroesSelector', 'LOC_START_HEROES_NAME', 'LOC_START_HEROES_DESCRIPTION', 'AWAW_StartHeroesDomain', 'Game', 'AWAW_START_HEROES_SELECTED', 'AdvancedOptions', 222, 1);

INSERT OR REPLACE INTO DomainValues (Domain, Value, Name, Description, SortIndex) VALUES
('AWAW_StartHeroesDomain', 'HEROCLASS_ANANSI', 'LOC_UNIT_HERO_ANANSI_NAME', 'LOC_UNIT_HERO_ANANSI_DESCRIPTION', 1),
('AWAW_StartHeroesDomain', 'HEROCLASS_ARTHUR', 'LOC_UNIT_HERO_ARTHUR_NAME', 'LOC_UNIT_HERO_ARTHUR_DESCRIPTION', 2),
('AWAW_StartHeroesDomain', 'HEROCLASS_BEOWULF', 'LOC_UNIT_HERO_BEOWULF_NAME', 'LOC_UNIT_HERO_BEOWULF_DESCRIPTION', 3),
('AWAW_StartHeroesDomain', 'HEROCLASS_HERCULES', 'LOC_UNIT_HERO_HERCULES_NAME', 'LOC_UNIT_HERO_HERCULES_DESCRIPTION', 4),
('AWAW_StartHeroesDomain', 'HEROCLASS_HIMIKO', 'LOC_UNIT_HERO_HIMIKO_NAME', 'LOC_UNIT_HERO_HIMIKO_DESCRIPTION', 5),
('AWAW_StartHeroesDomain', 'HEROCLASS_HIPPOLYTA', 'LOC_UNIT_HERO_HIPPOLYTA_NAME', 'LOC_UNIT_HERO_HIPPOLYTA_DESCRIPTION', 6),
('AWAW_StartHeroesDomain', 'HEROCLASS_HUNAHPU', 'LOC_UNIT_HERO_HUNAHPU_NAME', 'LOC_UNIT_HERO_HUNAHPU_DESCRIPTION', 7),
('AWAW_StartHeroesDomain', 'HEROCLASS_MAUI', 'LOC_UNIT_HERO_MAUI_NAME', 'LOC_UNIT_HERO_MAUI_DESCRIPTION', 8),
('AWAW_StartHeroesDomain', 'HEROCLASS_MULAN', 'LOC_UNIT_HERO_MULAN_NAME', 'LOC_UNIT_HERO_MULAN_DESCRIPTION', 9),
('AWAW_StartHeroesDomain', 'HEROCLASS_OYA', 'LOC_UNIT_HERO_OYA_NAME', 'LOC_UNIT_HERO_OYA_DESCRIPTION', 10),
('AWAW_StartHeroesDomain', 'HEROCLASS_SINBAD', 'LOC_UNIT_HERO_SINBAD_NAME', 'LOC_UNIT_HERO_SINBAD_DESCRIPTION', 11),
('AWAW_StartHeroesDomain', 'HEROCLASS_WUKONG', 'LOC_UNIT_HERO_WUKONG_NAME', 'LOC_UNIT_HERO_WUKONG_DESCRIPTION', 12);

--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_NANA', 'LOC_UNIT_HERO_FLACS_NANA_NAME', 'LOC_UNIT_HERO_FLACS_NANA_DESCRIPTION', 13),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_CHITO_YUURI', 'LOC_UNIT_HERO_FLACS_CHITO_YUURI_NAME', 'LOC_UNIT_HERO_FLACS_CHITO_YUURI_DESCRIPTION', 14),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_MAPLE', 'LOC_UNIT_HERO_FLACS_MAPLE_NAME', 'LOC_UNIT_HERO_FLACS_MAPLE_DESCRIPTION', 15),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_KOMORI', 'LOC_UNIT_HERO_FLACS_KOMORI_NAME', 'LOC_UNIT_HERO_FLACS_KOMORI_DESCRIPTION', 16),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_CLARISSA', 'LOC_UNIT_HERO_FLACS_CLARISSA_NAME', 'LOC_UNIT_HERO_FLACS_CLARISSA_DESCRIPTION', 17),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_ANDY_LAW', 'LOC_UNIT_HERO_FLACS_ANDY_LAW_NAME', 'LOC_UNIT_HERO_FLACS_ANDY_LAW_DESCRIPTION', 18),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_REMEDY', 'LOC_UNIT_HERO_FLACS_REMEDY_NAME', 'LOC_UNIT_HERO_FLACS_REMEDY_DESCRIPTION', 19),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_LEE_HUANG', 'LOC_UNIT_HERO_FLACS_LEE_HUANG_NAME', 'LOC_UNIT_HERO_FLACS_LEE_HUANG_DESCRIPTION', 20),
--('AWAW_StartHeroesDomain', 'HEROCLASS_FLACS_SEKIRO', 'LOC_UNIT_HERO_FLACS_SEKIRO_NAME', 'LOC_UNIT_HERO_FLACS_SEKIRO_DESCRIPTION', 21);
-- 如果有更多MOD英雄，需要在这里手动添加