-- KAIJU
-- Author: QIANCHUANBAILANG
-- DateCreated: 2025-8-7 22:45:53
--------------------------------------------------------------

-- Custom ModifierType
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
('MODIFIER_NW_ALL_PLAYERS_GRANT_YIELD', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_NW_ALL_PLAYERS_GRANT_YIELD', 'COLLECTION_ALL_PLAYERS', 'EFFECT_GRANT_YIELD');

INSERT OR REPLACE INTO GameModifiers (ModifierId) VALUES
('MODIFIER_HUMAN_GRANT_25_FAITH');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId) VALUES
('MODIFIER_HUMAN_GRANT_25_FAITH', 'MODIFIER_NW_ALL_PLAYERS_GRANT_YIELD','PLAYER_IS_HUMAN_AND_HAS_A_CITY');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Type, Value) VALUES
('MODIFIER_HUMAN_GRANT_25_FAITH', 'YieldType', 'ARGTYPE_IDENTITY','YIELD_FAITH'),
('MODIFIER_HUMAN_GRANT_25_FAITH', 'Amount', 'ScaleByGameSpeed','10');


INSERT OR REPLACE INTO GameModifiers (ModifierId) VALUES
('MODIFIER_HUMAN_GRANT_100_GOLD');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId) VALUES
('MODIFIER_HUMAN_GRANT_100_GOLD', 'MODIFIER_NW_ALL_PLAYERS_GRANT_YIELD', 'PLAYER_IS_HUMAN_AND_HAS_A_CITY');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Type, Value) VALUES
('MODIFIER_HUMAN_GRANT_100_GOLD', 'YieldType', 'ARGTYPE_IDENTITY','YIELD_GOLD'),
('MODIFIER_HUMAN_GRANT_100_GOLD', 'Amount', 'ScaleByGameSpeed','0');


-- RequirementSets
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('PLAYER_IS_HUMAN_AND_HAS_A_CITY', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('PLAYER_IS_HUMAN_AND_HAS_A_CITY', 'REQ_NW_PLAYER_IS_HUMAN'), 
('PLAYER_IS_HUMAN_AND_HAS_A_CITY', 'REQ_NW_PLAYER_HAS_BUILDING_PALACE');

-- Requirements
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_NW_PLAYER_IS_HUMAN', 'REQUIREMENT_PLAYER_IS_HUMAN'), 
('REQ_NW_PLAYER_HAS_BUILDING_PALACE', 'REQUIREMENT_PLAYER_HAS_BUILDING');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_NW_PLAYER_HAS_BUILDING_PALACE', 'BuildingType', 'BUILDING_PALACE');