-- ============================================
-- HarvestUnlock.sql — LoadOrder=99999999
-- 确保最后一个加载
--
-- TECH_BUILDERSAIL → 所有加成资源 + 奢侈品资源 开局可收获
-- TECH_SCOUTSAIL   → 所有可移除地貌 开局可移除
-- ============================================

UPDATE Resource_Harvests SET PrereqTech = 'TECH_BUILDERSAIL' WHERE PrereqTech IS NOT NULL;

INSERT OR REPLACE INTO Resource_Harvests (ResourceType, YieldType, Amount, PrereqTech)
VALUES
('RESOURCE_CITRUS',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_COCOA',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_COFFEE',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_COTTON',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_DIAMONDS',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_DYES',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_FURS',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_GYPSUM',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_INCENSE',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_IVORY',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_JADE',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_MARBLE',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_MERCURY',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_PEARLS',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_SALT',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_SILK',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_SILVER',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_SPICES',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_SUGAR',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_TEA',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_TOBACCO',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_TRUFFLES',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_WHALES',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL'),
('RESOURCE_WINE',		'YIELD_GOLD', 20, 'TECH_BUILDERSAIL');




UPDATE Features SET RemoveTech = 'TECH_SCOUTSAIL' WHERE Removable = 1;

-- ============================================
-- Part 4: 火山土、绿洲、礁石、地热裂缝 — 设为可移除
-- 基础游戏中这四种地貌不可移除，此处新增 Removable=1
-- ============================================
UPDATE Features SET Removable = 1, RemoveTech = 'TECH_SCOUTSAIL'
WHERE FeatureType IN (
	'FEATURE_VOLCANIC_SOIL',
	'FEATURE_OASIS',
	'FEATURE_REEF',
	'FEATURE_GEOTHERMAL_FISSURE'
);

-- ============================================
-- Part 5: 四种新增地貌的移除产出（Feature_Removes）
-- 基础游戏中这些地貌没有 Feature_Removes 条目，此处新增
-- ============================================
INSERT OR REPLACE INTO Feature_Removes (FeatureType, YieldType, Yield)
VALUES
('FEATURE_FOREST',	'YIELD_PRODUCTION',		20),
('FEATURE_JUNGLE',	'YIELD_PRODUCTION',	10),
('FEATURE_JUNGLE',	'YIELD_FOOD',		10),
('FEATURE_MARSH',		'YIELD_FOOD',		20),
('FEATURE_VOLCANIC_SOIL',	'YIELD_PRODUCTION',	20),
('FEATURE_OASIS',		'YIELD_FOOD',		20),
('FEATURE_REEF',		'YIELD_FOOD',		10),
('FEATURE_REEF',		'YIELD_PRODUCTION',	10),
('FEATURE_GEOTHERMAL_FISSURE',	'YIELD_PRODUCTION',	20);
