-- BCSP_Config
-- Author: Maple_Leaves
-- DateCreated: 10/26/2024 10:30:00 PM
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BCSP_FiraxisCityStates (
CivilizationType TEXT NOT NULL,
PRIMARY KEY (CivilizationType)
);


INSERT OR IGNORE INTO BCSP_FiraxisCityStates
(CivilizationType	)
VALUES
('CIVILIZATION_ZANZIBAR'),
('CIVILIZATION_JOHANNESBURG'),
('CIVILIZATION_WOLIN'),
('CIVILIZATION_CAHOKIA'),
('CIVILIZATION_NAN_MADOL'),
('CIVILIZATION_AKKAD'),
('CIVILIZATION_KABUL'),
('CIVILIZATION_ARMAGH'),
('CIVILIZATION_NAZCA'),
('CIVILIZATION_KUMASI'),
('CIVILIZATION_HONG_KONG'),
('CIVILIZATION_VALLETTA'),
('CIVILIZATION_SAMARKAND'),
('CIVILIZATION_NGAZARGAMU'),
('CIVILIZATION_PRESLAV'),
('CIVILIZATION_YEREVAN'),
('CIVILIZATION_KANDY'),
('CIVILIZATION_VILNIUS'),
('CIVILIZATION_GRANADA'),
('CIVILIZATION_ANTIOCH'),
('CIVILIZATION_CAGUANA'),
('CIVILIZATION_LISBON'),
('CIVILIZATION_JERUSALEM'),
('CIVILIZATION_CHINGUETTI'),
('CIVILIZATION_GENEVA'),
('CIVILIZATION_JAKARTA'),
('CIVILIZATION_VATICAN_CITY'),
('CIVILIZATION_LAHORE'),
('CIVILIZATION_BRUSSELS'),
('CIVILIZATION_MEXICO_CITY'),
('CIVILIZATION_CARDIFF'),
('CIVILIZATION_FEZ'),
('CIVILIZATION_ANTANANARIVO'),
('CIVILIZATION_NALANDA'),
('CIVILIZATION_LA_VENTA'),
('CIVILIZATION_AUCKLAND'),
('CIVILIZATION_HUNZA'),
('CIVILIZATION_TARUGA'),
('CIVILIZATION_AYUTTHAYA'),
('CIVILIZATION_BABYLON'),
('CIVILIZATION_SINGAPORE'),
('CIVILIZATION_HATTUSA'),
('CIVILIZATION_BOLOGNA'),
('CIVILIZATION_MOHENJO_DARO'),
('CIVILIZATION_RAPA_NUI'),
('CIVILIZATION_PALENQUE'),
('CIVILIZATION_BUENOS_AIRES'),
('CIVILIZATION_MUSCAT');