INSERT OR IGNORE INTO TypeProperties(Type, Name, Value) VALUES
('UNIT_SETTLER', 'CAN_TELEPORT_TO_CITY', 1),
('UNIT_BUILDER', 'CAN_TELEPORT_TO_CITY', 1),
('UNIT_MILITARY_ENGINEER', 'CAN_TELEPORT_TO_CITY', 1),
('UNIT_WONDER_THEFT', 'CAN_TELEPORT_TO_CITY', 1);
