--总督重做



-------------------------------------------Moksha-------------------------------------------

INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_CARDINAL_0',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3',				'KIND_GOVERNOR_PROMOTION');

DELETE FROM GovernorPromotions WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_CARDINAL_%';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_CARDINAL_%';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion LIKE 'GOVERNOR_PROMOTION_CARDINAL_%';

UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_CARDINAL_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_CARDINAL';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,													Level,		Column,		BaseAbility)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_0',						'LOC_GOVERNOR_PROMOTION_H_CARDINAL_0_NAME',						'LOC_GOVERNOR_PROMOTION_H_CARDINAL_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1_DESCRIPTION',		1,			2,			0),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'LOC_GOVERNOR_PROMOTION_H_CARDINAL_2_NAME',						'LOC_GOVERNOR_PROMOTION_H_CARDINAL_2_DESCRIPTION',				2,			1,			0),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3_NAME',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3_DESCRIPTION',			3,			0,			0),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3_NAME',				'LOC_GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3_DESCRIPTION',		3,			2,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_0'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_0'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3',				'GOVERNOR_PROMOTION_H_CARDINAL_2'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3',				'GOVERNOR_PROMOTION_H_CARDINAL_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_0'),
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1'),
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1'),
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_2'),
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3'),
	('GOVERNOR_THE_CARDINAL',				'GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3');



--Moksha Promotion Effect
INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_0',						'GOVERNOR_PROMOTION_H_CARDINAL_0_PROPHET'),
	('GOVERNOR_PROMOTION_H_CARDINAL_0',						'CARDINAL_LAYING_ON_OF_HANDS_HEAL'),
	('GOVERNOR_PROMOTION_H_CARDINAL_0',						'CARDINAL_LAYING_ON_OF_HANDS_RELIGIOUS_HEAL'),
	--
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1',				'CARDINAL_BISHOP_FAITH_DISTRICT'),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_1',				'CARDINAL_GRAND_INQUISITOR_COMBAT'),
	--
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_0_RELIGIOUS_CHARGE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_MISSIONARY'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_APOSTLE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_GURU'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_INQUISITOR'),
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_1',				'GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_WARRIOR_MONK'),
	--
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'CARDINAL_CITADEL_OF_GOD_PRESSURE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',				'CARDINAL_CITADEL_OF_GOD_COMBAT'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'CARDINAL_BISHOP_PRESSURE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_2',						'REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE'),
	--
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3',				'CARDINAL_FAITH_PURCHASE_DISTRICT'),
	('GOVERNOR_PROMOTION_H_CARDINAL_LEFT_3',				'CARDINAL_CITADEL_OF_GOD_FAITH_FINISH_BUILDINGS'),
	--
	('GOVERNOR_PROMOTION_H_CARDINAL_RIGHT_3',				'GOVERNOR_PROMOTION_H_CARDINAL_R3_PROMOTION');

--------------------------------Moksha 0: HolySite +2 Prophet Point, Religion Units +1 spread

INSERT INTO Modifiers 
	(ModifierId,												ModifierType,													SubjectRequirementSetId)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_0_PROPHET',					'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',	'DISTRICT_IS_HOLY_SITE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_0_RELIGIOUS_CHARGE',		'MODIFIER_SINGLE_CITY_RELIGIOUS_SPREADS',						'MOSQUE_RELIGIOUS_UNIT');

INSERT INTO ModifierArguments 
	(ModifierId,												Name,							Value)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_0_PROPHET',					'GreatPersonClassType',			'GREAT_PERSON_CLASS_PROPHET'),
	('GOVERNOR_PROMOTION_H_CARDINAL_0_PROPHET',					'Amount',						1),
	('GOVERNOR_PROMOTION_H_CARDINAL_0_RELIGIOUS_CHARGE',		'Amount',						1);

--------------------------------Moksha RIGHT 1: Grant Apostle, -30% Religion Unit Purchase Cost

INSERT INTO Types 
	(Type,																Kind)
VALUES
	('MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,														CollectionType,					EffectType)
VALUES
	('MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			'COLLECTION_OWNER',				'EFFECT_ADJUST_UNIT_PURCHASE_COST');


INSERT INTO Modifiers 
	(ModifierId,																ModifierType,														RunOnce,			Permanent,			SubjectRequirementSetId)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_MISSIONARY',			'MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			0,					0,					NULL),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_APOSTLE',				'MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			0,					0,					NULL),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_GURU',					'MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			0,					0,					NULL),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_INQUISITOR',			'MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			0,					0,					NULL),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_WARRIOR_MONK',			'MODIFIER_H_GOR_SINGLE_CITIES_ADJUST_UNIT_PURCHASE_COST',			0,					0,					NULL);

INSERT INTO ModifierArguments 
	(ModifierId,																Name,							Value)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_MISSIONARY',			'UnitType',						'UNIT_MISSIONARY'),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_MISSIONARY',			'Amount',						15),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_APOSTLE',				'UnitType',						'UNIT_APOSTLE'),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_APOSTLE',				'Amount',						15),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_GURU',					'UnitType',						'UNIT_GURU'),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_GURU',					'Amount',						15),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_INQUISITOR',			'UnitType',						'UNIT_INQUISITOR'),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_INQUISITOR',			'Amount',						15),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_WARRIOR_MONK',			'UnitType',						'UNIT_WARRIOR_MONK'),
	('GOVERNOR_PROMOTION_H_CARDINAL_R1_RELIGION_DISCOUNT_WARRIOR_MONK',			'Amount',						15);



--------------------------------Moksha Right 3: Religion Units +1 Promotion created

INSERT INTO Modifiers 
	(ModifierId,																ModifierType)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_R3_PROMOTION',								'MODIFIER_SINGLE_CITY_RELIGION_EXTRA_PROMOTIONS');

INSERT INTO ModifierArguments 
	(ModifierId,																Name,							Value)
VALUES
	('GOVERNOR_PROMOTION_H_CARDINAL_R3_PROMOTION',								'Amount',						1);
	
-------------------------------------------Magnus-------------------------------------------
INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3',		'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3',		'KIND_GOVERNOR_PROMOTION');

DELETE FROM GovernorPromotions WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_%';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_%';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion LIKE 'GOVERNOR_PROMOTION_RESOURCE_MANAGER_%';

UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_RESOURCE_MANAGER_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_RESOURCE_MANAGER';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,															Level,		Column,		BaseAbility)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0',				'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_NAME',				'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_NAME',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1_NAME',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1_DESCRIPTION',		1,			2,			0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2',				'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2_NAME',				'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2_DESCRIPTION',				2,			1,			0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3_NAME',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3_DESCRIPTION',			3,			0,			0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3_NAME',		'LOC_GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3_DESCRIPTION',		3,			2,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2',				'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2',				'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0'),
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1'),
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1'),
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2'),
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3'),
	('GOVERNOR_THE_RESOURCE_MANAGER',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3');

--Magnus Promotion Reward
	--This Part has been finished by lua

--Magnus Promotion Effect
INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0',				'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0'),
	--
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1',		'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER'),
	--
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'DEFENSE_LOGISTICS_BONUS_STRATEGICS'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'BLACK_MARKETEER_STRATEGIC_RESOURCE_COST_DISCOUNT'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_1',		'REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE'),
	--
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_2',		'EXPEDITION_ADJUST_SETTLERS_CONSUME_POPULATION'),
	--
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_3',		'VERTICAL_INTEGRATION_PRODUCTION_REGIONAL_STACKING'),
	--
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3',		'MAGNUS_REGIONAL_6'),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_RIGHT_3',		'MAGNUS_REGIONAL_9');


--------------------------------老马右3横向结合能力
INSERT INTO Modifiers
	(ModifierId,													ModifierType,							SubjectRequirementSetId)
values
	('MAGNUS_REGIONAL_6',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',			'GOR_MAGNUS_6_TILES_REQUIREMENTS'),
	('MAGNUS_REGIONAL_9',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',			'H_GOR_VICTOR_UNIT_9_TILES_REQUIREMENTS');


insert or replace into ModifierArguments
	(ModifierId,										Name,				Value)
values	
	('MAGNUS_REGIONAL_6',						'YieldType',		'YIELD_FOOD, YIELD_PRODUCTION, YIELD_CULTURE, YIELD_SCIENCE'),
	('MAGNUS_REGIONAL_6',							'Amount',			'2,2,2,2'),
	('MAGNUS_REGIONAL_9',						'YieldType',		'YIELD_FOOD, YIELD_PRODUCTION, YIELD_CULTURE, YIELD_SCIENCE'),
	('MAGNUS_REGIONAL_9',							'Amount',			'2,2,2,2');

--------------------------------Magnus 0: Harvest +50%

INSERT INTO Modifiers 
	(ModifierId,															ModifierType,													SubjectRequirementSetId,							Permanent,				SubjectStackLimit)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0',								'MODIFIER_CITY_ADJUST_RESOURCE_HARVEST_BONUS',					'CITY_NOT_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',		0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_OFFICE',						'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						NULL,												1,						NULL),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_OFFICE_MODIFIER',				'MODIFIER_CITY_ADJUST_RESOURCE_HARVEST_BONUS',					'CITY_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',			0,						1);

INSERT INTO ModifierArguments 
	(ModifierId,															Name,					Value)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0',								'Amount',				50),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_OFFICE',						'ModifierId',			'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_OFFICE_MODIFIER'),					
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_0_OFFICE_MODIFIER',				'Amount',				30);

--------------------------------Magnus Left 1: Buildings, Districts, Wonders Production +20%

INSERT INTO Types 
	(Type,													Kind)
VALUES
	('MODIFIER_H_CITY_INCREASE_BUILDING_PRODUCTION_RATE',	'KIND_MODIFIER'),
	('MODIFIER_H_CITY_INCREASE_WONDER_PRODUCTION_RATE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,											CollectionType,					EffectType)
VALUES
	('MODIFIER_H_CITY_INCREASE_BUILDING_PRODUCTION_RATE',	'COLLECTION_OWNER',				'EFFECT_ADJUST_ALL_BUILDING_PRODUCTION_MODIFIER'),
	('MODIFIER_H_CITY_INCREASE_WONDER_PRODUCTION_RATE',		'COLLECTION_OWNER',				'EFFECT_ADJUST_WONDER_PRODUCTION');


INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,													SubjectRequirementSetId,							Permanent,				SubjectStackLimit)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT',								'MODIFIER_CITY_INCREASE_DISTRICT_PRODUCTION_RATE',				'CITY_NOT_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',		0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT_OFFICE',						'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						NULL,												1,						NULL),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT_OFFICE_MODIFIER',				'MODIFIER_CITY_INCREASE_DISTRICT_PRODUCTION_RATE',				'CITY_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',			0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING',								'MODIFIER_H_CITY_INCREASE_BUILDING_PRODUCTION_RATE',			'CITY_NOT_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',		0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE',						'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						NULL,												1,						NULL),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE_MODIFIER',				'MODIFIER_H_CITY_INCREASE_BUILDING_PRODUCTION_RATE',			'CITY_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',			0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER',									'MODIFIER_H_CITY_INCREASE_WONDER_PRODUCTION_RATE',				'CITY_NOT_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',		0,						1),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER_OFFICE',							'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						NULL,												1,						NULL),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER_OFFICE_MODIFIER',					'MODIFIER_H_CITY_INCREASE_WONDER_PRODUCTION_RATE',				'CITY_HAS_MAGNUS_OFFICE_H_REQUIREMENTS',			0,						1);

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,					Value)
VALUES
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT',								'Amount',				-25),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT_OFFICE',						'ModifierId',			'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT_OFFICE_MODIFIER'),					
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_DISTRICT_OFFICE_MODIFIER',				'Amount',				25),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING',								'Amount',				25),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING',								'IsWonder',				0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE',						'ModifierId',			'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE_MODIFIER'),					
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE_MODIFIER',				'Amount',				25),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_BUILDING_OFFICE_MODIFIER',				'IsWonder',				0),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER',									'Amount',				15),
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER_OFFICE',							'ModifierId',			'GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER_OFFICE_MODIFIER'),					
	('GOVERNOR_PROMOTION_H_RESOURCE_MANAGER_LEFT_1_WONDER_OFFICE_MODIFIER',					'Amount',				15);




-------------------------------------------Victor-------------------------------------------

INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_DEFENDER_0',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'KIND_GOVERNOR_PROMOTION');

--DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_DEFENDER_GUILDMASTER';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_GARRISON_COMMANDER';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_DEFENSE_LOGISTICS';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_EMBRASURE';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AIR_DEFENSE_INITIATIVE';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_EDUCATOR_ARMS_RACE_PROPONENT';

--DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_DEFENDER_GUILDMASTER';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_GARRISON_COMMANDER';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_DEFENSE_LOGISTICS';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_EMBRASURE';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AIR_DEFENSE_INITIATIVE';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_EDUCATOR_ARMS_RACE_PROPONENT';

--DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_DEFENDER_GUILDMASTER';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_GARRISON_COMMANDER';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_DEFENSE_LOGISTICS';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_EMBRASURE';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AIR_DEFENSE_INITIATIVE';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_EDUCATOR_ARMS_RACE_PROPONENT';

UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_DEFENDER_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_DEFENDER';
UPDATE GovernorPromotions SET Description = 'LOC_GOVERNOR_PROMOTION_H_DEFENDER_0_DESCRIPTION' WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_REDOUBT';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,													Level,		Column,		BaseAbility)
VALUES
	--('GOVERNOR_PROMOTION_DEFENDER_GUILDMASTER',			'LOC_GOVERNOR_PROMOTION_H_DEFENDER_0_NAME',						'LOC_GOVERNOR_PROMOTION_H_DEFENDER_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1_DESCRIPTION',		1,			2,			0),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2_NAME',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2_DESCRIPTION',			2,			0,			0),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2_NAME',				'LOC_GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2_DESCRIPTION',		2,			2,			0),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'LOC_GOVERNOR_PROMOTION_H_DEFENDER_3_NAME',						'LOC_GOVERNOR_PROMOTION_H_DEFENDER_3_DESCRIPTION',				3,			1,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'GOVERNOR_PROMOTION_REDOUBT'),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1',				'GOVERNOR_PROMOTION_REDOUBT'),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2',				'GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1'),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2',				'GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	--('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_0'),
	('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1'),
	('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1'),
	('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2'),
	('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2'),
	('GOVERNOR_THE_DEFENDER',				'GOVERNOR_PROMOTION_H_DEFENDER_3');

--Victor Promotion Reward

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType)														
VALUES
	('GOVERNOR_DEFENDER_PROMOTION_REWARD_MILITARY_UNIT_PRODUCTION',							'MODIFIER_SINGLE_CITY_ADJUST_MILITARY_UNITS_PRODUCTION');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_DEFENDER_PROMOTION_REWARD_MILITARY_UNIT_PRODUCTION',							'Amount',															'5');

INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	SELECT GovernorPromotion, 'GOVERNOR_DEFENDER_PROMOTION_REWARD_MILITARY_UNIT_PRODUCTION' FROM GovernorPromotionSets WHERE GovernorType = 'GOVERNOR_THE_DEFENDER';

--Victor Promotion Effect

INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	('GOVERNOR_PROMOTION_REDOUBT',							'GOVERNOR_PROMOTION_H_DEFENDER_0_GENERAL'),
	--
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'DEFENSE_LOGISTICS_SIEGE_PROTECTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE'),
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_1',				'CITY_DEFENDER_ADJUST_ATTACKS_PER_TURN'),
	--
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1',				'PRESTIGE_IDENTITY_PRESSURE_TO_DOMESTIC_CITIES'),
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_1',				'GARRISON_COMMANDER_ADJUST_CITY_COMBAT_BONUS'),
	--
	('GOVERNOR_PROMOTION_H_DEFENDER_LEFT_2',				'CITY_DEFENDER_FREE_PROMOTIONS'),
	--
	('GOVERNOR_PROMOTION_H_DEFENDER_RIGHT_2',				'GOVERNOR_PROMOTION_H_DEFENDER_L1_MOVEMENT'),
	--
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'EDUCATOR_FASTER_MANHATTAN_PROJECT_RESEARCH'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'EDUCATOR_FASTER_OPERATION_IVY_RESEARCH'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'EDUCATOR_FASTER_NUCLEAR_DEVICE_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_DEFENDER_3',						'EDUCATOR_FASTER_THERMONUCLEAR_DEVICE_PRODUCTION');

--------------------------------Victor 0: City cannot be seiged.+2 Great General Point for Encampment

INSERT INTO Modifiers 
	(ModifierId,												ModifierType,													SubjectRequirementSetId)
VALUES
	('GOVERNOR_PROMOTION_H_DEFENDER_0_GENERAL',					'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',	'DISTRICT_IS_ENCAMPMENT'),
	('GOVERNOR_PROMOTION_H_DEFENDER_0_SEIGE_PROTECTION',		'MODIFIER_CITY_ADJUST_SIEGE_PROTECTION',						NULL);

INSERT INTO ModifierArguments 
	(ModifierId,												Name,							Value)
VALUES
	('GOVERNOR_PROMOTION_H_DEFENDER_0_GENERAL',					'GreatPersonClassType',			'GREAT_PERSON_CLASS_GENERAL'),
	('GOVERNOR_PROMOTION_H_DEFENDER_0_GENERAL',					'Amount',						1),
	('GOVERNOR_PROMOTION_H_DEFENDER_0_SEIGE_PROTECTION',		'Protected',					1);

--------------------------------Victor L1: Unit within 9 plots +1 Movement

INSERT INTO Types
	(Type,													Kind)
VALUES
	('ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT',				'KIND_ABILITY');

INSERT INTO TypeTags
	(Type,													Tag)
VALUES
	('ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT',				'CLASS_ALL_UNITS');

INSERT OR REPLACE INTO UnitAbilities
	(UnitAbilityType,										Name,																Description,														Inactive,					Permanent)
VALUES
	('ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT',				'LOC_ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT_NAME',					'LOC_ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT_DESCRIPTION',				1,							0);

INSERT INTO UnitAbilityModifiers
	(UnitAbilityType,										ModifierId)
VALUES
	('ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT',				'H_GOR_DEFENDER_UNIT_MOVEMENT_MODIFIER');

INSERT INTO Modifiers 
	(ModifierId,												ModifierType,													SubjectRequirementSetId)
VALUES
	('GOVERNOR_PROMOTION_H_DEFENDER_L1_MOVEMENT',				'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							'H_GOR_VICTOR_UNIT_9_TILES_REQUIREMENTS'),
	('H_GOR_DEFENDER_UNIT_MOVEMENT_MODIFIER',					'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT',							NULL);

INSERT INTO ModifierArguments 
	(ModifierId,												Name,							Value)
VALUES
	('GOVERNOR_PROMOTION_H_DEFENDER_L1_MOVEMENT',				'AbilityType',					'ABILITY_H_GOR_DEFENDER_UNIT_MOVEMENT'),
	('H_GOR_DEFENDER_UNIT_MOVEMENT_MODIFIER',					'Amount',						1);


-------------------------------------------Pingala-------------------------------------------


-------------------------------------------Reyna-------------------------------------------

INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_MERCHANT_0',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',				'KIND_GOVERNOR_PROMOTION');

DELETE FROM GovernorPromotions WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_MERCHANT_%' AND GovernorPromotionType <> 'GOVERNOR_PROMOTION_MERCHANT_CURATOR';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType LIKE 'GOVERNOR_PROMOTION_MERCHANT_%' AND GovernorPromotionType <> 'GOVERNOR_PROMOTION_MERCHANT_CURATOR';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion LIKE 'GOVERNOR_PROMOTION_MERCHANT_%' AND GovernorPromotion <> 'GOVERNOR_PROMOTION_MERCHANT_CURATOR';

UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_MERCHANT_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_MERCHANT';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,													Level,		Column,		BaseAbility)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_0',						'LOC_GOVERNOR_PROMOTION_H_MERCHANT_0_NAME',						'LOC_GOVERNOR_PROMOTION_H_MERCHANT_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1_DESCRIPTION',		1,			2,			0),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',						'LOC_GOVERNOR_PROMOTION_H_MERCHANT_2_NAME',						'LOC_GOVERNOR_PROMOTION_H_MERCHANT_2_DESCRIPTION',				2,			1,			0),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3_NAME',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3_DESCRIPTION',			3,			0,			0),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3_NAME',				'LOC_GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3_DESCRIPTION',		3,			2,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_0'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_0'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',						'GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',						'GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_2'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_0'),
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1'),
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1'),
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_2'),
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3'),
	('GOVERNOR_THE_MERCHANT',				'GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3');


--Reyna Promotion Effect

INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_0',						'LAND_ACQUISITION_FASTER_PLOT_ANNEXING'),
	('GOVERNOR_PROMOTION_H_MERCHANT_0',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_0',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),
	--
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_ARRIVAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_PRODUCTION_ARRIVAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_1',				'MODIFIER_BEARGOV_PORTS_PROD_FROM_CITIES'),
	--
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'FORESTRY_MANAGEMENT_FEATURE_NO_IMPROVEMENT_APPEAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_0_CITIZEN_GOLD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_1',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),

	--

	('GOVERNOR_PROMOTION_H_MERCHANT_2',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',			'MODIFIER_BEARGOV_THOUGHT_GOLD_PER_PERSON'),
	('GOVERNOR_PROMOTION_H_MERCHANT_2',						'MODIFIER_BEARGOV_EXCHANGE_BUILDINGS'),
	--
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',						'CONTRACTOR_ENABLE_DISTRICT_PURCHASE'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_LEFT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),
	--
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',				'GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',			'MODIFIER_BEARGOV_SUBS_AMENITIES'),
	('GOVERNOR_PROMOTION_H_MERCHANT_RIGHT_3',			'MODIFIER_BEARGOV_GRID_AMENITIES');

--------------------------------Reyna MINE


INSERT INTO Modifiers
	(ModifierId,																			ModifierType)
VALUES
	('MODIFIER_BEARGOV_THOUGHT_GOLD_PER_PERSON',							'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER');

INSERT INTO ModifierArguments
	(ModifierId,																			Name,					Value)
VALUES
	('MODIFIER_BEARGOV_THOUGHT_GOLD_PER_PERSON',		'YieldType',				'YIELD_GOLD'),
	('MODIFIER_BEARGOV_THOUGHT_GOLD_PER_PERSON',		'Amount',					20);




INSERT INTO Modifiers
			(ModifierId,									ModifierType,											RunOnce,	Permanent,	SubjectRequirementSetId)
VALUES
			('MODIFIER_BEARGOV_PORTS_PROD_FROM_CITIES',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		0,			0,				'MINE_REYNA_COAST_CITY_1_REQUIREMENTS');

INSERT INTO ModifierArguments
			(ModifierId,										Name,					Value)
VALUES			('MODIFIER_BEARGOV_PORTS_PROD_FROM_CITIES',			'Amount',				2),
			('MODIFIER_BEARGOV_PORTS_PROD_FROM_CITIES',			'YieldType',			'YIELD_PRODUCTION');


INSERT INTO Modifiers
			(ModifierId,									ModifierType,													NewOnly,	Permanent,	SubjectRequirementSetId)
VALUES		('MODIFIER_BEARGOV_SUBS_AMENITIES',				'MODIFIER_PLAYER_OWNED_LUXURY_EXTRA_AMENITIES',					0,			0,			NULL),
			('MODIFIER_BEARGOV_GRID_AMENITIES',				'MODIFIER_PLAYER_CITIES_ADJUST_AMENITIES_FROM_GOVERNORS',		0,			0,			'CITY_IS_POWERED');

INSERT INTO ModifierArguments
			(ModifierId,									Name,				Value)
VALUES		('MODIFIER_BEARGOV_SUBS_AMENITIES',				'Amount',			1),
			('MODIFIER_BEARGOV_GRID_AMENITIES',				'Amount',			1);



INSERT INTO Modifiers
			(ModifierId,									ModifierType,													RunOnce,	Permanent,	SubjectRequirementSetId)
VALUES		('MODIFIER_BEARGOV_EXCHANGE_BUILDINGS',			'MODIFIER_BEARGOV_PCITIES_ALL_BUILDINGS_DISCOUNT',				0,			0,			'MINE_REYNA_BUILDING_REQUIREMENTS');

INSERT INTO ModifierArguments
			(ModifierId,									Name,				Value)
VALUES		('MODIFIER_BEARGOV_EXCHANGE_BUILDINGS',			'Amount',			20);




--------------------------------Reyna 0: Citizen +2 Gold

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_0_CITIZEN_GOLD',										'MODIFIER_CITY_ADJUST_CITIZEN_GOLD_PER_TURN');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,					Value)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_0_CITIZEN_GOLD',										'Amount',				2);


--------------------------------Reyna Left 1: Commercial Hub & Harbor +100% Adjacency within 6 tiles

INSERT INTO Types 
	(Type,																					Kind)
VALUES
	('MODIFIER_H_GOR_SINGLE_DISTRICT_ADJUST_YIELD_MODIFIER',								'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,																			CollectionType,								EffectType)
VALUES
	('MODIFIER_H_GOR_SINGLE_DISTRICT_ADJUST_YIELD_MODIFIER',								'COLLECTION_OWNER',							'EFFECT_ADJUST_DISTRICT_YIELD_MODIFIER');


INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY',								'MODIFIER_H_GOR_PLAYER_DISTRICTS_ATTACH_MODIFIER',					'H_GOR_SIX_PLOTS_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY',									'MODIFIER_H_GOR_PLAYER_DISTRICTS_ATTACH_MODIFIER',					'H_GOR_SIX_PLOTS_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY_MODIFIER',						'MODIFIER_H_GOR_SINGLE_DISTRICT_ADJUST_YIELD_MODIFIER',				'DISTRICT_IS_COMMERCIAL_HUB'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY_MODIFIER',							'MODIFIER_H_GOR_SINGLE_DISTRICT_ADJUST_YIELD_MODIFIER',				'DISTRICT_IS_HARBOR');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY',								'ModifierId',														'GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY_MODIFIER'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY',									'ModifierId',														'GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY_MODIFIER'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY_MODIFIER',						'YieldType',														'YIELD_GOLD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_COMMERCIAL_ADJACENCY_MODIFIER',						'Amount',															50),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY_MODIFIER',							'YieldType',														'YIELD_GOLD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_L1_HARBOR_ADJACENCY_MODIFIER',							'Amount',															50);

--------------------------------Reyna Right 1: Trade Route +4 Gold for departure, +3 for Arrival

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC',										'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL',									'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_ARRIVAL',										'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_PRODUCTION_ARRIVAL',										'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC',										'YieldType',														'YIELD_GOLD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_DOMESTIC',										'Amount',															1),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL',									'YieldType',														'YIELD_GOLD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_INTERNATIONAL',									'Amount',															1),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_ARRIVAL',										'YieldType',														'YIELD_FOOD'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_ARRIVAL',										'Amount',															1),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_GOLD_ARRIVAL',										'Domestic',															1),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_PRODUCTION_ARRIVAL',										'YieldType',														'YIELD_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_PRODUCTION_ARRIVAL',										'Amount',															1),
	('GOVERNOR_PROMOTION_H_MERCHANT_R1_PRODUCTION_ARRIVAL',										'Domestic',															1);


-------------------------------------------Liang-------------------------------------------

INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_BUILDER_0',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'KIND_GOVERNOR_PROMOTION');

--DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_ZONING_COMMISSIONER';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AQUACULTURE';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_WATER_WORKS';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_PARKS_RECREATION';

--DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_ZONING_COMMISSIONER';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AQUACULTURE';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_WATER_WORKS';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_PARKS_RECREATION';

--DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_ZONING_COMMISSIONER';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AQUACULTURE';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_WATER_WORKS';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_PARKS_RECREATION';

UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_BUILDER_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_BUILDER';
UPDATE GovernorPromotions SET Description = 'LOC_GOVERNOR_PROMOTION_H_BUILDER_0_DESCRIPTION' WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,													Level,		Column,		BaseAbility)
VALUES
	--('GOVERNOR_PROMOTION_BUILDER_GUILDMASTER',						'LOC_GOVERNOR_PROMOTION_H_BUILDER_0_NAME',						'LOC_GOVERNOR_PROMOTION_H_BUILDER_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'LOC_GOVERNOR_PROMOTION_H_BUILDER_LEFT_1_NAME',					'LOC_GOVERNOR_PROMOTION_H_BUILDER_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'LOC_GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1_DESCRIPTION',			1,			2,			0),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'LOC_GOVERNOR_PROMOTION_H_BUILDER_2_NAME',						'LOC_GOVERNOR_PROMOTION_H_BUILDER_2_DESCRIPTION',				2,			1,			0),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'LOC_GOVERNOR_PROMOTION_H_BUILDER_LEFT_3_NAME',					'LOC_GOVERNOR_PROMOTION_H_BUILDER_LEFT_3_DESCRIPTION',			3,			0,			0),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'LOC_GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3_NAME',				'LOC_GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3_DESCRIPTION',			3,			2,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'GOVERNOR_PROMOTION_H_BUILDER_LEFT_1'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'GOVERNOR_PROMOTION_H_BUILDER_2'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	--('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_0'),
	('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_LEFT_1'),
	('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1'),
	('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_2'),
	('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_LEFT_3'),
	('GOVERNOR_THE_BUILDER',				'GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3');


--Liang Promotion Effect

INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	--('GOVERNOR_PROMOTION_H_BUILDER_0',						'GOVERNOR_PROMOTION_H_BUILDER_0_BUILDER'),
	('GOVERNOR_PROMOTION_BUILDER_GUILDMASTER',						'MINE_FISHERY_GOVERNOR_PRODUCTION'),
	--
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'MINE_PCITIES_WONDER_YIELD_CHANGE_CULTURE'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'MINE_PCITIES_WONDER_YIELD_CHANGE_SCIENCE'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_1',					'ARCHITECTURE_MASTER_WONDERS_BOOST'),
	--
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION_LATER'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_1',				'LIANG_POP_PRODUCTION'),
	--
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'WATER_WORKS_CANAL_AMENITY'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'WATER_WORKS_DAM_AMENITY'),
	('GOVERNOR_PROMOTION_H_BUILDER_2',						'WATER_WORKS_AQUEDUCT_AMENITY'),
	--
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'MINE_PCITIES_WONDER_YIELD_CHANGE_FAITH'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'MINE_PCITIES_WONDER_YIELD_CHANGE_GOLD'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'GOVERNOR_PROMOTION_H_BUILDER_L3_IMPROVEMENT_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_LEFT_3',					'GOVERNOR_PROMOTION_H_BUILDER_L3_NATIONAL_PARK_TOURISM'),
	--
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_ALL_CITY_ALLOW_CITY_PARK'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_CAMPUS_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_THEATER_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_INDUSTRIAL_ZONE_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_COMMERCIAL_HUB_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_HARBOR_ADJACENCY'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_HOLY_SITE_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_CAMPUS_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_INDUSTRIAL_ZONE_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_COMMERCIAL_HUB_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_RIGHT_3',				'GOVERNOR_PROMOTION_H_BUILDER_R3_THEATER_TOURISM');

-- Fishery鱼场科技解锁，公园修改

UPDATE Improvements SET TraitType = NULL WHERE ImprovementType = 'IMPROVEMENT_FISHERY';
UPDATE Improvements SET Description = 'LOC_IMPROVEMENT_FISHERY_H_GOR_DESCRIPTION' WHERE ImprovementType = 'IMPROVEMENT_FISHERY';
UPDATE Improvements SET PrereqTech = 'TECH_SHIPBUILDING' WHERE ImprovementType = 'IMPROVEMENT_FISHERY';
DELETE FROM ImprovementModifiers WHERE ModifierId = 'MINE_FISHERY_GOVERNOR_PRODUCTION';
UPDATE Improvements SET Description = 'LOC_IMPROVEMENT_CITY_PARK_H_GOR_DESCRIPTION' WHERE ImprovementType = 'IMPROVEMENT_CITY_PARK';
DELETE FROM ImprovementModifiers WHERE ModifierId = 'CITY_PARK_GOVERNOR_CULTURE';



--------------------------------梁自改，人口锤,就职渔场生产力

UPDATE ImprovementModifiers SET ModifierId = 'MINE_FISHERY_GOVERNOR_PRODUCTION' WHERE ImprovementType = 'IMPROVEMENT_FISHERY';


insert or replace into Modifiers
	(ModifierId,												ModifierType,												SubjectRequirementSetId)
values
	('LIANG_POP_PRODUCTION',								'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',	NULL),
	('MINE_FISHERY_GOVERNOR_PRODUCTION',								'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS',	'MINE_FISHERY_GOVERNOR_PRODUCTION_REQUIREMENTS');


insert or replace into ModifierArguments
	(ModifierId,												Name,											Value)
values
	('MINE_FISHERY_GOVERNOR_PRODUCTION',								'YieldType',									'YIELD_PRODUCTION'),
	('MINE_FISHERY_GOVERNOR_PRODUCTION',								'Amount',									1),
	('LIANG_POP_PRODUCTION',								'YieldType',									'YIELD_PRODUCTION'),
	('LIANG_POP_PRODUCTION',								'Amount',										0.6);

--------------------------------梁公园全国化

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,	
												SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_ALL_CITY_ALLOW_CITY_PARK',										'MODIFIER_GOVERNOR_PROMOTION_ALL_CITY_ALLOW_CITY_PARK',							NULL);

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_ALL_CITY_ALLOW_CITY_PARK',										'ImprovementType',													'IMPROVEMENT_CITY_PARK');

--------------------------------奇观强化

insert or replace into Modifiers
	(ModifierId,									ModifierType)
values
	('ARCHITECTURE_MASTER_WONDERS_BOOST',			'MODIFIER_H_CITY_INCREASE_WONDER_PRODUCTION_RATE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_SCIENCE',			'MODIFIER_MINE_PCITIES_WONDER_YIELD_CHANGE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_CULTURE',			'MODIFIER_MINE_PCITIES_WONDER_YIELD_CHANGE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_GOLD',			'MODIFIER_MINE_PCITIES_WONDER_YIELD_CHANGE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_FAITH',			'MODIFIER_MINE_PCITIES_WONDER_YIELD_CHANGE');

insert or replace into ModifierArguments
	(ModifierId,									Name,			Value)
values
	('ARCHITECTURE_MASTER_WONDERS_BOOST',			'Amount',				25),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_SCIENCE',			'YieldType',			'YIELD_SCIENCE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_SCIENCE',			'Amount',				1),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_CULTURE',			'YieldType',			'YIELD_CULTURE'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_CULTURE',			'Amount',				1),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_FAITH',			'YieldType',			'YIELD_FAITH'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_FAITH',			'Amount',				1),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_GOLD',			'YieldType',			'YIELD_GOLD'),
	('MINE_PCITIES_WONDER_YIELD_CHANGE_GOLD',			'Amount',				3);


--------------------------------水渠宜居度
insert or replace into Modifiers
	(ModifierId,									ModifierType,				SubjectRequirementSetId)
values
	('WATER_WORKS_AQUEDUCT_AMENITY',			'MODIFIER_CITY_DISTRICTS_ADJUST_DISTRICT_AMENITY',			'DISTRICT_IS_AQUEDUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,			Value)
values
	('WATER_WORKS_AQUEDUCT_AMENITY',			'Amount',				1);





--------------------------------Liang L1: Improved Resource Plots +2 Production 

INSERT INTO Types 
	(Type,														Kind)
VALUES
	('MODIFIER_H_GOR_CITY_ADJUST_YIELD_BY_NUMBER_RESOURCES',	'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
	(ModifierType,												CollectionType,								EffectType)
VALUES
	('MODIFIER_H_GOR_CITY_ADJUST_YIELD_BY_NUMBER_RESOURCES',	'COLLECTION_OWNER',				'EFFECT_ADJUST_YIELD_BY_NUMBER_OF_RESOURCES');


INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION',						'MODIFIER_H_GOR_CITY_ADJUST_YIELD_BY_NUMBER_RESOURCES',				NULL),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION_LATER',					'MODIFIER_H_GOR_CITY_ADJUST_YIELD_BY_NUMBER_RESOURCES',				'H_GOR_PLAYER_HAS_APPRENTICESHIP_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_PLOT',										'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',						'H_GOR_LIANG_L1_IMPROVED_REQUIREMENTS');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION',						'YieldType',														'YIELD_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION',						'Amount',															1),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION_LATER',					'YieldType',														'YIELD_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_RESOURCE_PRODUCTION_LATER',					'Amount',															1),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_PLOT',										'YieldType',														'YIELD_PRODUCTION'),
	('GOVERNOR_PROMOTION_H_BUILDER_L1_IMPROVED_PLOT',										'Amount',															1);



--------------------------------Liang 2: Allow Build City Park, City Park +1 Food,Production and 2 Culture in the city, +1 Adjacent Bonuses


INSERT INTO ImprovementModifiers
	(ImprovementType,																		ModifierId)
VALUES
	('IMPROVEMENT_CITY_PARK',																'H_GOR_CITY_PARK_FOOD'),
	('IMPROVEMENT_CITY_PARK',																'H_GOR_CITY_PARK_PRODUCTION'),
	('IMPROVEMENT_CITY_PARK',																'H_GOR_CITY_PARK_CULTURE');

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_2_ALLOW_CITY_PARK',										'MODIFIER_CITY_ADJUST_ALLOWED_IMPROVEMENT',							NULL),
	('H_GOR_CITY_PARK_FOOD',																'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS',							'H_GOR_LIANG_2_PROMOTION_REQUIREMENTS'),
	('H_GOR_CITY_PARK_PRODUCTION',															'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS',							'H_GOR_LIANG_2_PROMOTION_REQUIREMENTS'),
	('H_GOR_CITY_PARK_CULTURE',																'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS',							'H_GOR_LIANG_2_PROMOTION_REQUIREMENTS');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_2_ALLOW_CITY_PARK',										'ImprovementType',													'IMPROVEMENT_CITY_PARK'),
	('H_GOR_CITY_PARK_FOOD',																'YieldType',														'YIELD_FOOD'),
	('H_GOR_CITY_PARK_FOOD',																'Amount',															1),
	('H_GOR_CITY_PARK_PRODUCTION',															'YieldType',														'YIELD_PRODUCTION'),
	('H_GOR_CITY_PARK_PRODUCTION',															'Amount',															1),
	('H_GOR_CITY_PARK_CULTURE',																'YieldType',														'YIELD_CULTURE'),
	('H_GOR_CITY_PARK_CULTURE',																'Amount',															2);





--------------------------------Liang L3: +2 Appeal, +100% National Park & Improvement Tourism

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType)														
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_L3_APPEAL',												'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL'),
	('GOVERNOR_PROMOTION_H_BUILDER_L3_IMPROVEMENT_TOURISM',									'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_TOURISM'),
	('GOVERNOR_PROMOTION_H_BUILDER_L3_NATIONAL_PARK_TOURISM',								'MODIFIER_SINGLE_CITY_ADJUST_NATIONAL_PARK_TOURISM');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_BUILDER_L3_APPEAL',												'Amount',															2),
	('GOVERNOR_PROMOTION_H_BUILDER_L3_IMPROVEMENT_TOURISM',									'Amount',															200),
	('GOVERNOR_PROMOTION_H_BUILDER_L3_NATIONAL_PARK_TOURISM',								'Amount',															200);


-------------------------------------------Amani-------------------------------------------

INSERT INTO Types
	(Type,													Kind)
VALUES		 
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0',					'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2',					'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'KIND_GOVERNOR_PROMOTION'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',				'KIND_GOVERNOR_PROMOTION');

--DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_GUILDMASTER';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_EMISSARY';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_LOCAL_INFORMANTS';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_AFFLUENCE';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_FOREIGN_INVESTOR';
DELETE FROM GovernorPromotions WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_PUPPETEER';

--DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_GUILDMASTER';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_EMISSARY';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_LOCAL_INFORMANTS';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_AFFLUENCE';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_FOREIGN_INVESTOR';
DELETE FROM GovernorPromotionPrereqs WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_PUPPETEER';

--DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AMBASSADOR_GUILDMASTER';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AMBASSADOR_EMISSARY';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_LOCAL_INFORMANTS';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AMBASSADOR_AFFLUENCE';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AMBASSADOR_FOREIGN_INVESTOR';
DELETE FROM GovernorPromotionSets WHERE GovernorPromotion = 'GOVERNOR_PROMOTION_AMBASSADOR_PUPPETEER';

UPDATE Governors SET TransitionStrength = 200 WHERE GovernorType = 'GOVERNOR_THE_AMBASSADOR';
UPDATE Governors SET Description = 'LOC_GOVERNOR_THE_AMBASSADOR_H_DESCRIPTION' WHERE GovernorType = 'GOVERNOR_THE_AMBASSADOR';
UPDATE GovernorPromotions SET Description = 'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_0_DESCRIPTION' WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER';

INSERT OR REPLACE INTO GovernorPromotions
	(GovernorPromotionType,									Name,															Description,													Level,		Column,		BaseAbility)
VALUES
	--('GOVERNOR_PROMOTION_AMBASSADOR_GUILDMASTER',			'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_0_NAME',						'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_0_DESCRIPTION',				0,			1,			1),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1_DESCRIPTION',			1,			0,			0),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1_NAME',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1_DESCRIPTION',			1,			2,			0),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2_NAME',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2_DESCRIPTION',			2,			0,			0),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2_NAME',				'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2_DESCRIPTION',			2,			2,			0),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',					'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_3_NAME',					'LOC_GOVERNOR_PROMOTION_H_AMBASSADOR_3_DESCRIPTION',				3,			1,			0);

INSERT INTO GovernorPromotionPrereqs 
	(GovernorPromotionType,									PrereqGovernorPromotion)
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1',				'GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1',				'GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',					'GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',					'GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2');

INSERT INTO GovernorPromotionSets
	(GovernorType,							GovernorPromotion)
VALUES
	--('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_0'),
	('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1'),
	('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1'),
	('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2'),
	('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2'),
	('GOVERNOR_THE_AMBASSADOR',				'GOVERNOR_PROMOTION_H_AMBASSADOR_3');


--Amani Promotion Effect  

INSERT INTO GovernorPromotionModifiers 
	(GovernorPromotionType,									ModifierId)
VALUES
	('GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER',				'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE'),
	('GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER',				'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE'),
	('GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER',				'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH'),
	('GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER',				'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD'),
	--
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1',				'EMISSARY_IDENTITY_PRESSURE_TO_FOREIGN_CITIES'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_1',				'AFFLUENCE_COPY_LUXURIES_FOR_IMPORT'),
	--
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1',				'EMISSARY_IDENTITY_PRESSURE_TO_FOREIGN_CITIES'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_1',				'FOREIGN_INVESTOR_COPY_STRATEGICS_FOR_IMPORT'),
	--
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LESS_TIME'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_LEFT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LEVEL'),
	--
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'MODIFIER_BEARGOV_PUPPET_LEVY_TOKEN'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'MODIFIER_BEARGOV_PUPPET_LEVY_DISCOUNT'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_R1_OPEN_BORDER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_RIGHT_2',				'GOVERNOR_PROMOTION_H_AMBASSADOR_R1_INFLUENCE_POINT'),

	--
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',					'GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3',					'GOVERNOR_PROMOTION_H_AMBASSADOR_3_DOUBLE_ENVOY');

--------------------------------征兵降价

INSERT INTO Modifiers
			(ModifierId,									ModifierType,																RunOnce,	Permanent,	SubjectRequirementSetId)
VALUES		('MODIFIER_BEARGOV_PUPPET_LEVY_DISCOUNT',		'MODIFIER_PLAYER_ADJUST_LEVY_DISCOUNT_PERCENT',								0,			0,			NULL),
		('MODIFIER_BEARGOV_PUPPET_LEVY_TOKEN',			'MODIFIER_PLAYER_ADJUST_ENVOYS_FROM_LEVIED_CITY_STATES',					0,			0,			NULL);


INSERT INTO ModifierArguments
			(ModifierId,										Name,					Value)
VALUES		('MODIFIER_BEARGOV_PUPPET_LEVY_DISCOUNT',			'Percent',				25),
		('MODIFIER_BEARGOV_PUPPET_LEVY_TOKEN',				'Amount',				1);


--------------------------------Amani 0: Established natively +2 Science, Culture, Faith & Gold From Suzerain City States. Established in a city-state, provides a copy of its Luxury & Strategy

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_LUXURY',											'MODIFIER_GOVERNOR_ADJUST_CITY_COPY_LUXURIES_FOR_IMPORT',			NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_STRATEGY',											'MODIFIER_GOVERNOR_ADJUST_CITY_COPY_STRATEGICS_FOR_IMPORT',			NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE',										'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',								'H_GOR_AMANI_DOMESTIC_PROMOTION_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE_MODIFIER',								'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_TRIBUTARY',				NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE',										'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',								'H_GOR_AMANI_DOMESTIC_PROMOTION_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE_MODIFIER',								'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_TRIBUTARY',				NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH',											'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',								'H_GOR_AMANI_DOMESTIC_PROMOTION_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH_MODIFIER',								'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_TRIBUTARY',				NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD',											'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',								'H_GOR_AMANI_DOMESTIC_PROMOTION_REQUIREMENTS'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD_MODIFIER',									'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_TRIBUTARY',				NULL);

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE',										'ModifierId',														'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE_MODIFIER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE_MODIFIER',								'YieldType',														'YIELD_SCIENCE'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_SCIENCE_MODIFIER',								'Amount',															1),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE',										'ModifierId',														'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE_MODIFIER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE_MODIFIER',								'YieldType',														'YIELD_CULTURE'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_CULTURE_MODIFIER',								'Amount',															1),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH',											'ModifierId',														'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH_MODIFIER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH_MODIFIER',								'YieldType',														'YIELD_FAITH'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_FAITH_MODIFIER',								'Amount',															1),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD',											'ModifierId',														'GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD_MODIFIER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD_MODIFIER',									'YieldType',														'YIELD_GOLD'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_0_RAJ_GOLD_MODIFIER',									'Amount',															1);

--------------------------------Amani L1: +1 Spy capacity, Spy operations take 25% less time, Spy +1 Success probability

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LESS_TIME',									'MODIFIER_PLAYER_UNITS_ADJUST_SPY_OFFENSIVE_OPERATION_TIME',		'UNIT_IS_SPY'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LEVEL',										'MODIFIER_PLAYER_ADJUST_SPY_BONUS',									NULL);

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LESS_TIME',									'ReductionPercent',													25),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LEVEL',										'Offense',															1),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_L1_SPY_LEVEL',										'Amount',															1);

--------------------------------Amani R1: +8 Influence Point, Open City State Borders

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,										SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_R1_INFLUENCE_POINT',									'MODIFIER_PLAYER_ADJUST_INFLUENCE_POINTS_PER_TURN',					NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_R1_OPEN_BORDER',										'MODIFIER_ADJUST_OPEN_BORDERS_FROM_INFLUENCE',						'PLAYER_IS_MINOR');

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_R1_INFLUENCE_POINT',									'Amount',															3);



--------------------------------Amani 3: Established nationally -2 enemy Spy level; Established in City States double envoy num

INSERT INTO Modifiers 
	(ModifierId,																			ModifierType,														SubjectRequirementSetId)														
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY',											'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',								NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY_MODIFIER',									'MODIFIER_PLAYER_ADJUST_SPY_BONUS',									NULL),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_DOUBLE_ENVOY',										'MODIFIER_GOVERNOR_ADJUST_CITY_ENVOYS_MODIFIER',					NULL);

INSERT INTO ModifierArguments 
	(ModifierId,																			Name,																Value)
VALUES
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY',											'ModifierId',														'GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY_MODIFIER'),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY_MODIFIER',									'Offense',															0),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_ANTI_SPY_MODIFIER',									'Amount',															2),
	('GOVERNOR_PROMOTION_H_AMBASSADOR_3_DOUBLE_ENVOY',										'Percent',															100);




