-- Core
-- Author: Ithildin
-- DateCreated: 10/15/2023 9:30:01 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('BUILDING_STEELWALL',								'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings (BuildingType, Name, Description, PrereqTech, PrereqDistrict, Cost, AdvisorType, OuterDefenseHitPoints, OuterDefenseStrength, TraitType)
VALUES	('BUILDING_STEELWALL',	'LOC_TECH_STEEL_NAME',				'LOC_BUILDING_STAR_FORT_EXPANSION2_DESCRIPTION',	'TECH_STEEL',	'DISTRICT_CITY_CENTER', 999,	'ADVISOR_GENERIC', 300, 3, NULL);

INSERT OR REPLACE INTO BuildingPrereqs (Building, PrereqBuilding)
VALUES	('BUILDING_STEELWALL',								'BUILDING_STAR_FORT');

INSERT OR REPLACE INTO StartingBuildings (Era, Building, District, MinorOnly, MinDifficulty)
VALUES	('ERA_MEDIEVAL',									'BUILDING_CASTLE',		'DISTRICT_CITY_CENTER', 1,		'DIFFICULTY_IMMORTAL'),
		('ERA_RENAISSANCE',									'BUILDING_STAR_FORT',	'DISTRICT_CITY_CENTER', 1,		'DIFFICULTY_IMMORTAL'),
		('ERA_INFORMATION',									'BUILDING_STEELWALL',	'DISTRICT_CITY_CENTER', NULL,	NULL);

INSERT OR REPLACE INTO Building_YieldChanges (BuildingType, YieldType, YieldChange)
VALUES	('BUILDING_STEELWALL',								'YIELD_SCIENCE',	0);

INSERT OR REPLACE INTO Building_YieldsPerEra (BuildingType, YieldType, YieldChange)
VALUES	('BUILDING_STEELWALL',								'YIELD_SCIENCE',	1);

DELETE FROM TechnologyModifiers WHERE TechnologyType='TECH_STEEL' AND ModifierId='STEEL_UNLOCK_URBAN_DEFENSES';

INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_STEELWALL',								'STEEL_PREVENT_MELEE_ATTACK_OUTER_DEFENSES'),
		('BUILDING_STEELWALL',								'STEEL_PREVENT_BYPASS_OUTER_DEFENSE');

INSERT OR REPLACE INTO TechnologyModifiers (TechnologyType, ModifierId)
VALUES	('TECH_STEEL',										'MODFEAT_STEEL_GRANT_STEELWALL');

INSERT OR REPLACE INTO CivicModifiers (CivicType, ModifierId)
VALUES	('CIVIC_CONSERVATION',								'CONSERVATION_MODERN_WALL_TOURISM');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	('STEEL_PREVENT_MELEE_ATTACK_OUTER_DEFENSES',		'MODIFIER_SINGLE_CITY_ADJUST_PREVENT_MELEE_ATTACK_OUTER_DEFENSES',	NULL),
		('STEEL_PREVENT_BYPASS_OUTER_DEFENSE',				'MODIFIER_SINGLE_CITY_ADJUST_PREVENT_BYPASS_OUTER_DEFENSE',			NULL),
		('MODFEAT_STEEL_GRANT_STEELWALL',					'MODIFIER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE',					NULL),
		('CONSERVATION_MODERN_WALL_TOURISM',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_TOURISM_CHANGE',					'DISTRICT_IS_CITY_CENTER_MODERN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MODFEAT_STEEL_GRANT_STEELWALL',					'BuildingType',	'BUILDING_STEELWALL'),
		('CONSERVATION_MODERN_WALL_TOURISM',				'Amount',		3);

INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE',	'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE',	'COLLECTION_PLAYER_CITIES',	'EFFECT_GRANT_BUILDING_IN_CITY_IGNORE');

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('DISTRICT_IS_CITY_CENTER_MODERN',					'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('DISTRICT_IS_CITY_CENTER_MODERN',					'REQUIRES_DISTRICT_IS_CITY_CENTER'),
		('DISTRICT_IS_CITY_CENTER_MODERN',					'REQUIRES_CITY_HAS_MODERN_WALLS');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQUIRES_CITY_HAS_MODERN_WALLS',					'REQUIREMENT_CITY_HAS_BUILDING');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQUIRES_CITY_HAS_MODERN_WALLS',					'BuildingType', 'BUILDING_STEELWALL');