
--this is reusing the default reminder icon
INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_NOTIFICATION_AKGC_DEFAULTOPTIONS', 'ICON_ATLAS_NOTIFICATIONS', 0);

INSERT INTO IconAtlases (Name) VALUES
('ICON_ATLAS_AKGC');

INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_NOTIFICATION_AKGC_ENDOFERARANK', 'ICON_ATLAS_AKGC', 4),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_0', 'ICON_ATLAS_AKGC', 0),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_1', 'ICON_ATLAS_AKGC', 1),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_2', 'ICON_ATLAS_AKGC', 2),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_3', 'ICON_ATLAS_AKGC', 3),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_4', 'ICON_ATLAS_AKGC', 4),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_5', 'ICON_ATLAS_AKGC', 5),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_6', 'ICON_ATLAS_AKGC', 6),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_7', 'ICON_ATLAS_AKGC', 7),
('ICON_NOTIFICATION_AKGC_ENDOFERARANK_8', 'ICON_ATLAS_AKGC', 8);


INSERT INTO IconTextureAtlases (Name, IconSize, IconsPerRow, IconsPerColumn, Filename) VALUES
('ICON_ATLAS_AKGC', 36, 5, 2, 'akgc_notification_icons36.dds'),
('ICON_ATLAS_AKGC', 40, 5, 2, 'akgc_notification_icons40.dds'),
('ICON_ATLAS_AKGC', 100, 5, 2, 'akgc_notification_icons100.dds');

