--=============================================================
-- REGIONS
--=============================================================
-- Types
-------------------------------------
	INSERT INTO Types (Type, Kind) VALUES
	('REGION_SUK_FOREST', 'KIND_SUK_REGION'),
	('REGION_SUK_JUNGLE', 'KIND_SUK_REGION'),
	('REGION_SUK_CLIFFS', 'KIND_SUK_REGION'),
	('REGION_SUK_OASIS', 'KIND_SUK_REGION'),
	('REGION_SUK_MOUNTAINS', 'KIND_SUK_REGION'),
	('REGION_SUK_KELP', 'KIND_SUK_REGION'),
	('REGION_SUK_REEF', 'KIND_SUK_REGION'),
	('REGION_SUK_HILLS', 'KIND_SUK_REGION'),
	('REGION_SUK_PLAINS', 'KIND_SUK_REGION'),
	('REGION_SUK_GEOTHERMAL', 'KIND_SUK_REGION'),
	('REGION_SUK_MARSH', 'KIND_SUK_REGION'),
	('REGION_SUK_LAKE', 'KIND_SUK_REGION'),
	('REGION_SUK_DESERT', 'KIND_SUK_REGION'),
	('REGION_SUK_RIVER', 'KIND_SUK_REGION');
-------------------------------------
-- Regions
-------------------------------------
	INSERT INTO Suk_Regions (RegionType) VALUES
	('REGION_SUK_FOREST'),
	('REGION_SUK_JUNGLE'),
	('REGION_SUK_CLIFFS'),
	('REGION_SUK_OASIS'),
	('REGION_SUK_MOUNTAINS'),
	('REGION_SUK_KELP'),
	('REGION_SUK_REEF'),
	('REGION_SUK_HILLS'),
	('REGION_SUK_PLAINS'),
	('REGION_SUK_GEOTHERMAL'),
	('REGION_SUK_MARSH'),
	('REGION_SUK_LAKE'),
	('REGION_SUK_DESERT'),
	('REGION_SUK_RIVER');
--=============================================================
-- URBAN IDENTITIES
--=============================================================
-- Types
-------------------------------------
	INSERT INTO Types (Type, Kind) VALUES
	('IDENTITY_SUK_HARDWOOD_TREES', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_UNDERGROUND_AQUIFERS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_IDYLLIC_SCENERY', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_OPEN_SKIES', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_PROPHETIC_VISIONS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_MOUNTAIN_PASS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_OCEAN_SWELLS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_NATURAL_HARBOR', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_KARST_AQUIFERS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_FOG_DESERTS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ALLUVIAL_PLACER', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_FRESHWATER_FISHERY', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_SURFACE_DEPOSITS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_VANTAGE_POINTS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_STURDY_REEDS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_WINDY_PLAINS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ALTITUDE_TRAINING', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_DEFENSIBLE_CLIFFS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_CLAY_DEPOSITS', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_IGNEOUS_INTRUSION', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ML_VERTICAL_CLIMATE', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ML_MONSOON_VALLEY', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ML_YEW_GROVE', 'KIND_SUK_URBANIDENTITY'),
	('IDENTITY_SUK_ML_OASIS_TRADING_POST', 'KIND_SUK_URBANIDENTITY');
-------------------------------------
-- Urban Identities
-------------------------------------
	INSERT INTO Suk_UrbanIdentities (IdentityType, RegionOnly) VALUES
	('IDENTITY_SUK_HARDWOOD_TREES', 1),
	('IDENTITY_SUK_UNDERGROUND_AQUIFERS', 1),
	('IDENTITY_SUK_IDYLLIC_SCENERY', 1),
	('IDENTITY_SUK_OPEN_SKIES', 1),
	('IDENTITY_SUK_PROPHETIC_VISIONS', 1),
	('IDENTITY_SUK_MOUNTAIN_PASS', 1),
	('IDENTITY_SUK_OCEAN_SWELLS', 1),
	('IDENTITY_SUK_NATURAL_HARBOR', 1),
	('IDENTITY_SUK_KARST_AQUIFERS', 1),
	('IDENTITY_SUK_FOG_DESERTS', 1),
	('IDENTITY_SUK_ALLUVIAL_PLACER', 1),
	('IDENTITY_SUK_FRESHWATER_FISHERY', 1),
	('IDENTITY_SUK_SURFACE_DEPOSITS', 1),
	('IDENTITY_SUK_VANTAGE_POINTS', 1),
	('IDENTITY_SUK_STURDY_REEDS', 1),
	('IDENTITY_SUK_WINDY_PLAINS', 1),
	('IDENTITY_SUK_ALTITUDE_TRAINING', 1),
	('IDENTITY_SUK_DEFENSIBLE_CLIFFS', 1),
	('IDENTITY_SUK_CLAY_DEPOSITS', 1),
	('IDENTITY_SUK_IGNEOUS_INTRUSION', 1),
	('IDENTITY_SUK_ML_VERTICAL_CLIMATE', 1),
	('IDENTITY_SUK_ML_MONSOON_VALLEY', 1),
	('IDENTITY_SUK_ML_YEW_GROVE', 1),
	('IDENTITY_SUK_ML_OASIS_TRADING_POST', 1);
-------------------------------------
-- Identity Regions
-------------------------------------
	INSERT INTO Suk_UrbanIdentity_Regions (IdentityType, RegionType) VALUES
	(
		'IDENTITY_SUK_ALLUVIAL_PLACER', 'REGION_SUK_RIVER'
	),
	('IDENTITY_SUK_ALTITUDE_TRAINING', 'REGION_SUK_MOUNTAINS'),
	('IDENTITY_SUK_CLAY_DEPOSITS', 'REGION_SUK_PLAINS'),
	('IDENTITY_SUK_CLAY_DEPOSITS', 'REGION_SUK_LAKE'),
	('IDENTITY_SUK_CLAY_DEPOSITS', 'REGION_SUK_RIVER'),
	('IDENTITY_SUK_DEFENSIBLE_CLIFFS', 'REGION_SUK_CLIFFS'),
	('IDENTITY_SUK_FOG_DESERTS', 'REGION_SUK_DESERT'),
	('IDENTITY_SUK_FRESHWATER_FISHERY', 'REGION_SUK_LAKE'),
	('IDENTITY_SUK_HARDWOOD_TREES', 'REGION_SUK_JUNGLE'),
	('IDENTITY_SUK_HARDWOOD_TREES', 'REGION_SUK_FOREST'),
	('IDENTITY_SUK_IDYLLIC_SCENERY', 'REGION_SUK_FOREST'),
	('IDENTITY_SUK_IDYLLIC_SCENERY', 'REGION_SUK_RIVER'),
	('IDENTITY_SUK_IDYLLIC_SCENERY', 'REGION_SUK_LAKE'),
	('IDENTITY_SUK_IGNEOUS_INTRUSION', 'REGION_SUK_HILLS'),
	('IDENTITY_SUK_KARST_AQUIFERS', 'REGION_SUK_PLAINS'),
	('IDENTITY_SUK_KARST_AQUIFERS', 'REGION_SUK_MARSH'),
	('IDENTITY_SUK_KARST_AQUIFERS', 'REGION_SUK_LAKE'),
	('IDENTITY_SUK_KARST_AQUIFERS', 'REGION_SUK_RIVER'),
	('IDENTITY_SUK_MOUNTAIN_PASS', 'REGION_SUK_MOUNTAINS'),
	('IDENTITY_SUK_NATURAL_HARBOR', 'REGION_SUK_REEF'),
	('IDENTITY_SUK_NATURAL_HARBOR', 'REGION_SUK_CLIFFS'),
	('IDENTITY_SUK_NATURAL_HARBOR', 'REGION_SUK_KELP'),
	('IDENTITY_SUK_OCEAN_SWELLS', 'REGION_SUK_KELP'),
	('IDENTITY_SUK_OCEAN_SWELLS', 'REGION_SUK_REEF'),
	('IDENTITY_SUK_OCEAN_SWELLS', 'REGION_SUK_CLIFFS'),
	('IDENTITY_SUK_OPEN_SKIES', 'REGION_SUK_PLAINS'),
	('IDENTITY_SUK_OPEN_SKIES', 'REGION_SUK_DESERT'),
	('IDENTITY_SUK_PROPHETIC_VISIONS', 'REGION_SUK_GEOTHERMAL'),
	('IDENTITY_SUK_PROPHETIC_VISIONS', 'REGION_SUK_MARSH'),
	('IDENTITY_SUK_STURDY_REEDS', 'REGION_SUK_LAKE'),
	('IDENTITY_SUK_STURDY_REEDS', 'REGION_SUK_KELP'),
	('IDENTITY_SUK_SURFACE_DEPOSITS', 'REGION_SUK_PLAINS'),
	('IDENTITY_SUK_UNDERGROUND_AQUIFERS', 'REGION_SUK_OASIS'),
	('IDENTITY_SUK_UNDERGROUND_AQUIFERS', 'REGION_SUK_DESERT'),
	('IDENTITY_SUK_VANTAGE_POINTS', 'REGION_SUK_MOUNTAINS'),
	('IDENTITY_SUK_VANTAGE_POINTS', 'REGION_SUK_HILLS'),
	('IDENTITY_SUK_VANTAGE_POINTS', 'REGION_SUK_CLIFFS'),
	('IDENTITY_SUK_WINDY_PLAINS', 'REGION_SUK_PLAINS'),
	('IDENTITY_SUK_ML_VERTICAL_CLIMATE', 'REGION_SUK_MOUNTAINS'),
	('IDENTITY_SUK_ML_MONSOON_VALLEY', 'REGION_SUK_JUNGLE'),
	('IDENTITY_SUK_ML_YEW_GROVE', 'REGION_SUK_FOREST'),
	('IDENTITY_SUK_ML_OASIS_TRADING_POST', 'REGION_SUK_OASIS');
--=============================================================
--=============================================================